// Pluggable AI provider.
// If an API key is configured, real prompts are generated by an LLM.
// Otherwise everything falls back to the deterministic template generator.
//
//   ANTHROPIC_API_KEY  -> uses Anthropic Messages API (claude)
//   OPENAI_API_KEY     -> uses OpenAI Chat Completions
//   AI_PROVIDER        -> force "anthropic" | "openai" | "template" (optional)
//
// Uses native fetch (Node 18+). No SDK dependency.

const ANTHROPIC_MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";
const OPENAI_MODEL = process.env.OPENAI_MODEL || "gpt-4o-mini";

export function activeProvider() {
  const forced = (process.env.AI_PROVIDER || "").toLowerCase();
  if (forced) return forced;
  if (process.env.ANTHROPIC_API_KEY) return "anthropic";
  if (process.env.OPENAI_API_KEY) return "openai";
  return "template";
}

export function aiEnabled() {
  return activeProvider() !== "template";
}

async function callAnthropic(system, user, maxTokens = 1024) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      max_tokens: maxTokens,
      system,
      messages: [{ role: "user", content: user }]
    })
  });
  if (!res.ok) throw new Error(`Anthropic ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return data.content?.map((b) => b.text).join("") ?? "";
}

async function callOpenAI(system, user, maxTokens = 1024) {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${process.env.OPENAI_API_KEY}`
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      max_tokens: maxTokens,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user }
      ]
    })
  });
  if (!res.ok) throw new Error(`OpenAI ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return data.choices?.[0]?.message?.content ?? "";
}

// Low-level: ask the active LLM for raw text. Returns null if no provider.
export async function llmComplete(system, user, maxTokens) {
  const provider = activeProvider();
  if (provider === "anthropic") return callAnthropic(system, user, maxTokens);
  if (provider === "openai") return callOpenAI(system, user, maxTokens);
  return null;
}

// Ask the LLM for a JSON object. Strips code fences and parses.
// Returns null on any failure so callers can fall back to templates.
export async function llmJSON(system, user, maxTokens) {
  try {
    const text = await llmComplete(system, user, maxTokens);
    if (!text) return null;
    const cleaned = text
      .replace(/^```(?:json)?\s*/i, "")
      .replace(/\s*```\s*$/i, "")
      .trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) return null;
    return JSON.parse(cleaned.slice(start, end + 1));
  } catch (err) {
    console.warn("[ai] llmJSON failed, falling back to template:", err.message);
    return null;
  }
}

const SUNO_SYSTEM =
  "You are a music-direction assistant that writes concise, vivid Suno AI v5.5 style prompts. " +
  "A good prompt names genre, vocal character, key instruments, mood, tempo and key in one flowing line. " +
  "Never mention real recording artists by name; describe sound, not people. " +
  "Always respond with the exact JSON shape requested, no extra commentary.";

// --- AI-backed generators (each returns null if AI is unavailable/failed) ---

export async function aiArtistCard(name) {
  const user =
    `Create an original artist/style card for the name "${name}". ` +
    `Respond as JSON: {"genre":string,"bpm":number,"key":string,` +
    `"mood":string[],"vocals":string,"instruments":string[],"prompt":string,"tags":string[]}.`;
  const json = await llmJSON(SUNO_SYSTEM, user, 700);
  if (!json || !json.prompt) return null;
  return {
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    name,
    genre: json.genre || "AI",
    era: "AI-generated",
    mood: Array.isArray(json.mood) ? json.mood : [],
    bpm: json.bpm || null,
    key: json.key || "",
    vocals: json.vocals || "",
    instruments: Array.isArray(json.instruments) ? json.instruments : [],
    prompt: json.prompt,
    tags: Array.isArray(json.tags) ? json.tags : [],
    generated: true,
    ai: true
  };
}

export async function aiPromptFromAnalysis(meta, catalogNames) {
  const user =
    `An uploaded audio file was analysed. Real extracted metadata:\n` +
    JSON.stringify(meta, null, 2) +
    `\n\nFrom this catalog of style names: ${catalogNames.join(", ")}.\n` +
    `Respond as JSON: {"prompt":string,"era":string,"genre":string,` +
    `"vocals":string,"closest":string[3]} where "closest" are the 3 names ` +
    `from the catalog that best match the detected sound.`;
  const json = await llmJSON(SUNO_SYSTEM, user, 700);
  if (!json || !json.prompt) return null;
  return json;
}
