import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "data", "artists.json");

const existing = JSON.parse(await readFile(dataPath, "utf8"));
const existingNames = new Set(existing.map(a => a.name.toLowerCase()));

const E = (id, name, language, languageLabel, genre, subgenre, era, mood, bpm, key, vocals, prompt, tags, free = false, isNew = true) =>
  ({ id, name, language, languageLabel, genre, subgenre, era, mood, bpm, key, vocals, prompt, tags, free, isNew });

const newEntries = [

  // ══════════════════════════════════════════════════════════════════════════
  // ENGLISH / AMERICAN  (en: 80 → 140)
  // ══════════════════════════════════════════════════════════════════════════

  // — Soul / Motown / Funk
  E("en-aretha-franklin","Aretha Franklin","en","Зарубежные","Soul","gospel soul / R&B","1960s",["powerful","commanding"],105,"C major","Queen of Soul — gospel-trained mezzo with melismatic mastery","1960s gospel soul (soul), commanding gospel-trained mezzo with melismatic runs, English-language vocals, Hammond B-3 organ, tight horn section, Memphis-soul rhythm section, powerful and commanding mood, fits a soul classics playlist, 105 BPM, C major",["soul","gospel soul","1960s","powerful","commanding"],true),
  E("en-marvin-gaye","Marvin Gaye","en","Зарубежные","Soul","Motown soul / quiet storm","1970s",["sensual","conscious"],95,"E-flat major","silky multi-tracked Motown tenor with falsetto","1970s Motown soul (soul), silky multi-tracked tenor with falsetto, English-language vocals, layered background vocals, congas, Rhodes electric piano, lush strings, sensual and conscious mood, fits a quiet storm playlist, 95 BPM, E-flat major",["soul","Motown","1970s","sensual","conscious"],true),
  E("en-ray-charles","Ray Charles","en","Зарубежные","Soul","R&B / gospel / country","1960s",["soulful","virtuosic"],112,"F major","gospel-blues baritone with growl","1960s R&B (soul), gospel-blues baritone with growl, English-language vocals, electric piano, gospel choir, blues horn section, soulful virtuosic mood, fits an R&B legends playlist, 112 BPM, F major",["soul","R&B","1960s","soulful","virtuosic"],true),
  E("en-james-brown","James Brown","en","Зарубежные","Funk","funk / soul","1970s",["energetic","groove-locked"],115,"D minor","Godfather of Funk — grunting commanding baritone with screams","1970s funk (funk), grunting commanding baritone with screams, English-language vocals, syncopated horn stabs, scratching funk guitar, locked-in drum break, energetic groove-locked mood, fits a funk classics playlist, 115 BPM, D minor",["funk","soul","1970s","energetic","groove-locked"],true),
  E("en-otis-redding","Otis Redding","en","Зарубежные","Soul","Southern soul / Stax","1960s",["raw","heartbreak"],95,"C major","gritty Southern soul baritone","1960s Southern soul (soul), gritty Southern baritone, English-language vocals, Memphis Horns section, electric guitar, soulful organ, raw heartbreak mood, fits a Stax soul playlist, 95 BPM, C major",["soul","Southern soul","1960s","raw","heartbreak"],true),
  E("en-diana-ross","Diana Ross","en","Зарубежные","Pop","Motown / disco / pop","1970s",["glamorous","silky"],118,"F major","silky Motown soprano","1970s Motown (pop), silky soprano, English-language vocals, lush Motown arrangements, strings and brass, glamorous mood, fits a disco-era pop playlist, 118 BPM, F major",["pop","Motown","1970s","glamorous","silky"]),
  E("en-smokey-robinson","Smokey Robinson","en","Зарубежные","Soul","Motown soul","1960s",["smooth","romantic"],110,"E-flat major","smooth Motown falsetto tenor","1960s Motown soul (soul), smooth falsetto tenor, English-language vocals, finger-snaps, Motown rhythm section, glockenspiel, romantic mood, fits a Motown romance playlist, 110 BPM, E-flat major",["soul","Motown","1960s","smooth","romantic"]),
  E("en-al-green","Al Green","en","Зарубежные","Soul","Memphis soul / gospel","1970s",["sensual","tender"],90,"A major","Memphis-soul tender tenor with falsetto","1970s Memphis soul (soul), tender tenor with falsetto, English-language vocals, Hi Records rhythm section, vibraphone, sensual mood, fits a love-song soul playlist, 90 BPM, A major",["soul","Memphis soul","1970s","sensual","tender"],true),
  E("en-curtis-mayfield","Curtis Mayfield","en","Зарубежные","Funk","funk / soul / blaxploitation","1970s",["conscious","cinematic"],105,"F minor","Chicago falsetto tenor with social commentary","1970s blaxploitation funk (funk), Chicago falsetto tenor, English-language vocals, wah-wah guitar, congas, orchestral strings, conscious cinematic mood, fits a 70s funk playlist, 105 BPM, F minor",["funk","soul","1970s","conscious","cinematic"]),

  // — Classic rock canon
  E("en-the-who","The Who","en","Зарубежные","Rock","mod rock / hard rock","1960s",["explosive","rebellious"],138,"A major","Daltrey howling rock tenor","1960s mod rock (rock), howling tenor, English-language vocals, windmill power chords, thunderous drumming, smashed equipment energy, explosive rebellious mood, fits a classic rock playlist, 138 BPM, A major",["rock","mod rock","1960s","explosive","rebellious"]),
  E("en-the-kinks","The Kinks","en","Зарубежные","Rock","British invasion / proto-punk","1960s",["catchy","British"],120,"E major","Ray Davies wry English baritone","1960s British invasion (rock), wry English baritone, English-language vocals, riff-driven guitar, character-based songwriting, catchy British mood, fits a 60s British playlist, 120 BPM, E major",["rock","British invasion","1960s","catchy","British"]),
  E("en-black-sabbath","Black Sabbath","en","Зарубежные","Metal","heavy metal / doom","1970s",["heavy","ominous"],90,"D minor","Ozzy wailing doomy tenor","1970s heavy metal (metal), wailing doomy tenor, English-language vocals, downtuned riffs, tritone intervals, sludgy rhythm section, heavy ominous mood, fits a metal origins playlist, 90 BPM, D minor",["metal","heavy metal","1970s","heavy","ominous"],true),
  E("en-deep-purple","Deep Purple","en","Зарубежные","Rock","hard rock / proto-metal","1970s",["virtuosic","heavy"],125,"G minor","operatic hard-rock tenor","1970s hard rock (rock), operatic tenor, English-language vocals, virtuoso Hammond organ, screaming guitar, fast double-bass drumming, virtuosic heavy mood, fits a classic hard rock playlist, 125 BPM, G minor",["rock","hard rock","1970s","virtuosic","heavy"]),
  E("en-aerosmith","Aerosmith","en","Зарубежные","Rock","hard rock / blues rock","1970s",["swaggering","raunchy"],128,"E major","Steven Tyler screaming bluesy tenor","1970s hard rock (rock), screaming bluesy tenor, English-language vocals, twin-guitar attack, harmonica, swaggering raunchy mood, fits a hard rock playlist, 128 BPM, E major",["rock","hard rock","1970s","swaggering","raunchy"]),
  E("en-van-halen","Van Halen","en","Зарубежные","Rock","hard rock / arena","1980s",["virtuosic","party"],132,"A major","David Lee Roth swaggering tenor","1980s arena hard rock (rock), swaggering tenor, English-language vocals, virtuosic two-handed tap-guitar, big drum sound, party mood, fits an 80s arena rock playlist, 132 BPM, A major",["rock","hard rock","1980s","virtuosic","party"]),
  E("en-guns-n-roses","Guns N' Roses","en","Зарубежные","Rock","hard rock / glam metal","1980s",["dangerous","epic"],128,"D minor","Axl Rose snarling four-octave tenor","1980s hard rock (rock), snarling four-octave tenor, English-language vocals, dueling lead/rhythm guitar, big-rock production, dangerous epic mood, fits a classic hard rock playlist, 128 BPM, D minor",["rock","hard rock","1980s","dangerous","epic"],true),
  E("en-bon-jovi","Bon Jovi","en","Зарубежные","Rock","arena rock / glam","1980s",["anthemic","working-class"],120,"E major","Jersey arena-rock tenor","1980s arena rock (rock), anthemic tenor, English-language vocals, talk-box guitar, stadium drums, anthemic working-class mood, fits an 80s rock playlist, 120 BPM, E major",["rock","arena rock","1980s","anthemic","working-class"]),
  E("en-eagles","Eagles","en","Зарубежные","Rock","country rock / soft rock","1970s",["smooth","Californian"],95,"B minor","layered country-rock harmonies","1970s country rock (rock), layered tenor harmonies, English-language vocals, clean electric guitar, Californian production, smooth mood, fits a 70s rock playlist, 95 BPM, B minor",["rock","country rock","1970s","smooth","Californian"],true),
  E("en-bruce-springsteen","Bruce Springsteen","en","Зарубежные","Rock","heartland rock","1970s",["working-class","anthemic"],128,"E major","gravelly heartland-rock baritone","1970s heartland rock (rock), gravelly baritone, English-language vocals, E-Street Band horns, glockenspiel, working-class anthemic mood, fits a heartland rock playlist, 128 BPM, E major",["rock","heartland rock","1970s","working-class","anthemic"],true),
  E("en-tom-petty","Tom Petty","en","Зарубежные","Rock","heartland rock / Americana","1970s",["laid-back","melodic"],118,"A major","drawling Southern tenor","1970s heartland rock (rock), drawling tenor, English-language vocals, jangly Rickenbacker guitar, organ, laid-back melodic mood, fits a classic rock road-trip playlist, 118 BPM, A major",["rock","heartland rock","1970s","laid-back","melodic"]),
  E("en-neil-young","Neil Young","en","Зарубежные","Rock","folk rock / grunge precursor","1970s",["plaintive","raw"],105,"D major","plaintive nasal high tenor","1970s folk rock (rock), plaintive nasal high tenor, English-language vocals, distorted Crazy Horse guitar, harmonica, raw mood, fits a folk-rock playlist, 105 BPM, D major",["rock","folk rock","1970s","plaintive","raw"],true),
  E("en-simon-garfunkel","Simon & Garfunkel","en","Зарубежные","Folk","folk pop / harmony folk","1960s",["serene","poetic"],100,"E-flat major","intertwined high-tenor harmony duo","1960s folk pop (folk), high-tenor harmony duo, English-language vocals, fingerpicked acoustic guitar, gentle orchestration, serene poetic mood, fits a folk pop playlist, 100 BPM, E-flat major",["folk","folk pop","1960s","serene","poetic"]),
  E("en-beach-boys","The Beach Boys","en","Зарубежные","Pop","surf rock / sunshine pop","1960s",["sunny","layered"],130,"G major","five-part Wilson harmony stack","1960s sunshine pop (pop), five-part harmony stack, English-language vocals, surf guitar, vibraphone, Wall-of-Sound production, sunny layered mood, fits a 60s pop playlist, 130 BPM, G major",["pop","sunshine pop","1960s","sunny","layered"]),
  E("en-santana","Santana","en","Зарубежные","Rock","Latin rock / blues rock","1970s",["spiritual","groovy"],120,"A minor","instrumental-led with guest vocalists","1970s Latin rock (rock), expressive guitar instrumental with guest tenor vocals, English/Spanish vocals, soaring sustained guitar, congas, timbales, organ, spiritual groovy mood, fits a Latin rock playlist, 120 BPM, A minor",["rock","Latin rock","1970s","spiritual","groovy"]),

  // — Metal expansions
  E("en-iron-maiden","Iron Maiden","en","Зарубежные","Metal","NWOBHM / heavy metal","1980s",["epic","galloping"],160,"E minor","Dickinson operatic air-raid-siren tenor","1980s heavy metal (metal), operatic air-raid-siren tenor, English-language vocals, galloping bass lines, twin lead guitars, double-bass drumming, epic galloping mood, fits a heavy metal playlist, 160 BPM, E minor",["metal","NWOBHM","1980s","epic","galloping"],true),
  E("en-judas-priest","Judas Priest","en","Зарубежные","Metal","heavy metal","1980s",["heavy","leather"],145,"E minor","Halford operatic banshee tenor","1980s heavy metal (metal), operatic banshee tenor, English-language vocals, twin-guitar riffing, leather-and-studs aesthetic, heavy mood, fits a metal classics playlist, 145 BPM, E minor",["metal","heavy metal","1980s","heavy","leather"]),
  E("en-slayer","Slayer","en","Зарубежные","Metal","thrash metal","1980s",["aggressive","brutal"],190,"E minor","Tom Araya shouted thrash bark","1980s thrash metal (metal), shouted thrash bark, English-language vocals, atonal tritone riffs, blast beats, brutal aggressive mood, fits a thrash playlist, 190 BPM, E minor",["metal","thrash metal","1980s","aggressive","brutal"]),
  E("en-megadeth","Megadeth","en","Зарубежные","Metal","thrash metal / technical","1980s",["technical","sardonic"],175,"E minor","Mustaine sneering thrash tenor","1980s technical thrash (metal), sneering thrash tenor, English-language vocals, intricate twin-guitar work, complex song structures, technical sardonic mood, fits a thrash playlist, 175 BPM, E minor",["metal","thrash metal","1980s","technical","sardonic"]),
  E("en-pantera","Pantera","en","Зарубежные","Metal","groove metal","1990s",["heavy","groovy"],130,"D minor","Phil Anselmo barked groove-metal baritone","1990s groove metal (metal), barked groove-metal baritone, English-language vocals, Dimebag squealing riffs, half-time groove drums, heavy groovy mood, fits a groove metal playlist, 130 BPM, D minor",["metal","groove metal","1990s","heavy","groovy"]),
  E("en-system-of-a-down","System of a Down","en","Зарубежные","Metal","alternative metal","2000s",["chaotic","political"],145,"E minor","Serj operatic Armenian-flavored tenor","2000s alt-metal (metal), operatic Armenian-flavored tenor, English-language vocals, Middle-Eastern scales, abrupt tempo shifts, chaotic political mood, fits an alt-metal playlist, 145 BPM, E minor",["metal","alt-metal","2000s","chaotic","political"]),
  E("en-tool","Tool","en","Зарубежные","Metal","progressive metal","1990s",["hypnotic","dark"],120,"D minor","Maynard hypnotic baritone","1990s progressive metal (metal), hypnotic baritone, English-language vocals, polyrhythmic drums, odd time signatures, downtuned guitar, hypnotic dark mood, fits a prog-metal playlist, 120 BPM, D minor",["metal","prog metal","1990s","hypnotic","dark"]),
  E("en-slipknot","Slipknot","en","Зарубежные","Metal","nu-metal / alternative metal","2000s",["aggressive","chaotic"],150,"D minor","Corey Taylor screamed-and-sung mix","2000s nu-metal (metal), screamed-and-sung tenor, English-language vocals, nine-piece percussive chaos, downtuned guitars, aggressive chaotic mood, fits a nu-metal playlist, 150 BPM, D minor",["metal","nu-metal","2000s","aggressive","chaotic"]),
  E("en-korn","Korn","en","Зарубежные","Metal","nu-metal","1990s",["dark","tortured"],120,"A minor","Jonathan Davis scat-tortured baritone","1990s nu-metal (metal), scat-tortured baritone, English-language vocals, seven-string downtuned guitar, slap bass, dark tortured mood, fits a nu-metal playlist, 120 BPM, A minor",["metal","nu-metal","1990s","dark","tortured"]),

  // — Hip-hop expansions
  E("en-jay-z","Jay-Z","en","Зарубежные","Hip-hop","East Coast / mogul rap","1990s",["confident","luxurious"],95,"F minor","laid-back Brooklyn baritone","1990s East Coast hip-hop (hip-hop), laid-back Brooklyn baritone, English-language vocals, soul-sample chops, boom-bap drums, luxurious confident mood, fits an East Coast playlist, 95 BPM, F minor",["hip-hop","East Coast","1990s","confident","luxurious"],true),
  E("en-nas","Nas","en","Зарубежные","Hip-hop","East Coast / lyrical","1990s",["lyrical","poetic"],88,"D minor","conversational Queens-bred baritone","1990s East Coast hip-hop (hip-hop), conversational Queens baritone, English-language vocals, jazz-soul samples, dusty drums, lyrical poetic mood, fits an East Coast playlist, 88 BPM, D minor",["hip-hop","East Coast","1990s","lyrical","poetic"],true),
  E("en-notorious-big","The Notorious B.I.G.","en","Зарубежные","Hip-hop","East Coast / gangsta rap","1990s",["smooth","menacing"],92,"G minor","Biggie smooth-flowing baritone","1990s East Coast gangsta rap (hip-hop), smooth-flowing baritone, English-language vocals, soul sample chops, hard-knocking drums, smooth menacing mood, fits a 90s hip-hop playlist, 92 BPM, G minor",["hip-hop","East Coast","1990s","smooth","menacing"],true),
  E("en-snoop-dogg","Snoop Dogg","en","Зарубежные","Hip-hop","West Coast / g-funk","1990s",["laid-back","cool"],95,"F minor","laid-back drawled West Coast tenor","1990s West Coast g-funk (hip-hop), laid-back drawled tenor, English-language vocals, synth whines, deep funk bass, snare rolls, laid-back cool mood, fits a g-funk playlist, 95 BPM, F minor",["hip-hop","g-funk","1990s","laid-back","cool"]),
  E("en-dr-dre","Dr. Dre","en","Зарубежные","Hip-hop","g-funk / production","1990s",["smooth","cinematic"],95,"G minor","producer-led with guest verses","1990s g-funk (hip-hop), commanding producer baritone with guest verses, English-language vocals, P-funk synths, deep 808s, immaculate Detox-era mix, smooth cinematic mood, fits a West Coast playlist, 95 BPM, G minor",["hip-hop","g-funk","1990s","smooth","cinematic"]),
  E("en-wu-tang-clan","Wu-Tang Clan","en","Зарубежные","Hip-hop","East Coast / hardcore","1990s",["gritty","kung-fu"],90,"E minor","nine-emcee Staten Island collective","1990s hardcore hip-hop (hip-hop), nine-emcee collective, English-language vocals, dusty kung-fu film samples, lo-fi RZA drums, gritty mood, fits an East Coast playlist, 90 BPM, E minor",["hip-hop","East Coast","1990s","gritty","kung-fu"],true),
  E("en-outkast","OutKast","en","Зарубежные","Hip-hop","Southern hip-hop / funk rap","1990s",["funky","eclectic"],100,"F major","André 3000 melodic and Big Boi rhythmic","1990s Southern hip-hop (hip-hop), André 3000 melodic and Big Boi rhythmic duo, English-language vocals, live funk instrumentation, eclectic production, funky mood, fits a Southern hip-hop playlist, 100 BPM, F major",["hip-hop","Southern","1990s","funky","eclectic"],true),
  E("en-tribe-called-quest","A Tribe Called Quest","en","Зарубежные","Hip-hop","jazz rap / Native Tongues","1990s",["smooth","jazzy"],92,"D minor","Q-Tip nasal tenor and Phife streetwise baritone","1990s jazz rap (hip-hop), Q-Tip nasal tenor and Phife baritone duo, English-language vocals, upright-bass samples, jazzy chords, smooth jazzy mood, fits a jazz rap playlist, 92 BPM, D minor",["hip-hop","jazz rap","1990s","smooth","jazzy"]),
  E("en-public-enemy","Public Enemy","en","Зарубежные","Hip-hop","political hip-hop","1980s",["political","intense"],100,"A minor","Chuck D booming baritone with Flav hype","1980s political hip-hop (hip-hop), Chuck D booming baritone with Flav hype, English-language vocals, Bomb Squad noise collages, sirens, James Brown drum breaks, political intense mood, fits a hip-hop classics playlist, 100 BPM, A minor",["hip-hop","political","1980s","political","intense"],true),
  E("en-run-dmc","Run-DMC","en","Зарубежные","Hip-hop","old-school hip-hop","1980s",["raw","rebellious"],105,"E minor","call-and-response Queens duo","1980s old-school hip-hop (hip-hop), call-and-response Queens duo, English-language vocals, hard 808 drums, rock-guitar samples, raw rebellious mood, fits an old-school playlist, 105 BPM, E minor",["hip-hop","old-school","1980s","raw","rebellious"]),
  E("en-nwa","N.W.A.","en","Зарубежные","Hip-hop","West Coast / gangsta rap (pioneers)","1980s",["raw","political"],95,"G minor","group-format raw West Coast vocals","1980s gangsta rap (hip-hop), group raw vocals, English-language vocals, hard funk samples, Ice Cube and Eazy-E trade verses, raw political mood, fits a gangsta rap origins playlist, 95 BPM, G minor",["hip-hop","gangsta rap","1980s","raw","political"]),
  E("en-lauryn-hill","Lauryn Hill","en","Зарубежные","Hip-hop","neo-soul / hip-hop","1990s",["soulful","lyrical"],90,"E minor","Lauryn Hill soulful sung-and-rapped alto","1990s neo-soul hip-hop (hip-hop), soulful sung-and-rapped alto, English-language vocals, organic live instrumentation, reggae touches, soulful lyrical mood, fits a neo-soul playlist, 90 BPM, E minor",["hip-hop","neo-soul","1990s","soulful","lyrical"],true),
  E("en-missy-elliott","Missy Elliott","en","Зарубежные","Hip-hop","R&B / dance rap","1990s",["futuristic","fun"],105,"A minor","Missy playful experimental rapper","1990s R&B rap (hip-hop), playful experimental rapper, English-language vocals, Timbaland futuristic beats, beatboxing, fun futuristic mood, fits a 90s hip-hop playlist, 105 BPM, A minor",["hip-hop","R&B","1990s","futuristic","fun"]),
  E("en-lil-wayne","Lil Wayne","en","Зарубежные","Hip-hop","Southern hip-hop / mixtape rap","2000s",["raspy","prolific"],90,"F minor","Weezy raspy auto-tuned baritone","2000s Southern hip-hop (hip-hop), raspy auto-tuned baritone, English-language vocals, New Orleans bounce production, melodic 808s, prolific mood, fits a Southern rap playlist, 90 BPM, F minor",["hip-hop","Southern","2000s","raspy","prolific"]),
  E("en-nicki-minaj","Nicki Minaj","en","Зарубежные","Hip-hop","pop rap","2010s",["versatile","fierce"],128,"E minor","character-switching Trinidadian-Queens rapper","2010s pop rap (hip-hop), character-switching versatile rapper, English-language vocals, pop-rap beats, fierce mood, fits a pop rap playlist, 128 BPM, E minor",["hip-hop","pop rap","2010s","versatile","fierce"]),
  E("en-cardi-b","Cardi B","en","Зарубежные","Hip-hop","trap / pop rap","2010s",["fierce","Bronx"],95,"A minor","Bronx blunt confident female rapper","2010s trap pop rap (hip-hop), blunt confident female rapper, English-language vocals, modern trap beats, sliding 808s, fierce Bronx mood, fits a trap playlist, 95 BPM, A minor",["hip-hop","trap","2010s","fierce","Bronx"]),
  E("en-megan-thee-stallion","Megan Thee Stallion","en","Зарубежные","Hip-hop","Southern hip-hop / trap","2010s",["confident","Houston"],100,"F minor","Houston hottie commanding female rapper","2010s Southern trap (hip-hop), commanding female rapper, English-language vocals, Houston-Atlanta hybrid trap beats, confident mood, fits a trap playlist, 100 BPM, F minor",["hip-hop","Southern","2010s","confident","Houston"]),
  E("en-j-cole","J. Cole","en","Зарубежные","Hip-hop","conscious hip-hop","2010s",["introspective","grounded"],88,"C minor","J. Cole introspective laid-back baritone","2010s conscious hip-hop (hip-hop), introspective laid-back baritone, English-language vocals, self-produced soulful loops, organic drums, introspective grounded mood, fits a conscious rap playlist, 88 BPM, C minor",["hip-hop","conscious","2010s","introspective","grounded"]),
  E("en-tyler-the-creator","Tyler, the Creator","en","Зарубежные","Hip-hop","alt hip-hop / neo-soul","2010s",["eclectic","colorful"],100,"D major","Tyler eccentric baritone / falsetto switch","2010s alt hip-hop (hip-hop), eccentric baritone with falsetto switches, English-language vocals, lush jazzy chords, self-produced, eclectic colorful mood, fits an alt hip-hop playlist, 100 BPM, D major",["hip-hop","alt hip-hop","2010s","eclectic","colorful"]),
  E("en-frank-ocean","Frank Ocean","en","Зарубежные","R&B","alternative R&B","2010s",["intimate","ethereal"],90,"C major","Frank Ocean intimate falsetto-tenor","2010s alt R&B (R&B), intimate falsetto-tenor, English-language vocals, sparse instrumentation, ambient guitar, dreamy production, intimate ethereal mood, fits an alt R&B playlist, 90 BPM, C major",["R&B","alt R&B","2010s","intimate","ethereal"],true),
  E("en-childish-gambino","Childish Gambino","en","Зарубежные","Hip-hop","alt hip-hop / funk","2010s",["versatile","cinematic"],110,"E minor","Donald Glover versatile rapper-singer","2010s alt hip-hop (hip-hop), versatile rapper-singer, English-language vocals, funk-soul live instrumentation, cinematic mood, fits an alt hip-hop playlist, 110 BPM, E minor",["hip-hop","alt hip-hop","2010s","versatile","cinematic"]),
  E("en-anderson-paak","Anderson .Paak","en","Зарубежные","R&B","neo-soul / funk","2010s",["groovy","raspy"],105,"B-flat major","raspy drumming-rapper-singer","2010s neo-soul (R&B), raspy drumming-rapper-singer, English-language vocals, live drums, funk bass, smooth keys, groovy mood, fits a neo-soul playlist, 105 BPM, B-flat major",["R&B","neo-soul","2010s","groovy","raspy"]),
  E("en-sza","SZA","en","Зарубежные","R&B","alt R&B","2010s",["intimate","conversational"],95,"E minor","SZA conversational alto","2010s alt R&B (R&B), conversational alto, English-language vocals, soft chords, brushed drums, intimate mood, fits an alt R&B playlist, 95 BPM, E minor",["R&B","alt R&B","2010s","intimate","conversational"]),
  E("en-doja-cat","Doja Cat","en","Зарубежные","Pop","pop rap / R&B","2010s",["playful","catchy"],108,"F minor","versatile pop-rap soprano","2010s pop rap (pop), versatile pop-rap soprano, English-language vocals, glossy pop production with hip-hop touches, playful mood, fits a modern pop playlist, 108 BPM, F minor",["pop","pop rap","2010s","playful","catchy"]),

  // — Modern pop / indie
  E("en-lana-del-rey","Lana Del Rey","en","Зарубежные","Pop","sadcore / cinematic pop","2010s",["nostalgic","melancholic"],85,"D minor","Lana sultry breathy alto","2010s cinematic pop (pop), sultry breathy alto, English-language vocals, lush orchestral strings, lo-fi hip-hop drums, nostalgic melancholic mood, fits a sad pop playlist, 85 BPM, D minor",["pop","sadcore","2010s","nostalgic","melancholic"],true),
  E("en-lorde","Lorde","en","Зарубежные","Pop","art pop / electropop","2010s",["minimal","introspective"],95,"E-flat minor","Lorde dark-pop alto","2010s art pop (pop), dark-pop alto, English-language vocals, minimal finger-snap percussion, sparse production, introspective mood, fits an alt-pop playlist, 95 BPM, E-flat minor",["pop","art pop","2010s","minimal","introspective"]),
  E("en-olivia-rodrigo","Olivia Rodrigo","en","Зарубежные","Pop","pop punk / power ballad","2020s",["angsty","cinematic"],110,"G major","Olivia angsty Gen-Z soprano","2020s pop punk (pop), angsty Gen-Z soprano, English-language vocals, distorted guitar, big drums, angsty cinematic mood, fits a Gen-Z playlist, 110 BPM, G major",["pop","pop punk","2020s","angsty","cinematic"]),
  E("en-halsey","Halsey","en","Зарубежные","Pop","alt pop / electropop","2010s",["dark","cinematic"],100,"F minor","Halsey edgy alto","2010s alt pop (pop), edgy alto, English-language vocals, dark synth pads, cinematic production, fits an alt-pop playlist, 100 BPM, F minor",["pop","alt pop","2010s","dark","cinematic"]),
  E("en-sabrina-carpenter","Sabrina Carpenter","en","Зарубежные","Pop","pop / disco-pop","2020s",["playful","witty"],120,"B minor","Sabrina playful pop soprano","2020s pop (pop), playful witty soprano, English-language vocals, disco-influenced production, polished mix, fits a modern pop playlist, 120 BPM, B minor",["pop","pop","2020s","playful","witty"]),
  E("en-mitski","Mitski","en","Зарубежные","Rock","indie rock / art rock","2010s",["aching","raw"],100,"D minor","Mitski aching tortured alto","2010s indie rock (rock), aching tortured alto, English-language vocals, jagged guitars, sparse production, aching raw mood, fits an indie playlist, 100 BPM, D minor",["rock","indie rock","2010s","aching","raw"]),
  E("en-phoebe-bridgers","Phoebe Bridgers","en","Зарубежные","Folk","indie folk / chamber pop","2010s",["ghostly","sad"],95,"E minor","Phoebe whispered ghostly alto","2010s indie folk (folk), whispered ghostly alto, English-language vocals, fingerpicked guitar, swelling strings, sad ghostly mood, fits a sad indie playlist, 95 BPM, E minor",["folk","indie folk","2010s","ghostly","sad"]),
  E("en-bon-iver","Bon Iver","en","Зарубежные","Folk","indie folk / chamber pop","2000s",["intimate","Wisconsin"],85,"C major","Justin Vernon ethereal falsetto","2000s indie folk (folk), ethereal falsetto, English-language vocals, layered vocal stacks, acoustic guitar, intimate Wisconsin-cabin mood, fits an intimate folk playlist, 85 BPM, C major",["folk","indie folk","2000s","intimate","Wisconsin"]),
  E("en-arcade-fire","Arcade Fire","en","Зарубежные","Rock","indie rock / chamber rock","2000s",["anthemic","communal"],128,"D major","Win Butler quavering anthemic baritone","2000s indie rock (rock), quavering anthemic baritone, English-language vocals, layered orchestral instrumentation, communal singalong, fits an indie rock playlist, 128 BPM, D major",["rock","indie rock","2000s","anthemic","communal"]),
  E("en-vampire-weekend","Vampire Weekend","en","Зарубежные","Rock","indie rock / Afro-pop influenced","2000s",["preppy","intelligent"],130,"D major","Ezra Koenig preppy tenor","2000s indie rock (rock), preppy tenor, English-language vocals, harpsichord, Afro-pop guitar lines, intelligent mood, fits an indie playlist, 130 BPM, D major",["rock","indie rock","2000s","preppy","intelligent"]),
  E("en-the-national","The National","en","Зарубежные","Rock","indie rock / chamber rock","2000s",["melancholic","brooding"],110,"D minor","Matt Berninger drunken baritone","2000s indie rock (rock), drunken baritone, English-language vocals, intricate drumming, layered guitar, brooding melancholic mood, fits an indie playlist, 110 BPM, D minor",["rock","indie rock","2000s","melancholic","brooding"]),
  E("en-tame-impala","Tame Impala","en","Зарубежные","Rock","psychedelic / synth-pop","2010s",["psychedelic","groovy"],115,"E minor","Kevin Parker dreamy falsetto","2010s psychedelic synth-pop (rock), dreamy falsetto, English-language vocals, phased synths, vintage drum machines, psychedelic groovy mood, fits a psych playlist, 115 BPM, E minor",["rock","psychedelic","2010s","psychedelic","groovy"],true),

  // — Country / Americana
  E("en-george-strait","George Strait","en","Зарубежные","Country","neo-traditional country","1980s",["smooth","Texan"],110,"G major","George Strait smooth Texas baritone","1980s neo-traditional country (country), smooth Texas baritone, English-language vocals, fiddle, pedal steel, two-step rhythm, smooth Texan mood, fits a country classics playlist, 110 BPM, G major",["country","neo-traditional","1980s","smooth","Texan"]),
  E("en-shania-twain","Shania Twain","en","Зарубежные","Country","country pop / crossover","1990s",["sassy","crossover"],115,"D major","Shania country-pop soprano","1990s country pop (country), sassy soprano, English-language vocals, Mutt Lange polished country-pop production, crossover mood, fits a country pop playlist, 115 BPM, D major",["country","country pop","1990s","sassy","crossover"]),
  E("en-garth-brooks","Garth Brooks","en","Зарубежные","Country","modern country","1990s",["arena","heartfelt"],115,"E major","Garth Brooks Oklahoman baritone","1990s modern country (country), Oklahoman baritone, English-language vocals, arena-country production, fiddle and pedal steel, heartfelt mood, fits a country arena playlist, 115 BPM, E major",["country","modern country","1990s","arena","heartfelt"]),

  // — Electronic / EDM
  E("en-skrillex","Skrillex","en","Зарубежные","Electronic","dubstep / EDM","2010s",["aggressive","drop-heavy"],140,"F minor","Skrillex producer-led with vocal samples","2010s dubstep (electronic), producer with vocal samples, English-language vocals, screaming wobble bass, half-time drops, aggressive drop-heavy mood, fits a dubstep playlist, 140 BPM, F minor",["electronic","dubstep","2010s","aggressive","drop-heavy"]),
  E("en-deadmau5","deadmau5","en","Зарубежные","Electronic","progressive house","2000s",["minimal","melodic"],128,"A minor","deadmau5 mostly-instrumental electronic","2000s progressive house (electronic), instrumental with occasional guest vocals, English-language vocals, melodic synth leads, four-on-the-floor, minimal melodic mood, fits a house playlist, 128 BPM, A minor",["electronic","progressive house","2000s","minimal","melodic"]),
  E("en-calvin-harris","Calvin Harris","en","Зарубежные","Electronic","EDM / dance-pop","2010s",["catchy","summer"],128,"F minor","Scottish DJ-producer with guest vocalists","2010s EDM (electronic), producer with guest vocalists, English-language vocals, big-room synths, four-on-the-floor, catchy summer mood, fits a summer dance playlist, 128 BPM, F minor",["electronic","EDM","2010s","catchy","summer"]),
  E("en-david-guetta","David Guetta","en","Зарубежные","Electronic","EDM / electro house","2000s",["festival","big-room"],128,"A minor","French DJ-producer with guest vocals","2000s electro house (electronic), producer with guest vocals, English-language vocals, big-room electro synths, festival drops, fits a festival playlist, 128 BPM, A minor",["electronic","EDM","2000s","festival","big-room"]),
  E("en-aphex-twin","Aphex Twin","en","Зарубежные","Electronic","IDM / ambient","1990s",["unsettling","virtuosic"],150,"D minor","Aphex Twin mostly instrumental","1990s IDM (electronic), instrumental with manipulated vocal samples, English-language vocals, breakbeats, analog synths, unsettling virtuosic mood, fits an IDM playlist, 150 BPM, D minor",["electronic","IDM","1990s","unsettling","virtuosic"],true),

  // — Punk / pop-punk
  E("en-green-day","Green Day","en","Зарубежные","Rock","pop punk / punk rock","1990s",["bratty","catchy"],150,"E major","Billie Joe nasal pop-punk tenor","1990s pop punk (rock), nasal pop-punk tenor, English-language vocals, power-chord guitars, fast punk drums, bratty catchy mood, fits a pop-punk playlist, 150 BPM, E major",["rock","pop punk","1990s","bratty","catchy"]),
  E("en-blink-182","Blink-182","en","Зарубежные","Rock","pop punk","1990s",["bratty","party"],160,"G major","dual nasal pop-punk vocals","1990s pop punk (rock), dual nasal pop-punk vocals, English-language vocals, fast tempo, octave-jump bass, party mood, fits a pop-punk playlist, 160 BPM, G major",["rock","pop punk","1990s","bratty","party"]),
  E("en-ramones","Ramones","en","Зарубежные","Rock","punk rock","1970s",["fast","minimalist"],180,"A major","Joey Ramone bratty Queens tenor","1970s punk rock (rock), bratty Queens tenor, English-language vocals, three-chord buzz-saw guitar, minimalist drumming, fast mood, fits a punk classics playlist, 180 BPM, A major",["rock","punk rock","1970s","fast","minimalist"],true),
  E("en-sex-pistols","Sex Pistols","en","Зарубежные","Rock","punk rock / British punk","1970s",["snarling","anarchist"],160,"E major","Johnny Rotten sneering British snarl","1970s British punk (rock), sneering snarl, English-language vocals, raw distorted guitar, primitive drumming, snarling anarchist mood, fits a punk rock playlist, 160 BPM, E major",["rock","punk rock","1970s","snarling","anarchist"],true),
  E("en-clash","The Clash","en","Зарубежные","Rock","punk rock / post-punk / reggae","1970s",["political","eclectic"],145,"E minor","Joe Strummer gravelly punk baritone","1970s punk rock (rock), gravelly punk baritone, English-language vocals, reggae-tinged guitar, dub bass, political eclectic mood, fits a punk classics playlist, 145 BPM, E minor",["rock","punk rock","1970s","political","eclectic"],true),

  // — Singer-songwriters / pop staples
  E("en-john-mayer","John Mayer","en","Зарубежные","Pop","pop / blues rock / acoustic","2000s",["smooth","guitar-led"],95,"E major","John Mayer mellow tenor with smooth vibrato","2000s pop blues (pop), mellow tenor with smooth vibrato, English-language vocals, fingerpicked acoustic, blues-rock electric, smooth mood, fits a singer-songwriter playlist, 95 BPM, E major",["pop","singer-songwriter","2000s","smooth","guitar-led"]),
  E("en-norah-jones","Norah Jones","en","Зарубежные","Jazz","jazz / pop","2000s",["intimate","smoky"],85,"F major","Norah Jones intimate smoky alto","2000s jazz pop (jazz), intimate smoky alto, English-language vocals, piano-led arrangements, brushed snare, intimate mood, fits a coffee-shop jazz playlist, 85 BPM, F major",["jazz","jazz pop","2000s","intimate","smoky"]),
  E("en-alicia-keys","Alicia Keys","en","Зарубежные","R&B","soul / R&B","2000s",["powerful","piano-driven"],95,"E-flat minor","Alicia Keys gospel-trained piano-led soprano","2000s soul R&B (R&B), powerful piano-led soprano, English-language vocals, grand piano, gospel touches, powerful mood, fits an R&B playlist, 95 BPM, E-flat minor",["R&B","soul","2000s","powerful","piano-driven"]),
  E("en-lizzo","Lizzo","en","Зарубежные","Pop","pop / hip-hop / soul","2010s",["empowering","flute-led"],100,"G major","Lizzo soulful empowering soprano","2010s pop soul (pop), soulful empowering soprano with rap flow, English-language vocals, classical flute solos, brass, empowering mood, fits a body-positive playlist, 100 BPM, G major",["pop","pop","2010s","empowering","flute-led"]),
  E("en-sia","Sia","en","Зарубежные","Pop","pop / electropop","2010s",["powerhouse","emotional"],120,"A-flat major","Sia Australian powerhouse soprano","2010s electropop (pop), powerhouse Australian soprano, English-language vocals, big synth production, emotional mood, fits a pop power playlist, 120 BPM, A-flat major",["pop","electropop","2010s","powerhouse","emotional"]),
  E("en-madonna","Madonna","en","Зарубежные","Pop","dance pop / electropop","1980s",["iconic","provocative"],118,"D minor","Madonna chameleonic mezzo","1980s dance pop (pop), chameleonic mezzo, English-language vocals, era-defining synth production, dance beats, provocative mood, fits a Material-Girl playlist, 118 BPM, D minor",["pop","dance pop","1980s","iconic","provocative"],true),
  E("en-cher","Cher","en","Зарубежные","Pop","pop / dance pop","1970s",["husky","reinventing"],120,"A minor","Cher husky contralto","1970s dance pop (pop), husky contralto, English-language vocals, era-spanning production from disco to auto-tuned dance pop, reinventing mood, fits a divas playlist, 120 BPM, A minor",["pop","dance pop","1970s","husky","reinventing"]),
  E("en-whitney-houston-2","Janet Jackson","en","Зарубежные","Pop","R&B / dance pop","1980s",["controlled","sultry"],112,"F minor","Janet controlled breathy soprano","1980s R&B dance pop (pop), controlled breathy soprano, English-language vocals, Jam-and-Lewis production, slap bass, sultry mood, fits an 80s R&B playlist, 112 BPM, F minor",["pop","R&B","1980s","controlled","sultry"]),

  // ══════════════════════════════════════════════════════════════════════════
  // RUSSIAN  (ru: 58 → 110)
  // ══════════════════════════════════════════════════════════════════════════

  // — Эстрада / попса
  E("ru-alsou","Алсу","ru","Русские","Pop","эстрада / поп","2000s",["clear","youthful"],100,"D major","чистое юное сопрано Алсу","2000s Russian pop (pop), clear youthful soprano, Russian/English vocals, polished pop production, orchestral elements, fits a 2000s Russian pop playlist, 100 BPM, D major",["pop","эстрада","2000s","clear","youthful"]),
  E("ru-bilan","Дима Билан","ru","Русские","Pop","эстрада / Eurovision","2000s",["dramatic","slick"],120,"A minor","драматичный поп-тенор Билана","2000s Russian Eurovision pop (pop), dramatic pop tenor, Russian/English vocals, slick Eurovision-grade production, fits a Russian pop hits playlist, 120 BPM, A minor",["pop","эстрада","2000s","dramatic","slick"]),
  E("ru-lazarev","Сергей Лазарев","ru","Русские","Pop","эстрада / dance pop","2010s",["polished","glamorous"],120,"F minor","полированный поп-тенор","2010s Russian dance pop (pop), polished glamorous tenor, Russian/English vocals, glossy dance-pop production, fits a Russian glam pop playlist, 120 BPM, F minor",["pop","эстрада","2010s","polished","glamorous"]),
  E("ru-kirkorov","Филипп Киркоров","ru","Русские","Pop","эстрада / шоу-поп","2000s",["theatrical","grand"],110,"E minor","театральный король эстрады, баритон","2000s Russian show pop (pop), theatrical grand baritone, Russian vocals, lush orchestral pop, dramatic ballad production, fits a Russian estrada playlist, 110 BPM, E minor",["pop","эстрада","2000s","theatrical","grand"],true),
  E("ru-baskov","Николай Басков","ru","Русские","Pop","эстрада / классический кроссовер","2000s",["operatic","crossover"],100,"D major","классический кроссовер-тенор Баскова","2000s Russian classical crossover (pop), operatic tenor, Russian vocals, orchestral arrangements with pop sensibility, fits a Russian crossover playlist, 100 BPM, D major",["pop","эстрада","2000s","operatic","crossover"]),
  E("ru-gagarina","Полина Гагарина","ru","Русские","Pop","эстрада / поп-рок","2010s",["powerful","emotional"],100,"G minor","сильное драматичное сопрано","2010s Russian pop rock (pop), powerful emotional soprano, Russian vocals, anthemic pop-rock production, fits a Russian pop ballads playlist, 100 BPM, G minor",["pop","эстрада","2010s","powerful","emotional"]),
  E("ru-nyusha","Нюша","ru","Русские","Pop","поп / dance","2010s",["bright","danceable"],118,"F major","яркое поп-сопрано","2010s Russian pop (pop), bright soprano, Russian vocals, modern dance-pop production, fits a Russian radio pop playlist, 118 BPM, F major",["pop","dance pop","2010s","bright","danceable"]),
  E("ru-bianka","Бьянка","ru","Русские","Pop","поп / реггетон","2000s",["sultry","streetwise"],100,"D minor","заводное хриплое контральто","2000s Russian pop reggaeton (pop), sultry streetwise contralto, Russian vocals, reggaeton-tinged pop production, fits a Russian dance pop playlist, 100 BPM, D minor",["pop","эстрада","2000s","sultry","streetwise"]),
  E("ru-vintage","Винтаж","ru","Русские","Pop","электропоп / dance pop","2000s",["glamorous","camp"],128,"A minor","группа с театральным женским вокалом","2000s Russian electropop (pop), theatrical female vocals, Russian vocals, glamorous electropop production, fits a Russian dance pop playlist, 128 BPM, A minor",["pop","электропоп","2000s","glamorous","camp"]),
  E("ru-via-gra","ВИА Гра","ru","Русские","Pop","эстрада / женская группа","2000s",["sensual","glamorous"],110,"E minor","провокационное женское трио","2000s Russian female group pop (pop), sensual female trio, Russian/Ukrainian vocals, glamorous pop production, fits a Russian female group playlist, 110 BPM, E minor",["pop","эстрада","2000s","sensual","glamorous"]),
  E("ru-a-studio","А-Студио","ru","Русские","Pop","эстрада / джаз-поп","1990s",["smooth","sophisticated"],105,"D major","утончённое сопрано Полины Гриффис","1990s Russian jazz pop (pop), smooth sophisticated soprano, Russian/Kazakh vocals, jazz-influenced pop production, fits a Russian smooth pop playlist, 105 BPM, D major",["pop","эстрада","1990s","smooth","sophisticated"]),

  // — Шансон / chanson
  E("ru-shufutinsky","Михаил Шуфутинский","ru","Русские","Pop","русский шансон / эмигрант-поп","1990s",["nostalgic","velvety"],95,"E minor","бархатный баритон шансона","1990s Russian chanson (pop), velvety chanson baritone, Russian vocals, accordion, restaurant-pop arrangements, nostalgic mood, fits a Russian chanson playlist, 95 BPM, E minor",["pop","шансон","1990s","nostalgic","velvety"],true),
  E("ru-rozenbaum","Александр Розенбаум","ru","Русские","Folk","авторская песня / шансон","1980s",["gravelly","narrative"],90,"D minor","хриплый бардовский баритон","1980s Russian bard chanson (folk), gravelly narrative baritone, Russian vocals, twelve-string guitar, narrative songwriting, fits a Russian bard playlist, 90 BPM, D minor",["folk","шансон","1980s","gravelly","narrative"]),
  E("ru-krug","Михаил Круг","ru","Русские","Pop","русский шансон / блатняк","1990s",["streetwise","nostalgic"],100,"E minor","характерный шансонный баритон Круга","1990s Russian street chanson (pop), streetwise baritone, Russian vocals, accordion and guitar, blatnyak chanson production, fits a Russian shanson playlist, 100 BPM, E minor",["pop","шансон","1990s","streetwise","nostalgic"]),
  E("ru-mihailov","Стас Михайлов","ru","Русские","Pop","эстрада / шансон","2000s",["dramatic","sentimental"],90,"A minor","драматичный баритон Михайлова","2000s Russian pop chanson (pop), dramatic sentimental baritone, Russian vocals, orchestral chanson-pop, fits a Russian sentimental playlist, 90 BPM, A minor",["pop","эстрада","2000s","dramatic","sentimental"]),
  E("ru-uspenskaya","Любовь Успенская","ru","Русские","Pop","русский шансон / эмигрант-поп","1990s",["smoky","emigre"],95,"E minor","прокуренный женский шансонный голос","1990s Russian émigré chanson (pop), smoky chanson alto, Russian vocals, restaurant-pop, accordion, fits a Russian chanson playlist, 95 BPM, E minor",["pop","шансон","1990s","smoky","emigre"]),
  E("ru-veska","Игорь Николаев","ru","Русские","Pop","эстрада / композитор-исполнитель","1990s",["soft","romantic"],95,"D major","мягкий поп-баритон Николаева","1990s Russian estrada (pop), soft romantic baritone, Russian vocals, piano-led pop ballads, fits a Russian romantic estrada playlist, 95 BPM, D major",["pop","эстрада","1990s","soft","romantic"]),

  // — Русский рок
  E("ru-sektor-gaza","Сектор Газа","ru","Русские","Rock","русский панк / фолк-панк","1990s",["irreverent","raw"],150,"E minor","разудалый народно-панковый баритон Хоя","1990s Russian folk-punk (rock), raucous folk-punk baritone, Russian vocals, accordion-meets-punk-guitar, irreverent raw mood, fits a Russian punk playlist, 150 BPM, E minor",["rock","русский панк","1990s","irreverent","raw"],true),
  E("ru-korol-i-shut","Король и Шут","ru","Русские","Rock","хоррор-панк / фолк-рок","1990s",["theatrical","macabre"],145,"D minor","дуэт Горшок и Князь, театральный панк","1990s Russian horror-punk (rock), theatrical Gorshok and Knyaz duo, Russian vocals, folk-punk with horror lyrics, macabre theatrical mood, fits a Russian punk playlist, 145 BPM, D minor",["rock","хоррор-панк","1990s","theatrical","macabre"],true),
  E("ru-alisa","Алиса","ru","Русские","Rock","русский рок / хард-рок","1980s",["epic","prophetic"],128,"E minor","надрывный пророческий тенор Кинчева","1980s Russian rock (rock), prophetic anguished tenor, Russian vocals, hard-rock guitars, anthemic production, epic mood, fits a Russian rock classics playlist, 128 BPM, E minor",["rock","русский рок","1980s","epic","prophetic"]),
  E("ru-chizh","Чиж и Ко","ru","Русские","Rock","блюз-рок / русский рок","1990s",["smoky","blues"],110,"A minor","прокуренный блюзовый тенор Чижа","1990s Russian blues rock (rock), smoky blues tenor, Russian vocals, harmonica, electric guitar, blues mood, fits a Russian blues rock playlist, 110 BPM, A minor",["rock","блюз-рок","1990s","smoky","blues"]),
  E("ru-voskresenie","Воскресение","ru","Русские","Rock","советский рок","1980s",["philosophical","melodic"],100,"A minor","задушевный баритон Сапунова","1980s Soviet rock (rock), heartfelt baritone, Russian vocals, acoustic-driven Soviet rock, philosophical mood, fits a Soviet rock classics playlist, 100 BPM, A minor",["rock","советский рок","1980s","philosophical","melodic"]),
  E("ru-tequila-jazzz","Tequilajazzz","ru","Русские","Rock","альтернатива / пост-рок","1990s",["melancholic","artsy"],120,"E minor","задумчивый альтернативный баритон Михайлова","1990s Russian alt-rock (rock), pensive baritone, Russian vocals, alternative rock with post-rock textures, melancholic artsy mood, fits a Russian alt-rock playlist, 120 BPM, E minor",["rock","альтернатива","1990s","melancholic","artsy"]),
  E("ru-nochnye-snaiperi","Ночные Снайперы","ru","Русские","Rock","русский рок / женский рок","1990s",["poetic","tender"],115,"E minor","нежный женский рок-вокал","1990s Russian female rock (rock), tender female rock vocals, Russian vocals, acoustic-electric rock, poetic mood, fits a Russian women rock playlist, 115 BPM, E minor",["rock","русский рок","1990s","poetic","tender"]),
  E("ru-surganova","Сурганова и Оркестр","ru","Русские","Rock","авторская песня / рок-кабаре","2000s",["theatrical","romantic"],110,"E minor","эмоциональный контральто Сургановой","2000s Russian rock cabaret (rock), theatrical contralto, Russian vocals, chamber rock with violin, theatrical romantic mood, fits a Russian art rock playlist, 110 BPM, E minor",["rock","авторская песня","2000s","theatrical","romantic"]),
  E("ru-chicherina","Чичерина","ru","Русские","Rock","русский рок / поп-рок","2000s",["energetic","heartfelt"],128,"D major","энергичный женский вокал Чичериной","2000s Russian pop rock (rock), energetic female vocals, Russian vocals, guitar-driven pop-rock, heartfelt mood, fits a Russian women rock playlist, 128 BPM, D major",["rock","поп-рок","2000s","energetic","heartfelt"]),
  E("ru-naik-borzov","Найк Борзов","ru","Русские","Rock","инди-рок / альтернатива","1990s",["quirky","ironic"],120,"E minor","своеобразный тенор Борзова","1990s Russian indie rock (rock), quirky tenor, Russian vocals, indie-alternative production, ironic mood, fits a Russian indie rock playlist, 120 BPM, E minor",["rock","инди-рок","1990s","quirky","ironic"]),
  E("ru-mara","Мара","ru","Русские","Rock","русский рок / женский рок","2000s",["fiery","feminist"],128,"E minor","яростный женский рок-вокал","2000s Russian female rock (rock), fiery female rock vocals, Russian vocals, hard rock production, feminist mood, fits a Russian female rock playlist, 128 BPM, E minor",["rock","русский рок","2000s","fiery","feminist"]),
  E("ru-glaz-samoiloff","Глеб Самойлоff & The MATRIXX","ru","Русские","Rock","альтернатива / дарк-рок","2010s",["dark","poetic"],128,"D minor","театральный мрачный баритон","2010s Russian dark alt-rock (rock), theatrical dark baritone, Russian vocals, post-punk-tinged alt-rock, dark poetic mood, fits a Russian dark rock playlist, 128 BPM, D minor",["rock","альтернатива","2010s","dark","poetic"]),
  E("ru-bumboks","Бумбокс","ru","Русские","Pop","украинский фанк / поп","2000s",["funky","laid-back"],108,"D major","расслабленный фанковый вокал Хливнюка","2000s Ukrainian funk pop (pop), laid-back funky vocals, Ukrainian/Russian vocals, funk-pop production, fits a Ukrainian funk playlist, 108 BPM, D major",["pop","фанк","2000s","funky","laid-back"]),
  E("ru-vopli","Несчастный случай","ru","Русские","Rock","рок-кабаре / театральный рок","1990s",["witty","theatrical"],120,"D major","остроумный театральный баритон Кортнева","1990s Russian theatre rock (rock), witty theatrical baritone, Russian vocals, brass-led rock cabaret, witty mood, fits a Russian theatre rock playlist, 120 BPM, D major",["rock","театральный рок","1990s","witty","theatrical"]),
  E("ru-sukachev","Гарик Сукачёв","ru","Русские","Rock","русский рок / городской романс","1990s",["raucous","streetwise"],128,"E minor","разудалый хриплый баритон","1990s Russian street rock (rock), raucous streetwise baritone, Russian vocals, accordion-meets-rock, fits a Russian street rock playlist, 128 BPM, E minor",["rock","городской романс","1990s","raucous","streetwise"]),
  E("ru-zhanna-aguzarova","Жанна Агузарова","ru","Русские","Rock","ретро-рок / эксцентрик-поп","1980s",["eccentric","theatrical"],120,"E minor","эксцентричное театральное сопрано Агузаровой","1980s Russian eccentric pop (rock), eccentric theatrical soprano, Russian vocals, retro-pop-rock production, theatrical mood, fits a Russian retro playlist, 120 BPM, E minor",["rock","ретро-рок","1980s","eccentric","theatrical"],true),
  E("ru-linda","Линда","ru","Русские","Pop","электропоп / world","1990s",["mystical","ethnic"],110,"D minor","мистическое контральто Линды","1990s Russian mystic electropop (pop), mystical contralto, Russian vocals, world-music meets electronica, mystical ethnic mood, fits a Russian art pop playlist, 110 BPM, D minor",["pop","электропоп","1990s","mystical","ethnic"]),
  E("ru-bgu","Гарик Сукачев и Бригада С","ru","Русские","Rock","советский рок / рок-н-ролл","1980s",["rock'n'roll","party"],145,"A major","задорный рок-н-ролльный вокал","1980s Soviet rock'n'roll (rock), rowdy rock'n'roll vocals, Russian vocals, swing-influenced rock production, party mood, fits a Soviet rock playlist, 145 BPM, A major",["rock","рок-н-ролл","1980s","rock'n'roll","party"]),
  E("ru-cherny-kofe","Чёрный Кофе","ru","Русские","Metal","русский хэви-метал","1980s",["heavy","Soviet"],135,"E minor","характерный метал-тенор Варшавского","1980s Soviet heavy metal (metal), characterful metal tenor, Russian vocals, NWOBHM-influenced metal, Soviet mood, fits a Soviet metal playlist, 135 BPM, E minor",["metal","русский метал","1980s","heavy","Soviet"]),
  E("ru-25-17","25/17","ru","Русские","Hip-hop","русский рэп / рэп-рок","2010s",["literary","patriotic"],95,"D minor","литературный рэп-баритон","2010s Russian rap rock (hip-hop), literary baritone, Russian vocals, rap-rock production with live instrumentation, patriotic mood, fits a Russian literary rap playlist, 95 BPM, D minor",["hip-hop","рэп-рок","2010s","literary","patriotic"]),

  // — Современный рэп / новая волна
  E("ru-skriptonit","Скриптонит","ru","Русские","Hip-hop","клауд-рэп / трэп","2010s",["atmospheric","drawled"],90,"D minor","ленивый протяжный казахстанский баритон","2010s cloud rap trap (hip-hop), drawled lazy baritone, Russian vocals, atmospheric trap production, fits a Russian cloud rap playlist, 90 BPM, D minor",["hip-hop","клауд-рэп","2010s","atmospheric","drawled"],true),
  E("ru-timati","Тимати","ru","Русские","Hip-hop","поп-рэп / luxury rap","2000s",["luxurious","posturing"],95,"F minor","glossy luxury-rap baritone","2000s Russian pop rap (hip-hop), glossy luxury baritone, Russian vocals, polished pop-rap production, fits a Russian mainstream rap playlist, 95 BPM, F minor",["hip-hop","поп-рэп","2000s","luxurious","posturing"]),
  E("ru-guf","ГУФ","ru","Русские","Hip-hop","русский хип-хоп","2000s",["streetwise","monotone"],90,"E minor","характерный монотонный рэп ГУФа","2000s Russian street hip-hop (hip-hop), streetwise monotone rapper, Russian vocals, boom-bap production, fits a Russian classic rap playlist, 90 BPM, E minor",["hip-hop","русский хип-хоп","2000s","streetwise","monotone"],true),
  E("ru-kaspiysky-gruz","Каспийский Груз","ru","Русские","Hip-hop","южный рэп / уличный рэп","2010s",["streetwise","southern"],95,"E minor","южнорусский уличный рэп","2010s Russian southern hip-hop (hip-hop), streetwise southern rappers, Russian vocals, southern-flavored beats, fits a Russian southern rap playlist, 95 BPM, E minor",["hip-hop","южный рэп","2010s","streetwise","southern"]),
  E("ru-ak-47","AK-47","ru","Русские","Hip-hop","сибирский рэп / стрит-рэп","2000s",["streetwise","Novosibirsk"],95,"D minor","сибирский уличный рэп","2000s Siberian hip-hop (hip-hop), Siberian street rappers, Russian vocals, hard street beats, fits a Russian street rap playlist, 95 BPM, D minor",["hip-hop","сибирский рэп","2000s","streetwise","Novosibirsk"]),
  E("ru-jony","JONY","ru","Русские","Pop","поп-рэп / меланхоличный","2010s",["melancholic","silky"],95,"C minor","шёлковый меланхоличный поп-тенор","2010s Russian melancholic pop rap (pop), silky melancholic tenor, Russian vocals, atmospheric pop production, fits a Russian sad pop playlist, 95 BPM, C minor",["pop","поп-рэп","2010s","melancholic","silky"]),
  E("ru-niletto","Niletto","ru","Русские","Pop","поп / dance-pop","2010s",["upbeat","catchy"],120,"G major","задорный поп-тенор","2010s Russian dance pop (pop), upbeat catchy tenor, Russian vocals, modern dance-pop production, fits a Russian radio pop playlist, 120 BPM, G major",["pop","dance pop","2010s","upbeat","catchy"]),
  E("ru-the-hatters","The Hatters","ru","Русские","Rock","фолк-рок / балканский поп","2010s",["festive","gypsy"],135,"D minor","театральный балканско-фолковый коллектив","2010s Russian folk rock (rock), theatrical Balkan-folk collective, Russian vocals, brass band, accordion, festive gypsy mood, fits a Russian fun rock playlist, 135 BPM, D minor",["rock","фолк-рок","2010s","festive","gypsy"]),
  E("ru-pyrokinesis","Pyrokinesis","ru","Русские","Hip-hop","клауд-рэп / альт-рэп","2010s",["dark","cinematic"],95,"F minor","меланхоличный альт-рэп тенор","2010s Russian alt-rap cloud (hip-hop), melancholic alt-rap tenor, Russian vocals, cinematic atmospheric beats, fits a Russian alt rap playlist, 95 BPM, F minor",["hip-hop","клауд-рэп","2010s","dark","cinematic"]),
  E("ru-instasamka","INSTASAMKA","ru","Русские","Hip-hop","поп-рэп / Гипер-поп","2020s",["provocative","viral"],130,"F minor","провокационное сопрано","2020s Russian hyperpop rap (hip-hop), provocative soprano, Russian vocals, hyperpop-trap production, viral mood, fits a Russian viral pop rap playlist, 130 BPM, F minor",["hip-hop","поп-рэп","2020s","provocative","viral"]),
  E("ru-mia-boyka","MIA BOYKA","ru","Русские","Pop","поп / dance pop","2020s",["bratty","catchy"],128,"A minor","задорное юное поп-сопрано","2020s Russian dance pop (pop), bratty catchy soprano, Russian vocals, hyper-pop influenced dance production, fits a Russian Gen-Z pop playlist, 128 BPM, A minor",["pop","dance pop","2020s","bratty","catchy"]),
  E("ru-manizha","Manizha","ru","Русские","Pop","альт-поп / world","2010s",["empowering","ethnic"],115,"D minor","эмоциональное world-pop сопрано Манижы","2010s Russian alt pop (pop), empowering ethnic-inflected soprano, Russian/Tajik vocals, world-music production, fits a Russian alt pop playlist, 115 BPM, D minor",["pop","альт-поп","2010s","empowering","ethnic"]),
  E("ru-zveri","Звери","ru","Русские","Rock","поп-рок / инди","2000s",["upbeat","youthful"],128,"G major","задорный молодёжный рок-тенор Билыка","2000s Russian pop rock (rock), upbeat youthful tenor, Russian vocals, indie-influenced pop rock, fits a Russian pop rock playlist, 128 BPM, G major",["rock","поп-рок","2000s","upbeat","youthful"]),
  E("ru-tokio","Токио","ru","Русские","Rock","поп-рок / альтернатива","2000s",["melodic","emotional"],120,"E minor","эмоциональный поп-рок вокал","2000s Russian pop rock (rock), emotional vocals, Russian vocals, alternative-leaning pop rock, fits a Russian alt pop rock playlist, 120 BPM, E minor",["rock","поп-рок","2000s","melodic","emotional"]),
  E("ru-pelageya","Пелагея","ru","Русские","Folk","фолк-рок / этно","2000s",["powerful","ethnic"],110,"D minor","сильное этно-фолковое сопрано","2000s Russian folk rock (folk), powerful ethnic soprano, Russian vocals, folk instruments meets rock band, fits a Russian folk rock playlist, 110 BPM, D minor",["folk","фолк-рок","2000s","powerful","ethnic"]),
  E("ru-melnitsa","Мельница","ru","Русские","Folk","фолк-рок / кельтский","2000s",["mystical","Celtic-tinged"],115,"D minor","мечтательное фолк-сопрано Хелависы","2000s Russian Celtic folk rock (folk), dreamy folk soprano, Russian vocals, Celtic-influenced folk-rock production, mystical mood, fits a Russian folk rock playlist, 115 BPM, D minor",["folk","фолк-рок","2000s","mystical","Celtic-tinged"]),
  E("ru-mgzavrebi","Mgzavrebi","ru","Русские","Folk","грузинский инди-фолк","2010s",["warm","Georgian"],100,"D major","грузинский фолк-баритон Гиги Дедаламазишвили","2010s Georgian indie folk (folk), warm Georgian baritone, Georgian vocals, acoustic guitar, Georgian polyphony, warm mood, fits a post-Soviet indie folk playlist, 100 BPM, D major",["folk","грузинский фолк","2010s","warm","Georgian"]),
  E("ru-leps-2","Григорий Лепс ft. Тимати","ru","Русские","Pop","эстрада / поп-рэп коллаб","2010s",["dramatic","crossover"],100,"E minor","хриплый Лепс + рэп Тимати","2010s Russian crossover pop (pop), Leps gravelly + Timati rap, Russian vocals, dramatic pop-rap production, fits a Russian crossover playlist, 100 BPM, E minor",["pop","эстрада","2010s","dramatic","crossover"]),
  E("ru-anacondaz","Anacondaz","ru","Русские","Hip-hop","альт-рэп / рэп-рок","2010s",["ironic","punk"],128,"D minor","ироничный рэп-панк коллектив","2010s Russian alt-rap rock (hip-hop), ironic rap-punk collective, Russian vocals, punk-rock instrumentation with rap delivery, fits a Russian alt rap playlist, 128 BPM, D minor",["hip-hop","рэп-рок","2010s","ironic","punk"]),
  E("ru-slot","Слот","ru","Русские","Metal","альтернативный метал / nu-metal","2000s",["intense","melodic"],135,"E minor","дуэт мужского и женского вокала","2000s Russian alt-metal (metal), male/female dual vocals, Russian vocals, nu-metal production, intense mood, fits a Russian nu-metal playlist, 135 BPM, E minor",["metal","альт-метал","2000s","intense","melodic"]),
  E("ru-kishlak","Кишлак","ru","Русские","Hip-hop","клауд-рэп / меланхоличный рэп","2010s",["dark","atmospheric"],85,"C minor","меланхоличный клауд-рэп баритон","2010s Russian melancholic cloud rap (hip-hop), dark atmospheric baritone, Russian vocals, lo-fi cloud production, fits a Russian sad rap playlist, 85 BPM, C minor",["hip-hop","клауд-рэп","2010s","dark","atmospheric"]),
  E("ru-quest-pistols","Quest Pistols","ru","Русские","Pop","украинский dance-pop","2000s",["fun","danceable"],128,"E minor","украинское дэнс-поп трио","2000s Ukrainian dance pop (pop), fun dance-pop trio, Russian/Ukrainian vocals, modern dance production, fits a post-Soviet dance pop playlist, 128 BPM, E minor",["pop","украинский поп","2000s","fun","danceable"]),
  E("ru-dolphin","Дельфин","ru","Русские","Hip-hop","альт-рэп / электронный","1990s",["introspective","experimental"],100,"D minor","задумчивый альт-рэп тенор","1990s Russian alt rap electronic (hip-hop), introspective tenor, Russian vocals, electronic-rap production, experimental mood, fits a Russian alt rap playlist, 100 BPM, D minor",["hip-hop","альт-рэп","1990s","introspective","experimental"],true),
  E("ru-spasibo","Спасибо","ru","Русские","Rock","инди-рок / пост-панк","2010s",["dreamy","cold"],128,"E minor","задумчивый инди баритон","2010s Russian indie post-punk (rock), dreamy detached baritone, Russian vocals, jangly indie guitar, cold reverb, fits a Russian indie rock playlist, 128 BPM, E minor",["rock","инди-рок","2010s","dreamy","cold"]),
  E("ru-jane-air","Jane Air","ru","Русские","Metal","пост-хардкор / эмо","2000s",["intense","emo"],145,"E minor","комбинированный чистый/скриминговый вокал","2000s Russian post-hardcore emo (metal), clean/screamed vocals combo, Russian vocals, emo-influenced post-hardcore, fits a Russian emo playlist, 145 BPM, E minor",["metal","пост-хардкор","2000s","intense","emo"]),
  E("ru-amatory","Amatory","ru","Русские","Metal","металкор / пост-хардкор","2000s",["aggressive","melodic"],150,"D minor","скрим + чистый вокал","2000s Russian metalcore (metal), screamed and clean dual vocals, Russian vocals, metalcore breakdowns, fits a Russian metalcore playlist, 150 BPM, D minor",["metal","металкор","2000s","aggressive","melodic"]),
  E("ru-tokio-hotel-ru","Звери (live)","ru","Русские","Rock","поп-рок / live","2000s",["energetic","raw"],128,"G major","живой поп-рок энергия","2000s Russian live pop rock (rock), live energy raw vocals, Russian vocals, raw live production, fits a Russian live rock playlist, 128 BPM, G major",["rock","поп-рок","2000s","energetic","raw"]),
  E("ru-megapolis","Мегаполис","ru","Русские","Rock","инди-поп / арт-поп","1980s",["sophisticated","ironic"],110,"D major","утончённый арт-поп баритон","1980s Soviet art pop (rock), sophisticated baritone, Russian vocals, intelligent art-pop production, ironic mood, fits a Soviet art pop playlist, 110 BPM, D major",["rock","инди-поп","1980s","sophisticated","ironic"]),

  // ══════════════════════════════════════════════════════════════════════════
  // FRENCH  (fr: 26 → 60)
  // ══════════════════════════════════════════════════════════════════════════

  // — Classic chanson / variété
  E("fr-johnny-hallyday","Johnny Hallyday","fr","Французские","Rock","French rock'n'roll / variété","1960s",["iconic","raw"],128,"E major","raspy French rock'n'roll baritone","1960s French rock'n'roll (rock), raspy baritone, French vocals, Elvis-influenced rock production with French strings, iconic mood, fits a French rock classics playlist, 128 BPM, E major",["rock","French rock","1960s","iconic","raw"],true),
  E("fr-france-gall","France Gall","fr","Французские","Pop","yé-yé / chanson","1960s",["sunny","yé-yé"],120,"D major","bright yé-yé soprano","1960s yé-yé (pop), bright soprano, French vocals, sunny 60s pop production with brass and strings, yé-yé mood, fits a 60s French pop playlist, 120 BPM, D major",["pop","yé-yé","1960s","sunny","yé-yé"]),
  E("fr-francoise-hardy","Françoise Hardy","fr","Французские","Pop","yé-yé / chanson","1960s",["cool","melancholic"],100,"E minor","cool detached French alto","1960s French chanson (pop), cool detached alto, French vocals, fingerpicked guitar, melancholic production, fits a 60s French chic playlist, 100 BPM, E minor",["pop","yé-yé","1960s","cool","melancholic"],true),
  E("fr-sylvie-vartan","Sylvie Vartan","fr","Французские","Pop","yé-yé / variété","1960s",["effervescent","Parisian"],128,"G major","effervescent Parisian soprano","1960s yé-yé (pop), effervescent soprano, French vocals, sunny variété production, fits a 60s French pop playlist, 128 BPM, G major",["pop","yé-yé","1960s","effervescent","Parisian"]),
  E("fr-dalida","Dalida","fr","Французские","Pop","French/Mediterranean variété","1970s",["dramatic","Mediterranean"],110,"D minor","Italian-Egyptian-French diva mezzo","1970s Mediterranean variété (pop), dramatic Mediterranean mezzo, French/Italian/Arabic vocals, lush variété arrangements, fits a French diva playlist, 110 BPM, D minor",["pop","variété","1970s","dramatic","Mediterranean"],true),
  E("fr-michel-sardou","Michel Sardou","fr","Французские","Pop","French variété / chanson","1970s",["dramatic","conservative"],100,"E minor","powerful French variété baritone","1970s French variété (pop), powerful baritone, French vocals, orchestral variété, dramatic mood, fits a French variété classics playlist, 100 BPM, E minor",["pop","variété","1970s","dramatic","conservative"]),
  E("fr-jean-jacques-goldman","Jean-Jacques Goldman","fr","Французские","Pop","French pop rock / variété","1980s",["sincere","melodic"],115,"D major","sincere French pop-rock tenor","1980s French pop rock (pop), sincere tenor, French vocals, polished pop-rock production, melodic mood, fits a French pop rock playlist, 115 BPM, D major",["pop","French pop rock","1980s","sincere","melodic"],true),
  E("fr-patrick-bruel","Patrick Bruel","fr","Французские","Pop","French pop / variété","1980s",["romantic","heartthrob"],95,"E major","romantic heartthrob French tenor","1980s French pop (pop), romantic heartthrob tenor, French vocals, polished variété production, fits a French pop playlist, 95 BPM, E major",["pop","variété","1980s","romantic","heartthrob"]),
  E("fr-florent-pagny","Florent Pagny","fr","Французские","Pop","French variété / opera-pop","1990s",["powerful","operatic"],90,"D minor","powerful operatic French baritone","1990s French operatic pop (pop), powerful baritone, French vocals, classical-influenced variété, fits a French operatic pop playlist, 90 BPM, D minor",["pop","variété","1990s","powerful","operatic"]),
  E("fr-garou","Garou","fr","Французские","Pop","French Canadian rock / variété","2000s",["husky","theatrical"],100,"E minor","husky Quebec baritone","2000s French Canadian variété (pop), husky theatrical baritone, French vocals, rock-influenced variété production, fits a French Canadian pop playlist, 100 BPM, E minor",["pop","variété","2000s","husky","theatrical"]),
  E("fr-calogero","Calogero","fr","Французские","Pop","French pop rock","2000s",["heartfelt","melodic"],110,"C major","heartfelt French pop-rock tenor","2000s French pop rock (pop), heartfelt tenor, French vocals, polished pop-rock production, melodic mood, fits a French pop rock playlist, 110 BPM, C major",["pop","French pop rock","2000s","heartfelt","melodic"]),
  E("fr-yves-montand","Yves Montand","fr","Французские","Pop","French chanson / classique","1950s",["intimate","Parisian"],88,"E minor","intimate Italian-French baritone","1950s French chanson (pop), intimate baritone, French vocals, classic chanson with accordion, fits a French classic chanson playlist, 88 BPM, E minor",["pop","chanson","1950s","intimate","Parisian"],true),
  E("fr-charles-trenet","Charles Trenet","fr","Французские","Pop","French chanson / swing","1940s",["whimsical","poetic"],120,"C major","whimsical Trenet tenor","1940s French chanson swing (pop), whimsical poetic tenor, French vocals, swing-era arrangements, fits a French chanson classics playlist, 120 BPM, C major",["pop","chanson","1940s","whimsical","poetic"],true),
  E("fr-henri-salvador","Henri Salvador","fr","Французские","Jazz","French jazz / chanson","1950s",["warm","bossa"],95,"G major","warm sunny French-Caribbean baritone","1950s French jazz chanson (jazz), warm Caribbean baritone, French vocals, bossa-jazz arrangements, fits a French jazz playlist, 95 BPM, G major",["jazz","French jazz","1950s","warm","bossa"]),
  E("fr-michel-polnareff","Michel Polnareff","fr","Французские","Pop","French pop / orchestral pop","1960s",["theatrical","baroque"],110,"E minor","theatrical Polnareff falsetto","1960s French baroque pop (pop), theatrical falsetto, French vocals, baroque pop arrangements, fits a French baroque pop playlist, 110 BPM, E minor",["pop","French pop","1960s","theatrical","baroque"]),
  E("fr-alain-souchon","Alain Souchon","fr","Французские","Pop","French chanson moderne","1980s",["bittersweet","poetic"],105,"D major","Souchon gentle reflective tenor","1980s French chanson moderne (pop), bittersweet reflective tenor, French vocals, acoustic chanson production, fits a French songwriter playlist, 105 BPM, D major",["pop","chanson moderne","1980s","bittersweet","poetic"]),
  E("fr-laurent-voulzy","Laurent Voulzy","fr","Французские","Pop","French pop / Caribbean influenced","1980s",["sunny","melodic"],115,"D major","sunny melodic Caribbean-French tenor","1980s French Caribbean pop (pop), sunny melodic tenor, French vocals, Caribbean-influenced pop, fits a French summer pop playlist, 115 BPM, D major",["pop","French pop","1980s","sunny","melodic"]),
  E("fr-eddy-mitchell","Eddy Mitchell","fr","Французские","Rock","French rock'n'roll / country","1970s",["nostalgic","Americana"],120,"E major","French country-rock baritone","1970s French country rock (rock), nostalgic Americana baritone, French vocals, country-rock arrangements, fits a French rock'n'roll playlist, 120 BPM, E major",["rock","French rock","1970s","nostalgic","Americana"]),
  E("fr-renaud-2","Carla Bruni","fr","Французские","Pop","French folk / chanson moderne","2000s",["whispered","intimate"],88,"E major","whispered intimate Italian-French alto","2000s French folk chanson (pop), whispered intimate alto, French/Italian vocals, acoustic guitar production, fits a French intimate playlist, 88 BPM, E major",["pop","chanson","2000s","whispered","intimate"]),
  E("fr-yannick-noah","Yannick Noah","fr","Французские","Pop","French world pop / reggae","2000s",["warm","Afro-Caribbean"],115,"D major","warm African-French baritone","2000s French world pop (pop), warm Afro-Caribbean baritone, French vocals, reggae-influenced production, fits a French world playlist, 115 BPM, D major",["pop","world pop","2000s","warm","Afro-Caribbean"]),

  // — Modern French pop / rap / electronic
  E("fr-angele","Angèle","fr","Французские","Pop","Belgian French indie pop","2010s",["clever","intimate"],100,"C major","clever Belgian French soprano","2010s French indie pop (pop), clever intimate soprano, French vocals, minimalist indie-pop production, fits a French indie pop playlist, 100 BPM, C major",["pop","indie pop","2010s","clever","intimate"]),
  E("fr-yseult","Yseult","fr","Французские","Pop","French art pop / soul","2010s",["powerful","raw"],90,"D minor","powerful raw soul-tinged contralto","2010s French art pop soul (pop), powerful raw contralto, French vocals, sparse piano-led art-pop production, fits a French art pop playlist, 90 BPM, D minor",["pop","art pop","2010s","powerful","raw"]),
  E("fr-louane-2","Louane","fr","Французские","Pop","French pop","2010s",["youthful","heartfelt"],100,"E major","youthful heartfelt French soprano","2010s French pop (pop), youthful heartfelt soprano, French vocals, polished pop production, fits a French pop playlist, 100 BPM, E major",["pop","French pop","2010s","youthful","heartfelt"]),
  E("fr-maitre-gims","Maître Gims","fr","Французские","Hip-hop","French pop rap / Afro-French","2010s",["melodic","catchy"],100,"F minor","melodic French-Congolese pop-rap baritone","2010s French pop rap (hip-hop), melodic baritone, French vocals, Afro-French pop production, fits a French pop rap playlist, 100 BPM, F minor",["hip-hop","French rap","2010s","melodic","catchy"]),
  E("fr-soprano","Soprano","fr","Французские","Hip-hop","French rap / pop rap","2000s",["uplifting","Marseillais"],95,"D minor","Marseille rap-pop tenor","2000s French pop rap (hip-hop), uplifting Marseillais tenor, French vocals, melodic pop-rap production, fits a French rap playlist, 95 BPM, D minor",["hip-hop","French rap","2000s","uplifting","Marseillais"]),
  E("fr-booba","Booba","fr","Французские","Hip-hop","French rap / trap","2000s",["dark","aggressive"],90,"F minor","dark menacing French rapper baritone","2000s French trap rap (hip-hop), dark aggressive baritone, French vocals, hard street trap production, fits a French rap playlist, 90 BPM, F minor",["hip-hop","French rap","2000s","dark","aggressive"]),
  E("fr-damso","Damso","fr","Французские","Hip-hop","French rap / Belgian rap","2010s",["raw","cinematic"],90,"D minor","raw Belgian-Congolese rapper","2010s French rap (hip-hop), raw cinematic rapper, French vocals, dark atmospheric trap production, fits a French rap playlist, 90 BPM, D minor",["hip-hop","French rap","2010s","raw","cinematic"]),
  E("fr-sch","SCH","fr","Французские","Hip-hop","French rap / Marseille trap","2010s",["mafioso","Marseille"],90,"F minor","Marseille trap rapper baritone","2010s French Marseille trap (hip-hop), mafioso baritone, French vocals, dark Marseille trap production, fits a French rap playlist, 90 BPM, F minor",["hip-hop","French rap","2010s","mafioso","Marseille"]),
  E("fr-ninho","Ninho","fr","Французские","Hip-hop","French rap / drill / trap","2010s",["melodic","prolific"],90,"D minor","melodic French rapper-singer","2010s French rap (hip-hop), melodic auto-tuned rapper, French vocals, drill-trap production, fits a French rap playlist, 90 BPM, D minor",["hip-hop","French rap","2010s","melodic","prolific"]),
  E("fr-stromae-3","Stromae","fr","Французские","Pop","Belgian French electro / world pop","2010s",["danceable","poignant"],112,"D minor","Stromae poignant Belgian tenor","2010s Belgian French electro pop (pop), poignant tenor, French vocals, world-influenced electro-pop production, fits a French alt pop playlist, 112 BPM, D minor",["pop","electro pop","2010s","danceable","poignant"]),
  E("fr-phoenix","Phoenix","fr","Французские","Rock","French indie pop / dance rock","2000s",["polished","sunny"],128,"D major","Thomas Mars polished indie tenor","2000s French indie pop (rock), polished tenor, French/English vocals, dance-rock production, sunny mood, fits a French indie rock playlist, 128 BPM, D major",["rock","indie pop","2000s","polished","sunny"]),
  E("fr-justice","Justice","fr","Французские","Electronic","French electronic / electro house","2000s",["aggressive","funky"],128,"F minor","Justice mostly-instrumental electro duo","2000s French electro house (electronic), instrumental with guest vocals, French/English vocals, aggressive electro-house production, fits a French dance playlist, 128 BPM, F minor",["electronic","electro house","2000s","aggressive","funky"]),
  E("fr-cassius","Cassius","fr","Французские","Electronic","French house","1990s",["funky","filtered"],128,"A minor","Cassius mostly-instrumental French house","1990s French house (electronic), instrumental with chopped vocals, French/English vocals, filter-house production, fits a French house playlist, 128 BPM, A minor",["electronic","French house","1990s","funky","filtered"]),
  E("fr-m83","M83","fr","Французские","Electronic","dream pop / electronic","2000s",["cinematic","nostalgic"],100,"D major","Anthony Gonzalez dreamy whispered tenor","2000s French dream pop (electronic), dreamy whispered tenor, French/English vocals, cinematic synth production, nostalgic mood, fits a French dream pop playlist, 100 BPM, D major",["electronic","dream pop","2000s","cinematic","nostalgic"],true),
  E("fr-sebastien-tellier","Sébastien Tellier","fr","Французские","Electronic","French electronic / cosmic pop","2000s",["cosmic","sensual"],110,"C major","Sébastien Tellier cosmic falsetto","2000s French cosmic pop (electronic), cosmic falsetto, French/English vocals, lush vintage-synth arrangements, fits a French alt electronic playlist, 110 BPM, C major",["electronic","cosmic pop","2000s","cosmic","sensual"]),
  E("fr-bigflo-oli","Bigflo & Oli","fr","Французские","Hip-hop","French pop rap / Toulouse","2010s",["warm","brotherly"],100,"D major","Bigflo & Oli brotherly rap duo","2010s French pop rap (hip-hop), warm brotherly duo, French vocals, sunny melodic pop-rap production, fits a French rap playlist, 100 BPM, D major",["hip-hop","French rap","2010s","warm","brotherly"]),

  // ══════════════════════════════════════════════════════════════════════════
  // ITALIAN  (it: 25 → 60)
  // ══════════════════════════════════════════════════════════════════════════

  // — Classic Italian opera / canzone
  E("it-luciano-pavarotti","Luciano Pavarotti","it","Итальянские","Classical","Italian opera","1980s",["majestic","legendary"],80,"D major","king of high Cs operatic tenor","1980s Italian opera (classical), legendary majestic tenor, Italian vocals, full orchestral accompaniment, operatic high Cs, fits an opera classics playlist, 80 BPM, D major",["classical","Italian opera","1980s","majestic","legendary"],true),
  E("it-domenico-modugno","Domenico Modugno","it","Итальянские","Pop","classic Italian canzone","1950s",["soaring","iconic"],110,"F major","Modugno classic Italian tenor","1950s classic canzone (pop), soaring iconic tenor, Italian vocals, orchestral 50s arrangements, fits an Italian classics playlist, 110 BPM, F major",["pop","canzone","1950s","soaring","iconic"],true),
  E("it-riccardo-cocciante","Riccardo Cocciante","it","Итальянские","Pop","Italian pop / musical","1970s",["passionate","theatrical"],100,"D minor","passionate Italian theatrical tenor","1970s Italian pop musical (pop), passionate theatrical tenor, Italian/French vocals, orchestral pop production, fits an Italian pop classics playlist, 100 BPM, D minor",["pop","Italian pop","1970s","passionate","theatrical"]),
  E("it-claudio-baglioni","Claudio Baglioni","it","Итальянские","Pop","Italian cantautore","1970s",["heartfelt","melodic"],95,"E major","Baglioni heartfelt Italian tenor","1970s Italian cantautore (pop), heartfelt melodic tenor, Italian vocals, lush pop ballad arrangements, fits an Italian classics playlist, 95 BPM, E major",["pop","cantautore","1970s","heartfelt","melodic"]),
  E("it-antonello-venditti","Antonello Venditti","it","Итальянские","Pop","Italian cantautore / Roman","1970s",["Roman","poetic"],100,"D major","Roman storyteller baritone","1970s Italian cantautore (pop), Roman storyteller baritone, Italian vocals, piano-led cantautore production, poetic mood, fits an Italian songwriter playlist, 100 BPM, D major",["pop","cantautore","1970s","Roman","poetic"]),
  E("it-renato-zero","Renato Zero","it","Итальянские","Pop","Italian theatrical pop","1970s",["theatrical","camp"],115,"E minor","Renato Zero theatrical Italian tenor","1970s Italian theatrical pop (pop), theatrical camp tenor, Italian vocals, glam-influenced pop production, fits an Italian theatrical pop playlist, 115 BPM, E minor",["pop","theatrical pop","1970s","theatrical","camp"]),
  E("it-massimo-ranieri","Massimo Ranieri","it","Итальянские","Pop","Italian classic pop / Neapolitan","1970s",["powerful","Neapolitan"],95,"E minor","powerful Neapolitan tenor","1970s Italian classic pop (pop), powerful Neapolitan tenor, Italian/Neapolitan vocals, orchestral classic-pop arrangements, fits an Italian classics playlist, 95 BPM, E minor",["pop","Neapolitan","1970s","powerful","Neapolitan"]),
  E("it-toto-cutugno","Toto Cutugno","it","Итальянские","Pop","Italian variety","1980s",["sentimental","Mediterranean"],100,"G major","Toto Cutugno sentimental tenor","1980s Italian variety (pop), sentimental Mediterranean tenor, Italian vocals, orchestral pop production, fits an Italian classics playlist, 100 BPM, G major",["pop","Italian variety","1980s","sentimental","Mediterranean"],true),
  E("it-gianni-morandi","Gianni Morandi","it","Итальянские","Pop","Italian pop / beat","1960s",["sunny","optimistic"],128,"D major","Morandi sunny Italian tenor","1960s Italian beat pop (pop), sunny optimistic tenor, Italian vocals, 60s beat-pop production, fits an Italian 60s playlist, 128 BPM, D major",["pop","Italian pop","1960s","sunny","optimistic"]),
  E("it-fabrizio-de-andre","Fabrizio De André","it","Итальянские","Folk","Italian cantautore / folk","1970s",["poetic","literary"],90,"D minor","De André literary baritone","1970s Italian folk cantautore (folk), poetic literary baritone, Italian vocals, acoustic guitar, folk arrangements, fits an Italian songwriter playlist, 90 BPM, D minor",["folk","cantautore","1970s","poetic","literary"],true),
  E("it-paolo-conte","Paolo Conte","it","Итальянские","Jazz","Italian jazz / cantautore","1980s",["smoky","cinematic"],95,"E minor","Paolo Conte smoky jazz baritone","1980s Italian jazz cantautore (jazz), smoky cinematic baritone, Italian vocals, jazzy piano-led arrangements, fits an Italian jazz playlist, 95 BPM, E minor",["jazz","cantautore","1980s","smoky","cinematic"],true),
  E("it-loredana-berte","Loredana Bertè","it","Итальянские","Rock","Italian rock / pop rock","1980s",["raspy","rebellious"],128,"E minor","Loredana Bertè raspy Italian alto","1980s Italian pop rock (rock), raspy rebellious alto, Italian vocals, glam-rock-influenced production, fits an Italian rock divas playlist, 128 BPM, E minor",["rock","Italian rock","1980s","raspy","rebellious"]),
  E("it-mia-martini","Mia Martini","it","Итальянские","Pop","Italian classic pop","1970s",["wounded","powerful"],95,"D minor","Mia Martini wounded powerful Italian mezzo","1970s Italian classic pop (pop), wounded powerful mezzo, Italian vocals, orchestral pop production, fits an Italian classics playlist, 95 BPM, D minor",["pop","Italian pop","1970s","wounded","powerful"],true),
  E("it-patty-pravo","Patty Pravo","it","Итальянские","Pop","Italian pop / experimental","1960s",["chameleonic","cool"],110,"E minor","Patty Pravo chameleonic Italian mezzo","1960s Italian pop (pop), chameleonic cool mezzo, Italian vocals, varied pop production from 60s yé-yé to experimental, fits an Italian pop classics playlist, 110 BPM, E minor",["pop","Italian pop","1960s","chameleonic","cool"]),

  // — Italian rock
  E("it-litfiba","Litfiba","it","Итальянские","Rock","Italian rock / post-punk","1980s",["dark","Mediterranean"],128,"E minor","Piero Pelù gravelly Italian rock baritone","1980s Italian rock post-punk (rock), gravelly dark baritone, Italian vocals, Mediterranean-influenced rock production, fits an Italian rock playlist, 128 BPM, E minor",["rock","Italian rock","1980s","dark","Mediterranean"],true),
  E("it-ligabue","Ligabue","it","Итальянские","Rock","Italian rock / heartland","1990s",["working-class","heartland"],128,"D major","Ligabue Emilian heartland rock baritone","1990s Italian heartland rock (rock), working-class baritone, Italian vocals, anthemic rock production, fits an Italian rock playlist, 128 BPM, D major",["rock","Italian rock","1990s","working-class","heartland"]),
  E("it-negrita","Negrita","it","Итальянские","Rock","Italian rock / blues rock","1990s",["raucous","Italian"],130,"E minor","Negrita raucous Italian rock baritone","1990s Italian blues rock (rock), raucous baritone, Italian vocals, blues-influenced rock production, fits an Italian rock playlist, 130 BPM, E minor",["rock","Italian rock","1990s","raucous","Italian"]),
  E("it-afterhours","Afterhours","it","Итальянские","Rock","Italian indie rock / alt","1990s",["dark","artsy"],120,"D minor","Manuel Agnelli dark Italian alt baritone","1990s Italian alt rock (rock), dark artsy baritone, Italian vocals, alternative rock production, fits an Italian indie playlist, 120 BPM, D minor",["rock","Italian alt rock","1990s","dark","artsy"]),
  E("it-verdena","Verdena","it","Итальянские","Rock","Italian alt rock / grunge","2000s",["heavy","psychedelic"],130,"E minor","Alberto Ferrari heavy Italian alt voice","2000s Italian alt rock (rock), heavy psychedelic vocals, Italian vocals, grunge-psych production, fits an Italian alt rock playlist, 130 BPM, E minor",["rock","Italian alt rock","2000s","heavy","psychedelic"]),
  E("it-bluvertigo","Bluvertigo","it","Итальянские","Rock","Italian electronic rock","1990s",["arty","cold"],120,"D minor","Morgan cool Italian art-rock baritone","1990s Italian electronic rock (rock), arty cold baritone, Italian vocals, electro-rock production, fits an Italian art rock playlist, 120 BPM, D minor",["rock","Italian rock","1990s","arty","cold"]),
  E("it-marlene-kuntz","Marlene Kuntz","it","Итальянские","Rock","Italian alt rock / noise","1990s",["literary","intense"],128,"E minor","Cristiano Godano literary Italian alt baritone","1990s Italian alt rock noise (rock), literary intense baritone, Italian vocals, noise-rock production, fits an Italian alt rock playlist, 128 BPM, E minor",["rock","Italian alt rock","1990s","literary","intense"]),
  E("it-subsonica","Subsonica","it","Итальянские","Rock","Italian electronic rock / Turin","1990s",["danceable","futuristic"],128,"E minor","Samuel Romano futuristic Italian rock tenor","1990s Italian electronic rock (rock), danceable futuristic tenor, Italian vocals, electronica-meets-rock production, fits an Italian alt rock playlist, 128 BPM, E minor",["rock","Italian rock","1990s","danceable","futuristic"]),
  E("it-pgr","CCCP / CSI","it","Итальянские","Rock","Italian post-punk / industrial","1980s",["political","industrial"],125,"D minor","Giovanni Lindo Ferretti political baritone","1980s Italian post-punk (rock), political industrial baritone, Italian vocals, abrasive post-punk production, fits an Italian alt rock playlist, 125 BPM, D minor",["rock","Italian post-punk","1980s","political","industrial"]),

  // — Italian rap / urban
  E("it-caparezza","Caparezza","it","Итальянские","Hip-hop","Italian rap / alt rap","2000s",["satirical","verbose"],95,"D minor","Caparezza verbose satirical Italian rapper","2000s Italian alt rap (hip-hop), satirical verbose rapper, Italian vocals, dense funk-rock-rap production, fits an Italian alt rap playlist, 95 BPM, D minor",["hip-hop","Italian rap","2000s","satirical","verbose"]),
  E("it-articolo-31","Articolo 31","it","Итальянские","Hip-hop","Italian hip-hop / classic","1990s",["pioneering","Milanese"],95,"F minor","J-Ax & DJ Jad Italian rap pioneers","1990s Italian classic hip-hop (hip-hop), pioneering Milanese duo, Italian vocals, classic 90s hip-hop production, fits an Italian rap classics playlist, 95 BPM, F minor",["hip-hop","Italian rap","1990s","pioneering","Milanese"]),
  E("it-marracash","Marracash","it","Итальянские","Hip-hop","Italian rap / street","2000s",["streetwise","Milanese"],90,"D minor","Marracash streetwise Sicilian-Milanese rapper","2000s Italian street rap (hip-hop), streetwise baritone, Italian vocals, modern street-rap production, fits an Italian rap playlist, 90 BPM, D minor",["hip-hop","Italian rap","2000s","streetwise","Milanese"]),
  E("it-gue-pequeno","Gué","it","Итальянские","Hip-hop","Italian rap / Club Dogo","2000s",["cool","Milanese"],90,"F minor","Gué cool Milanese rapper baritone","2000s Italian rap (hip-hop), cool Milanese baritone, Italian vocals, urban Italian rap production, fits an Italian rap playlist, 90 BPM, F minor",["hip-hop","Italian rap","2000s","cool","Milanese"]),
  E("it-fedez","Fedez","it","Итальянские","Hip-hop","Italian pop rap","2010s",["catchy","mainstream"],100,"G minor","Fedez catchy Italian pop-rap tenor","2010s Italian pop rap (hip-hop), catchy mainstream tenor, Italian vocals, polished pop-rap production, fits an Italian pop rap playlist, 100 BPM, G minor",["hip-hop","Italian pop rap","2010s","catchy","mainstream"]),
  E("it-j-ax","J-Ax","it","Итальянские","Hip-hop","Italian rap / pop rap","2000s",["jocular","Milanese"],105,"D major","J-Ax jocular Italian rapper-singer","2000s Italian pop rap (hip-hop), jocular Milanese rapper-singer, Italian vocals, pop-rap with rock guitar production, fits an Italian pop rap playlist, 105 BPM, D major",["hip-hop","Italian pop rap","2000s","jocular","Milanese"]),
  E("it-ghali","Ghali","it","Итальянские","Hip-hop","Italian rap / Tunisian-Italian","2010s",["youthful","multicultural"],95,"F minor","Ghali multicultural Italian rapper","2010s Italian rap (hip-hop), youthful multicultural rapper, Italian/Arabic vocals, modern trap production, fits an Italian rap playlist, 95 BPM, F minor",["hip-hop","Italian rap","2010s","youthful","multicultural"]),
  E("it-achille-lauro","Achille Lauro","it","Итальянские","Pop","Italian pop / glam / trap","2010s",["theatrical","provocative"],110,"E minor","Achille Lauro theatrical glam-trap tenor","2010s Italian glam pop (pop), theatrical provocative tenor, Italian vocals, glam-rock-meets-trap production, fits an Italian glam pop playlist, 110 BPM, E minor",["pop","Italian pop","2010s","theatrical","provocative"]),
  E("it-lazza","Lazza","it","Итальянские","Hip-hop","Italian trap / drill","2010s",["melodic","drill"],140,"F minor","Lazza melodic Italian trap-drill rapper","2010s Italian trap drill (hip-hop), melodic drill rapper, Italian vocals, hard drill-trap production, fits an Italian trap playlist, 140 BPM, F minor",["hip-hop","Italian trap","2010s","melodic","drill"]),
  E("it-geolier","Geolier","it","Итальянские","Hip-hop","Italian rap / Neapolitan trap","2010s",["Neapolitan","melodic"],90,"D minor","Geolier Neapolitan-dialect trap rapper","2010s Italian Neapolitan trap (hip-hop), Neapolitan-dialect rapper, Neapolitan vocals, modern trap production, fits an Italian rap playlist, 90 BPM, D minor",["hip-hop","Italian trap","2010s","Neapolitan","melodic"]),
  E("it-madame","Madame","it","Итальянские","Hip-hop","Italian rap / alt","2010s",["literary","fresh"],95,"D minor","Madame literary Italian young rapper","2010s Italian alt rap (hip-hop), literary fresh young rapper, Italian vocals, melodic alt-rap production, fits an Italian alt rap playlist, 95 BPM, D minor",["hip-hop","Italian rap","2010s","literary","fresh"]),
  E("it-rkomi","Rkomi","it","Итальянские","Hip-hop","Italian rap / pop rap","2010s",["melodic","rock-tinged"],110,"E minor","Rkomi rock-tinged Italian rap-singer","2010s Italian pop rap (hip-hop), melodic rock-tinged rapper, Italian vocals, rap-rock production, fits an Italian pop rap playlist, 110 BPM, E minor",["hip-hop","Italian pop rap","2010s","melodic","rock-tinged"]),
  E("it-coez","Coez","it","Итальянские","Pop","Italian indie pop / urban","2010s",["melodic","earnest"],100,"D major","Coez melodic Italian urban pop tenor","2010s Italian urban indie pop (pop), melodic earnest tenor, Italian vocals, indie-urban production, fits an Italian indie pop playlist, 100 BPM, D major",["pop","Italian indie pop","2010s","melodic","earnest"]),
  E("it-calcutta","Calcutta","it","Итальянские","Pop","Italian indie pop / itpop","2010s",["nostalgic","melodic"],105,"D major","Calcutta nostalgic Italian indie tenor","2010s Italian itpop (pop), nostalgic melodic tenor, Italian vocals, jangly indie-pop production, fits an Italian indie pop playlist, 105 BPM, D major",["pop","itpop","2010s","nostalgic","melodic"]),
  E("it-carl-brave","Carl Brave","it","Итальянские","Pop","Italian indie pop / Roman","2010s",["Roman","laid-back"],100,"G major","Carl Brave laid-back Roman indie tenor","2010s Italian indie pop (pop), Roman laid-back tenor, Italian vocals, indie-pop with hip-hop production, fits an Italian indie pop playlist, 100 BPM, G major",["pop","Italian indie pop","2010s","Roman","laid-back"]),
  E("it-pinguini-tattici-nucleari","Pinguini Tattici Nucleari","it","Итальянские","Pop","Italian indie pop / itpop","2010s",["witty","catchy"],120,"E minor","Pinguini Tattici Nucleari witty Italian indie band","2010s Italian itpop (pop), witty catchy indie pop band, Italian vocals, accessible indie-pop production, fits an Italian indie pop playlist, 120 BPM, E minor",["pop","itpop","2010s","witty","catchy"]),
  E("it-irama","Irama","it","Итальянские","Pop","Italian pop / urban","2010s",["earnest","romantic"],95,"E minor","Irama earnest Italian young tenor","2010s Italian urban pop (pop), earnest romantic tenor, Italian vocals, urban-influenced pop production, fits an Italian pop playlist, 95 BPM, E minor",["pop","Italian pop","2010s","earnest","romantic"]),
  E("it-ultimo","Ultimo","it","Итальянские","Pop","Italian pop / piano pop","2010s",["heartfelt","piano-led"],90,"E major","Ultimo heartfelt Italian piano-pop tenor","2010s Italian piano pop (pop), heartfelt piano-led tenor, Italian vocals, piano ballad production, fits an Italian pop playlist, 90 BPM, E major",["pop","Italian pop","2010s","heartfelt","piano-led"]),
  E("it-mr-rain","Mr. Rain","it","Итальянские","Pop","Italian pop rap","2010s",["melodic","emotional"],100,"D minor","Mr. Rain melodic Italian pop-rap tenor","2010s Italian pop rap (pop), melodic emotional tenor, Italian vocals, polished pop-rap production, fits an Italian pop rap playlist, 100 BPM, D minor",["pop","Italian pop rap","2010s","melodic","emotional"]),
  E("it-tananai","Tananai","it","Итальянские","Pop","Italian indie pop","2010s",["catchy","quirky"],115,"E major","Tananai catchy quirky Italian indie tenor","2010s Italian indie pop (pop), catchy quirky tenor, Italian vocals, modern indie-pop production, fits an Italian indie pop playlist, 115 BPM, E major",["pop","Italian indie pop","2010s","catchy","quirky"]),
  E("it-annalisa","Annalisa","it","Итальянские","Pop","Italian pop","2010s",["polished","melodic"],110,"E major","Annalisa polished Italian pop soprano","2010s Italian pop (pop), polished melodic soprano, Italian vocals, modern pop production, fits an Italian pop playlist, 110 BPM, E major",["pop","Italian pop","2010s","polished","melodic"]),
  E("it-emma","Emma","it","Итальянские","Pop","Italian pop rock","2010s",["raspy","passionate"],120,"E minor","Emma raspy Italian pop-rock soprano","2010s Italian pop rock (pop), raspy passionate soprano, Italian vocals, pop-rock production, fits an Italian pop rock playlist, 120 BPM, E minor",["pop","Italian pop rock","2010s","raspy","passionate"]),
  E("it-alessandra-amoroso","Alessandra Amoroso","it","Итальянские","Pop","Italian pop","2000s",["powerful","Salentino"],100,"D minor","Alessandra Amoroso powerful Italian pop soprano","2000s Italian pop (pop), powerful Salentino soprano, Italian vocals, polished pop production, fits an Italian pop playlist, 100 BPM, D minor",["pop","Italian pop","2000s","powerful","Salentino"]),
  E("it-noemi","Noemi","it","Итальянские","Pop","Italian pop / soul","2010s",["soulful","red-haired"],100,"E minor","Noemi soulful Italian pop alto","2010s Italian pop soul (pop), soulful alto, Italian vocals, soul-influenced pop production, fits an Italian pop playlist, 100 BPM, E minor",["pop","Italian pop","2010s","soulful","red-haired"]),
  E("it-arisa","Arisa","it","Итальянские","Pop","Italian pop / classical","2010s",["pure","crystalline"],95,"E major","Arisa pure crystalline Italian soprano","2010s Italian classical pop (pop), pure crystalline soprano, Italian vocals, orchestral pop production, fits an Italian pop playlist, 95 BPM, E major",["pop","Italian pop","2010s","pure","crystalline"]),

];

const toAdd = newEntries.filter(e => !existingNames.has(e.name.toLowerCase()));
const combined = [...existing, ...toAdd];

await writeFile(dataPath, JSON.stringify(combined, null, 2), "utf8");
console.log(`Added ${toAdd.length} entries. Total: ${combined.length}`);
const skipped = newEntries.filter(e => existingNames.has(e.name.toLowerCase())).map(e => e.name);
if (skipped.length) console.log("Skipped (already exist):", skipped.join(", "));
