import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "data", "artists.json");

const existing = JSON.parse(await readFile(dataPath, "utf8"));
const existingNames = new Set(existing.map(a => a.name.toLowerCase()));

function entry(id, name, language, languageLabel, genre, subgenre, era, mood, bpm, key, vocals, prompt, tags, free = false, isNew = true) {
  return { id, name, language, languageLabel, genre, subgenre, era, mood, bpm, key, vocals, prompt, tags, free, isNew };
}

const newEntries = [

  // ── ENGLISH expand (en: 50 → 80) ──────────────────────────────────────────
  entry("en-adele","Adele","en","Зарубежные","Pop","soul-pop","2010s",["emotional","powerful"],72,"C major","powerful belting soprano","2010s soul-pop (pop), powerful belting soprano, English-language vocals, live piano, orchestral strings, subtle reverb, cinematic production, emotional and powerful mood, fits a heartbreak playlist, 72 BPM, C major",["pop","soul-pop","2010s","emotional","powerful"]),
  entry("en-amy-winehouse","Amy Winehouse","en","Зарубежные","Soul","retro soul / jazz","2000s",["sultry","melancholic"],90,"F minor","raspy jazz-soul alto","2000s retro soul (soul), raspy jazz-soul alto, English-language vocals, upright bass, vintage brass section, lo-fi tape warmth, motown-influenced drums, sultry and melancholic mood, fits a late-night bar playlist, 90 BPM, F minor",["soul","retro soul","jazz","2000s","sultry"]),
  entry("en-arctic-monkeys","Arctic Monkeys","en","Зарубежные","Rock","indie rock / post-punk revival","2000s",["cool","sardonic"],136,"A minor","nasal baritone with Sheffield drawl","2000s indie rock (rock), nasal baritone with Sheffield drawl, English-language vocals, jangly electric guitars, tight snare, punchy bass, dry production, cool and sardonic mood, fits a party rock playlist, 136 BPM, A minor",["rock","indie rock","2000s","cool","sardonic"]),
  entry("en-billie-eilish","Billie Eilish","en","Зарубежные","Pop","dark pop / bedroom pop","2010s",["eerie","intimate"],95,"D minor","breathy whispering soprano","2010s dark pop (pop), breathy whispering soprano, English-language vocals, lo-fi beats, heavy sub-bass, close-mic ASMR textures, sparse production, eerie and intimate mood, fits a late-night playlist, 95 BPM, D minor",["pop","dark pop","2010s","eerie","intimate"]),
  entry("en-bob-dylan","Bob Dylan","en","Зарубежные","Folk","folk rock","1960s",["poetic","world-weary"],104,"G major","raspy nasal baritone","1960s folk rock (folk), raspy nasal baritone, English-language vocals, acoustic guitar strumming, harmonica riffs, simple drum kit, organic recording, poetic and world-weary mood, fits a road-trip playlist, 104 BPM, G major",["folk","folk rock","1960s","poetic","world-weary"],true),
  entry("en-coldplay","Coldplay","en","Зарубежные","Pop","arena rock / post-Britpop","2000s",["uplifting","anthemic"],138,"E major","breathy high tenor","2000s arena rock (pop), breathy high tenor, English-language vocals, chiming piano, jangly guitar arpeggios, massive reverb, stadium drums, uplifting and anthemic mood, fits a workout playlist, 138 BPM, E major",["pop","arena rock","2000s","uplifting","anthemic"]),
  entry("en-david-bowie","David Bowie","en","Зарубежные","Rock","glam rock / art rock","1970s",["theatrical","avant-garde"],118,"D major","chameleonic baritone-tenor","1970s glam rock (rock), chameleonic baritone-tenor, English-language vocals, layered synths, saxophones, rock guitar riffs, studio experimentation, theatrical and avant-garde mood, fits an art-rock playlist, 118 BPM, D major",["rock","glam rock","1970s","theatrical","avant-garde"],true),
  entry("en-dua-lipa","Dua Lipa","en","Зарубежные","Pop","nu-disco / dance-pop","2010s",["confident","danceable"],124,"A minor","warm mezzo with pop polish","2010s nu-disco (pop), warm mezzo with pop polish, English-language vocals, four-on-the-floor kicks, retro synth bass, glittery production, confident and danceable mood, fits a dance-floor playlist, 124 BPM, A minor",["pop","nu-disco","2010s","confident","danceable"]),
  entry("en-ed-sheeran","Ed Sheeran","en","Зарубежные","Pop","pop folk / acoustic pop","2010s",["warm","heartfelt"],87,"G major","intimate tenor with loop-station delivery","2010s pop folk (pop), intimate tenor with loop-station delivery, English-language vocals, acoustic guitar, light percussion, warm production, heartfelt mood, fits a wedding playlist, 87 BPM, G major",["pop","pop folk","2010s","warm","heartfelt"]),
  entry("en-elton-john","Elton John","en","Зарубежные","Pop","glam pop / piano rock","1970s",["flamboyant","sentimental"],120,"B-flat major","theatrical high tenor","1970s glam pop (pop), theatrical high tenor, English-language vocals, grand piano, orchestral strings, gospel choir, lush production, flamboyant and sentimental mood, fits a classics playlist, 120 BPM, B-flat major",["pop","glam pop","1970s","flamboyant","sentimental"],true),
  entry("en-frank-sinatra","Frank Sinatra","en","Зарубежные","Jazz","traditional pop / swing","1950s",["smooth","nostalgic"],126,"C major","velvety baritone crooner","1950s traditional pop (jazz), velvety baritone crooner, English-language vocals, big band brass, lush string arrangements, brushed snare, warm tape compression, smooth and nostalgic mood, fits a lounge playlist, 126 BPM, C major",["jazz","traditional pop","1950s","smooth","nostalgic"],true),
  entry("en-imagine-dragons","Imagine Dragons","en","Зарубежные","Rock","arena pop-rock","2010s",["epic","anthemic"],120,"C major","gravelly pop tenor","2010s arena pop-rock (rock), gravelly pop tenor, English-language vocals, electronic drum machines, massive walls of synth, heavy low-end, epic and anthemic mood, fits a cinematic trailer playlist, 120 BPM, C major",["rock","arena pop-rock","2010s","epic","anthemic"]),
  entry("en-kendrick-lamar","Kendrick Lamar","en","Зарубежные","Hip-hop","conscious hip-hop / jazz rap","2010s",["intense","introspective"],93,"G minor","versatile multi-flow rapper","2010s conscious hip-hop (hip-hop), versatile multi-flow rapper, English-language vocals, live jazz band samples, sub-heavy 808s, complex polyrhythm drums, intense and introspective mood, fits a focus playlist, 93 BPM, G minor",["hip-hop","conscious hip-hop","2010s","intense","introspective"]),
  entry("en-lady-gaga","Lady Gaga","en","Зарубежные","Pop","electropop / dance-pop","2000s",["theatrical","empowering"],128,"A minor","powerful pop soprano","2000s electropop (pop), powerful pop soprano, English-language vocals, synth arpeggios, pounding 4/4 kicks, stadium production, theatrical and empowering mood, fits a confidence playlist, 128 BPM, A minor",["pop","electropop","2000s","theatrical","empowering"]),
  entry("en-led-zeppelin","Led Zeppelin","en","Зарубежные","Rock","hard rock / blues rock","1970s",["heavy","mystical"],112,"E minor","raw bluesy tenor screamer","1970s hard rock (rock), raw bluesy tenor screamer, English-language vocals, distorted power riffs, thunderous live drums, pounding bass, mystical imagery, heavy and mystical mood, fits a classic rock playlist, 112 BPM, E minor",["rock","hard rock","1970s","heavy","mystical"],true),
  entry("en-linkin-park","Linkin Park","en","Зарубежные","Rock","nu-metal / alternative rock","2000s",["angst","intense"],144,"D minor","dual vocal (rap + singing)","2000s nu-metal (rock), dual vocal (rap + singing), English-language vocals, down-tuned guitars, electronic elements, heavy drop beats, emotional and intense mood, fits a gym playlist, 144 BPM, D minor",["rock","nu-metal","2000s","angst","intense"]),
  entry("en-metallica","Metallica","en","Зарубежные","Metal","thrash metal","1980s",["aggressive","epic"],170,"E minor","gruff aggressive baritone","1980s thrash metal (metal), gruff aggressive baritone, English-language vocals, down-tuned drop-D riffs, lightning-fast double-kick, crunching palm mutes, aggressive and epic mood, fits a headbanging playlist, 170 BPM, E minor",["metal","thrash metal","1980s","aggressive","epic"]),
  entry("en-nirvana","Nirvana","en","Зарубежные","Rock","grunge","1990s",["angst","raw"],116,"F major","raspy screaming tenor","1990s grunge (rock), raspy screaming tenor, English-language vocals, distorted drop-D guitar, sloppy live drums, quiet-loud dynamics, raw and angst-ridden mood, fits an alternative playlist, 116 BPM, F major",["rock","grunge","1990s","angst","raw"],true),
  entry("en-pink-floyd","Pink Floyd","en","Зарубежные","Rock","progressive rock / psychedelic","1970s",["cosmic","melancholic"],68,"D major","gentle expressive baritone","1970s progressive rock (rock), gentle expressive baritone, English-language vocals, epic synth pads, spacey guitar solos, ambient soundscapes, multi-part compositions, cosmic and melancholic mood, fits a late-night drive playlist, 68 BPM, D major",["rock","progressive rock","1970s","cosmic","melancholic"],true),
  entry("en-radiohead","Radiohead","en","Зарубежные","Rock","alternative rock / art rock","1990s",["alienated","introspective"],92,"A minor","falsetto-reaching anxious tenor","1990s alternative rock (rock), falsetto-reaching anxious tenor, English-language vocals, glitchy electronics, angular guitar lines, jazzy drums, experimental production, alienated and introspective mood, fits a late-night playlist, 92 BPM, A minor",["rock","alternative rock","1990s","alienated","introspective"]),
  entry("en-rihanna","Rihanna","en","Зарубежные","Pop","dance-pop / R&B","2000s",["edgy","sultry"],122,"G-sharp minor","Caribbean-accented R&B soprano","2000s dance-pop (pop), Caribbean-accented R&B soprano, English-language vocals, synth bass drops, 808 snares, glitchy vocal chops, edgy and sultry mood, fits a club playlist, 122 BPM, G-sharp minor",["pop","dance-pop","R&B","2000s","edgy","sultry"]),
  entry("en-taylor-swift","Taylor Swift","en","Зарубежные","Pop","country-pop / synth-pop","2010s",["nostalgic","empowering"],130,"G major","bright country-pop soprano","2010s country-pop (pop), bright country-pop soprano, English-language vocals, acoustic and electric guitar blend, electronic beats, shimmering production, nostalgic and empowering mood, fits a driving playlist, 130 BPM, G major",["pop","country-pop","2010s","nostalgic","empowering"]),
  entry("en-the-beatles","The Beatles","en","Зарубежные","Rock","classic rock / Merseybeat","1960s",["joyful","experimental"],134,"C major","harmonized British tenor/baritone","1960s classic rock (rock), harmonized British tenor/baritone, English-language vocals, jangly Rickenbacker guitar, steady rock kit, analog tape, joyful and experimental mood, fits a feel-good playlist, 134 BPM, C major",["rock","classic rock","1960s","joyful","experimental"],true),
  entry("en-the-weeknd","The Weeknd","en","Зарубежные","R&B","dark R&B / synthwave","2010s",["dark","sensual"],105,"C-sharp minor","silky falsetto tenor","2010s dark R&B (R&B), silky falsetto tenor, English-language vocals, lush 80s-style synths, gated reverb drums, pulsing bass, dark and sensual mood, fits a midnight drive playlist, 105 BPM, C-sharp minor",["R&B","dark R&B","2010s","dark","sensual"]),
  entry("en-travis-scott","Travis Scott","en","Зарубежные","Hip-hop","trap / psychedelic rap","2010s",["hazy","hypnotic"],140,"F minor","auto-tuned melodic rapper","2010s trap (hip-hop), auto-tuned melodic rapper, English-language vocals, ominous 808 slides, hi-hat rolls, atmospheric synth pads, hazy and hypnotic mood, fits a late-night trap playlist, 140 BPM, F minor",["hip-hop","trap","2010s","hazy","hypnotic"]),
  entry("en-post-malone","Post Malone","en","Зарубежные","Hip-hop","emo rap / pop rap","2010s",["melancholic","laid-back"],145,"G minor","melodic tattooed rock-rapper","2010s emo rap (hip-hop), melodic tattooed rock-rapper, English-language vocals, trap hi-hats, distorted guitar samples, watery reverb, melancholic and laid-back mood, fits a chill trap playlist, 145 BPM, G minor",["hip-hop","emo rap","2010s","melancholic","laid-back"]),
  entry("en-beyonce","Beyoncé","en","Зарубежные","R&B","pop R&B / neo-soul","2000s",["powerful","regal"],120,"B-flat minor","powerhouse soprano with gospel roots","2000s pop R&B (R&B), powerhouse soprano with gospel roots, English-language vocals, lush orchestration, driving funk bass, tight snare, regal and powerful mood, fits a confidence playlist, 120 BPM, B-flat minor",["R&B","pop R&B","2000s","powerful","regal"]),
  entry("en-drake","Drake","en","Зарубежные","Hip-hop","rap / melodic hip-hop","2010s",["introspective","smooth"],140,"A minor","half-sung half-rapped tenor","2010s melodic hip-hop (hip-hop), half-sung half-rapped tenor, English-language vocals, sample-heavy beats, lush 808s, atmospheric pads, introspective and smooth mood, fits a late-night playlist, 140 BPM, A minor",["hip-hop","melodic hip-hop","2010s","introspective","smooth"]),
  entry("en-eminem","Eminem","en","Зарубежные","Hip-hop","hardcore rap","2000s",["intense","witty"],100,"D minor","rapid-fire lyrical baritone","2000s hardcore rap (hip-hop), rapid-fire lyrical baritone, English-language vocals, boom-bap drums, sparse piano loops, hard snares, intense and witty mood, fits a focus rap playlist, 100 BPM, D minor",["hip-hop","hardcore rap","2000s","intense","witty"]),
  entry("en-daft-punk","Daft Punk","en","Зарубежные","Electronic","french house / electro","1990s",["futuristic","groovy"],124,"F minor","vocoder robot vocal","1990s french house (electronic), vocoder robot vocal, English-language vocals, filter sweeps, funky disco bass, four-on-the-floor, analogue synth stabs, futuristic and groovy mood, fits a house party playlist, 124 BPM, F minor",["electronic","french house","1990s","futuristic","groovy"],true),

  // ── RUSSIAN expand (ru: 34 → 50) ──────────────────────────────────────────
  entry("ru-alla-pugacheva","Алла Пугачёва","ru","Русские","Pop","советский поп","1970s",["theatrical","sentimental"],110,"C major","мощное лирическое сопрано","1970s Soviet pop (pop), powerful lyrical soprano, Russian-language vocals, lush orchestral strings, grand piano, theatrical stage production, sentimental and dramatic mood, fits a Russian classics playlist, 110 BPM, C major",["pop","советский поп","1970s","theatrical","sentimental"],true),
  entry("ru-zemfira","Земфира","ru","Русские","Rock","альтернативный рок","1990s",["melancholic","raw"],118,"E minor","хриплое сопрано с надломом","1990s Russian alt-rock (rock), hoarse soprano with emotional cracks, Russian-language vocals, distorted electric guitar, post-Soviet lo-fi production, melancholic and raw mood, fits a rainy-day playlist, 118 BPM, E minor",["rock","альтернативный рок","1990s","melancholic","raw"]),
  entry("ru-bi-2","Би-2","ru","Русские","Rock","брит-рок / российский рок","2000s",["melodic","anthemic"],128,"A major","мягкий тенор в рок-обёртке","2000s Russian brit-rock (rock), smooth tenor with melodic phrasing, Russian-language vocals, jangly electric guitar, driving rock drums, anthemic and melodic mood, fits a radio rock playlist, 128 BPM, A major",["rock","брит-рок","2000s","melodic","anthemic"]),
  entry("ru-leningrad","Ленинград","ru","Русские","Rock","ska-punk / провокационный рок","1990s",["wild","party"],160,"G major","разудалый баритон-шансонье","1990s ska-punk (rock), rowdy baritone chansonnier, Russian-language vocals, tuba and brass section, punk guitars, sloppy live drums, wild and party mood, fits a drunken sing-along playlist, 160 BPM, G major",["rock","ska-punk","1990s","wild","party"]),
  entry("ru-monetochka","Монеточка","ru","Русские","Pop","инди-поп / ироничный поп","2010s",["ironic","nostalgic"],115,"D major","девичий поп-сопрано с иронией","2010s indie pop (pop), girlish soprano with ironic tone, Russian-language vocals, synth pads, minimal drum machine, nostalgic and ironic mood, fits a Gen-Z Russian playlist, 115 BPM, D major",["pop","инди-поп","2010s","ironic","nostalgic"]),
  entry("ru-morgenshtern","Моргенштерн","ru","Русские","Hip-hop","трэп / хайп-хоп","2010s",["provocative","energetic"],145,"F minor","провокационный авто-тюн рэпер","2010s Russian trap (hip-hop), provocative auto-tuned rapper, Russian-language vocals, sliding 808 bass, trap hi-hats, rave synths, energetic and provocative mood, fits a hype playlist, 145 BPM, F minor",["hip-hop","трэп","2010s","provocative","energetic"]),
  entry("ru-face","FACE","ru","Русские","Hip-hop","трэп / эмо-рэп","2010s",["melancholic","underground"],140,"C minor","монотонный трэп-рэпер","2010s Russian emo trap (hip-hop), monotone trap rapper, Russian-language vocals, dark 808s, lo-fi samples, melancholic mood, fits an underground Russian hip-hop playlist, 140 BPM, C minor",["hip-hop","трэп","2010s","melancholic","underground"]),
  entry("ru-oxxxymiron","Oxxxymiron","ru","Русские","Hip-hop","бит-поэзия / альт-рэп","2010s",["intellectual","dark"],95,"D minor","многослойный словесный баттл-рэпер","2010s alt-rap (hip-hop), multilayered lyrical battle rapper, Russian-language vocals, orchestral samples, complex polyrhythmic beats, dark and intellectual mood, fits a lyrical rap playlist, 95 BPM, D minor",["hip-hop","альт-рэп","2010s","intellectual","dark"]),
  entry("ru-shaman","SHAMAN","ru","Русские","Pop","патриотичный поп-рок","2020s",["epic","patriotic"],118,"B-flat major","драматичный тенор","2020s patriotic pop-rock (pop), dramatic tenor, Russian-language vocals, soaring strings, anthemic guitars, stadium production, epic and patriotic mood, fits an inspirational Russian playlist, 118 BPM, B-flat major",["pop","патриотичный","2020s","epic","patriotic"]),
  entry("ru-gruppa-krovi","Кино","ru","Русские","Rock","постпанк / новая волна","1980s",["poetic","yearning"],122,"G minor","меланхоличный баритон Цоя","1980s Soviet post-punk (rock), melancholic poetic baritone, Russian-language vocals, cold synth pads, sparse guitar, gated reverb drums, yearning and iconic mood, fits a Soviet cult classics playlist, 122 BPM, G minor",["rock","постпанк","1980s","poetic","yearning"],true),
  entry("ru-nautilus","Nautilus Pompilius","ru","Русские","Rock","арт-рок / советский рок","1980s",["existential","gloomy"],108,"E minor","низкий интеллектуальный баритон","1980s Soviet art-rock (rock), low intellectual baritone, Russian-language vocals, dark synths, jangly guitar, minimalist production, existential and gloomy mood, fits a philosophical rock playlist, 108 BPM, E minor",["rock","арт-рок","1980s","existential","gloomy"]),
  entry("ru-alisher","Alisher","ru","Русские","Hip-hop","меланхоличный рэп","2010s",["melancholic","intimate"],92,"A minor","мягкий задумчивый рэп-тенор","2010s melancholic rap (hip-hop), soft pensive rap tenor, Russian-language vocals, jazz piano loops, slow trap drums, intimate mood, fits a sad boy playlist, 92 BPM, A minor",["hip-hop","меланхоличный рэп","2010s","melancholic","intimate"]),
  entry("ru-lyube","Любэ","ru","Русские","Rock","русский рок / шансон-рок","1990s",["patriotic","nostalgic"],118,"G major","хриплый народный тенор","1990s Russian rock (rock), rough folk-inflected tenor, Russian-language vocals, accordion elements, electric guitar, marching drums, patriotic and nostalgic mood, fits a Russian folk-rock playlist, 118 BPM, G major",["rock","шансон-рок","1990s","patriotic","nostalgic"]),
  entry("ru-ddt","ДДТ","ru","Русские","Rock","русский рок","1980s",["protest","soulful"],112,"D minor","надрывный поэтический тенор Шевчука","1980s Russian rock (rock), anguished poetic tenor, Russian-language vocals, acoustic and electric guitar mix, protest poetry delivery, soulful and raw mood, fits a Russian rock classics playlist, 112 BPM, D minor",["rock","русский рок","1980s","protest","soulful"]),
  entry("ru-basta","Баста","ru","Русские","Hip-hop","русский хип-хоп / южный рэп","2000s",["smooth","street"],98,"F minor","спокойный уличный баритон","2000s Russian hip-hop (hip-hop), calm street baritone, Russian-language vocals, soulful soul samples, heavy 808s, smooth and street mood, fits a Russian summer playlist, 98 BPM, F minor",["hip-hop","русский хип-хоп","2000s","smooth","street"]),
  entry("ru-rammstein-ru","IC3PEAK","ru","Русские","Electronic","dark electro / industrial pop","2010s",["dark","rebellious"],140,"C minor","ледяное сопрано над индастриал-битом","2010s dark electro (electronic), ice-cold soprano over industrial beat, Russian-language vocals, distorted synths, heavy kick drums, rebellious mood, fits a dark dance playlist, 140 BPM, C minor",["electronic","dark electro","2010s","dark","rebellious"]),

  // ── ARABIC (ar: 0 → 20) ───────────────────────────────────────────────────
  entry("ar-fairuz","Fairuz","ar","Арабские","Classical","Arabic classical / maqam","1950s",["ethereal","sorrowful"],80,"Maqam Rast","angelic crystalline soprano","1950s Arabic classical (classical), angelic crystalline soprano, Arabic-language vocals, oud, qanun, Arabic percussion (tabla), lush orchestral strings, ethereal and sorrowful mood, fits a Middle Eastern classics playlist, 80 BPM, Maqam Rast",["classical","Arabic classical","1950s","ethereal","sorrowful"],true),
  entry("ar-amr-diab","Amr Diab","ar","Арабские","Pop","Mediterranean pop / shaabi","1990s",["romantic","summery"],118,"Maqam Bayati","smooth romantic tenor","1990s Mediterranean pop (pop), smooth romantic tenor, Arabic-language vocals, electric bouzouki, synth pads, light percussion, romantic and summery mood, fits a beach playlist, 118 BPM, Maqam Bayati",["pop","Mediterranean pop","1990s","romantic","summery"],true),
  entry("ar-nancy-ajram","Nancy Ajram","ar","Арабские","Pop","Arabic pop","2000s",["playful","sensual"],122,"Maqam Hijaz","bright bubbly soprano","2000s Arabic pop (pop), bright bubbly soprano, Arabic-language vocals, digital tabla, synth bass, catchy hooks, playful and sensual mood, fits an Arabic pop playlist, 122 BPM, Maqam Hijaz",["pop","Arabic pop","2000s","playful","sensual"]),
  entry("ar-elissa","Elissa","ar","Арабские","Pop","Lebanese pop","2000s",["emotional","romantic"],100,"Maqam Kurd","tender emotional soprano","2000s Lebanese pop (pop), tender emotional soprano, Arabic-language vocals, orchestral strings, piano, light electronic beats, emotional and romantic mood, fits a sad Arabic playlist, 100 BPM, Maqam Kurd",["pop","Lebanese pop","2000s","emotional","romantic"]),
  entry("ar-umm-kulthum","Umm Kulthum","ar","Арабские","Classical","Egyptian classical / tarab","1940s",["transcendent","mournful"],60,"Maqam Sikah","legendary contralto with microtonal ornaments","1940s Egyptian classical (classical), legendary contralto with microtonal ornaments, Arabic-language vocals, orchestral takht ensemble, long improvised phrases, transcendent and mournful mood, fits a tarab meditation playlist, 60 BPM, Maqam Sikah",["classical","Egyptian classical","1940s","transcendent","mournful"],true),
  entry("ar-kadim-al-saher","Kadim Al Saher","ar","Арабские","Pop","Iraqi classical pop","1990s",["romantic","grand"],90,"Maqam Rast","theatrical lyrical tenor","1990s Iraqi classical pop (pop), theatrical lyrical tenor, Arabic-language vocals, symphonic orchestra, poetic lyrics delivery, romantic and grand mood, fits an Arabic classics playlist, 90 BPM, Maqam Rast",["pop","Iraqi classical pop","1990s","romantic","grand"]),
  entry("ar-fadel-shaker","Fadel Shaker","ar","Арабские","Pop","Lebanese pop / tarab","2000s",["emotive","melancholic"],95,"Maqam Hijaz","silky emotional tenor","2000s Lebanese pop (pop), silky emotional tenor, Arabic-language vocals, violin-heavy orchestration, light synth, melancholic mood, fits a romantic Arabic playlist, 95 BPM, Maqam Hijaz",["pop","Lebanese pop","2000s","emotive","melancholic"]),
  entry("ar-tamer-hosny","Tamer Hosny","ar","Арабские","Pop","Egyptian pop / R&B","2000s",["smooth","youthful"],108,"Maqam Bayati","smooth youthful tenor","2000s Egyptian pop (pop), smooth youthful tenor, Arabic-language vocals, pop production with Arabic scales, R&B beats, smooth mood, fits a youth Arabic playlist, 108 BPM, Maqam Bayati",["pop","Egyptian pop","2000s","smooth","youthful"]),
  entry("ar-majida-el-roumi","Majida El Roumi","ar","Арабские","Classical","Arabic art song","1980s",["majestic","lyrical"],75,"Maqam Nahawand","majestic lyric soprano","1980s Arabic art song (classical), majestic lyric soprano, Arabic-language vocals, full orchestra, poetry settings, majestic and lyrical mood, fits a literary Arabic playlist, 75 BPM, Maqam Nahawand",["classical","Arabic art song","1980s","majestic","lyrical"]),
  entry("ar-ragheb-alama","Ragheb Alama","ar","Арабские","Pop","Lebanese pop","1990s",["festive","charming"],120,"Maqam Ajam","charming baritone with Lebanese flair","1990s Lebanese pop (pop), charming baritone with Lebanese flair, Arabic-language vocals, dabke-influenced rhythms, festive production, fits a wedding playlist, 120 BPM, Maqam Ajam",["pop","Lebanese pop","1990s","festive","charming"]),
  entry("ar-sabah-fakhri","Sabah Fakhri","ar","Арабские","Classical","Syrian muwashshah / tarab","1960s",["ecstatic","ornate"],70,"Maqam Bayati","ornate maqam tenor with waslah delivery","1960s Syrian classical (classical), ornate maqam tenor, Arabic-language vocals, Arabic ensemble, complex rhythmic cycles, ecstatic and ornate mood, fits a Sufi-leaning playlist, 70 BPM, Maqam Bayati",["classical","muwashshah","1960s","ecstatic","ornate"]),
  entry("ar-balqees","Balqees","ar","Арабские","Pop","Gulf pop / khaleeji","2010s",["empowering","modern"],115,"Maqam Rast","confident modern soprano","2010s Gulf pop (pop), confident modern soprano, Arabic-language vocals, khaleeji rhythms, modern production, empowering mood, fits a contemporary Arabic playlist, 115 BPM, Maqam Rast",["pop","khaleeji","2010s","empowering","modern"]),
  entry("ar-hussein-al-jasmi","Hussein Al Jasmi","ar","Арабские","Pop","Emirati pop / khaleeji","2000s",["warm","patriotic"],110,"Maqam Hijaz","warm khaleeji baritone","2000s Emirati pop (pop), warm khaleeji baritone, Arabic-language vocals, tabl drums, khaleeji guitar patterns, warm and patriotic mood, fits a Gulf playlist, 110 BPM, Maqam Hijaz",["pop","khaleeji","2000s","warm","patriotic"]),
  entry("ar-wael-kfoury","Wael Kfoury","ar","Арабские","Pop","Lebanese romantic pop","2000s",["heartbreak","smooth"],88,"Maqam Kurd","smooth baritone romantic","2000s Lebanese romantic pop (pop), smooth baritone, Arabic-language vocals, piano-led ballads, orchestral touches, heartbreak mood, fits a sad Arabic playlist, 88 BPM, Maqam Kurd",["pop","Lebanese pop","2000s","heartbreak","smooth"]),
  entry("ar-assala","Assala Nasri","ar","Арабские","Pop","Syrian pop","2000s",["soulful","vivacious"],112,"Maqam Bayati","vivacious mezzo-soprano","2000s Syrian pop (pop), vivacious mezzo-soprano, Arabic-language vocals, pop orchestration, soulful delivery, fits a lively Arabic playlist, 112 BPM, Maqam Bayati",["pop","Syrian pop","2000s","soulful","vivacious"]),
  entry("ar-maher-zain","Maher Zain","ar","Арабские","Pop","Islamic nasheed pop","2000s",["spiritual","uplifting"],100,"Maqam Rast","pure clear tenor","2000s nasheed pop (pop), pure clear tenor, multilingual vocals, acoustic guitars, light orchestration, spiritual and uplifting mood, fits a devotional playlist, 100 BPM, Maqam Rast",["pop","nasheed","2000s","spiritual","uplifting"]),
  entry("ar-diana-haddad","Diana Haddad","ar","Арабские","Pop","Gulf pop","2000s",["energetic","danceable"],126,"Maqam Ajam","energetic soprano with khaleeji flair","2000s Gulf pop (pop), energetic soprano, Arabic-language vocals, khaleeji dance beats, danceable mood, fits an Arabic party playlist, 126 BPM, Maqam Ajam",["pop","Gulf pop","2000s","energetic","danceable"]),
  entry("ar-ali-deek","Ali Deek","ar","Арабские","Folk","Syrian folk / mawwal","1980s",["rustic","nostalgic"],90,"Maqam Hijaz","rustic mawwal baritone","1980s Syrian folk (folk), rustic mawwal baritone, Arabic-language vocals, folk instruments, nostalgic rural mood, fits a Syrian heritage playlist, 90 BPM, Maqam Hijaz",["folk","Syrian folk","1980s","rustic","nostalgic"]),
  entry("ar-hamid-al-shaeri","Hamid Al Shaeri","ar","Арабские","Pop","Egyptian pop / shaabi","1990s",["groovy","urban"],125,"Maqam Rast","catchy urban tenor","1990s Egyptian pop (pop), catchy urban tenor, Arabic-language vocals, shaabi percussion, synth bass, groovy and urban mood, fits a street Arabic playlist, 125 BPM, Maqam Rast",["pop","shaabi","1990s","groovy","urban"]),
  entry("ar-kazem-al-saher-2","Mohammed Abdo","ar","Арабские","Classical","Saudi classical / jeel","1970s",["stately","lyrical"],80,"Maqam Rast","stately lyric tenor","1970s Saudi classical (classical), stately lyric tenor, Arabic-language vocals, oud, orchestral arrangement, stately and lyrical mood, fits a Gulf classics playlist, 80 BPM, Maqam Rast",["classical","Saudi classical","1970s","stately","lyrical"]),

  // ── CHINESE (zh: 0 → 20) ──────────────────────────────────────────────────
  entry("zh-jay-chou","Jay Chou","zh","Китайские","Pop","mandopop / R&B","2000s",["romantic","creative"],88,"G major","smooth mid-range Mandarin tenor","2000s mandopop (pop), smooth mid-range Mandarin tenor, Chinese-language vocals, piano, acoustic guitar, light R&B beats, creative and romantic mood, fits a Chinese pop classics playlist, 88 BPM, G major",["pop","mandopop","2000s","romantic","creative"],true),
  entry("zh-teresa-teng","Teresa Teng","zh","Китайские","Pop","classic mandopop","1970s",["gentle","nostalgic"],88,"C major","sweet crystalline soprano","1970s classic mandopop (pop), sweet crystalline soprano, Chinese-language vocals, traditional Chinese instruments, orchestral strings, gentle and nostalgic mood, fits a vintage Chinese pop playlist, 88 BPM, C major",["pop","classic mandopop","1970s","gentle","nostalgic"],true),
  entry("zh-gem","G.E.M.","zh","Китайские","Pop","pop rock / mandopop","2010s",["powerful","passionate"],130,"A minor","powerful rock soprano with emotional range","2010s pop rock (pop), powerful rock soprano, Chinese-language vocals, electric guitar, driving drums, passionate mood, fits a Chinese rock playlist, 130 BPM, A minor",["pop","pop rock","2010s","powerful","passionate"]),
  entry("zh-eason-chan","Eason Chan","zh","Китайские","Pop","cantopop / mandopop","2000s",["versatile","melancholic"],95,"E minor","expressive baritone with wide range","2000s cantopop (pop), expressive baritone, Cantonese/Mandarin vocals, piano ballads, R&B elements, versatile and melancholic mood, fits a HK pop playlist, 95 BPM, E minor",["pop","cantopop","2000s","versatile","melancholic"],true),
  entry("zh-faye-wong","Faye Wong","zh","Китайские","Pop","dream pop / cantopop","1990s",["ethereal","indie"],105,"D major","dreamy atmospheric soprano","1990s dream pop (pop), dreamy atmospheric soprano, Chinese-language vocals, alternative guitar textures, Cocteau Twins-influenced soundscapes, ethereal mood, fits a dream pop playlist, 105 BPM, D major",["pop","dream pop","1990s","ethereal","indie"]),
  entry("zh-jacky-cheung","Jacky Cheung","zh","Китайские","Pop","cantopop / ballad","1990s",["romantic","soulful"],80,"F major","golden age Canto baritone","1990s cantopop (pop), golden age Canto baritone, Cantonese vocals, lush orchestration, sentimental ballads, romantic and soulful mood, fits a HK classics playlist, 80 BPM, F major",["pop","cantopop","1990s","romantic","soulful"]),
  entry("zh-stefanie-sun","Stefanie Sun","zh","Китайские","Pop","mandopop / folk pop","2000s",["warm","sincere"],92,"C major","warm girl-next-door soprano","2000s mandopop (pop), warm sincere soprano, Chinese-language vocals, acoustic guitar, breezy production, fits a feel-good Chinese playlist, 92 BPM, C major",["pop","mandopop","2000s","warm","sincere"]),
  entry("zh-a-mei","A-Mei","zh","Китайские","Pop","mandopop / R&B soul","2000s",["powerful","tribal"],118,"G minor","powerful tribal-influenced belter","2000s mandopop R&B (pop), powerful tribal-influenced belter, Chinese-language vocals, Aboriginal Taiwan influences, R&B production, powerful mood, fits a Chinese soul playlist, 118 BPM, G minor",["pop","mandopop","2000s","powerful","tribal"]),
  entry("zh-jay-lin","Hins Cheung","zh","Китайские","Pop","cantopop / R&B","2000s",["suave","urban"],108,"A major","suave urban cantopop tenor","2000s cantopop (pop), suave urban tenor, Cantonese vocals, R&B production, smooth groove, fits a modern HK playlist, 108 BPM, A major",["pop","cantopop","2000s","suave","urban"]),
  entry("zh-wang-fei","Xu Wei","zh","Китайские","Rock","Chinese indie rock","1990s",["raw","poetic"],112,"E minor","raw guitar poet baritone","1990s Chinese indie rock (rock), raw guitar poet baritone, Chinese-language vocals, distorted guitar, emotional delivery, raw and poetic mood, fits a Chinese rock playlist, 112 BPM, E minor",["rock","Chinese indie rock","1990s","raw","poetic"]),
  entry("zh-cui-jian","Cui Jian","zh","Китайские","Rock","Chinese rock / new wave","1980s",["rebellious","pioneer"],128,"D major","gravelly rock pioneer baritone","1980s Chinese rock (rock), gravelly rock pioneer baritone, Chinese-language vocals, electric guitar, new wave production, rebellious mood, fits a Chinese rock origins playlist, 128 BPM, D major",["rock","Chinese rock","1980s","rebellious","pioneer"],true),
  entry("zh-mayday","Mayday","zh","Китайские","Rock","Taiwanese rock / alternative","2000s",["anthemic","youthful"],135,"G major","soaring youthful tenor","2000s Taiwanese rock (rock), soaring youthful tenor, Chinese-language vocals, electric guitar wall of sound, anthemic production, fits a stadium rock playlist, 135 BPM, G major",["rock","Taiwanese rock","2000s","anthemic","youthful"]),
  entry("zh-jj-lin","JJ Lin","zh","Китайские","Pop","mandopop / neo soul","2000s",["versatile","charismatic"],105,"B-flat major","versatile charismatic tenor","2000s mandopop (pop), versatile charismatic tenor, Chinese-language vocals, neo soul production, jazz harmonics, fits a sophisticated pop playlist, 105 BPM, B-flat major",["pop","mandopop","2000s","versatile","charismatic"]),
  entry("zh-yoga-lin","Yoga Lin","zh","Китайские","Pop","indie pop / alternative","2010s",["introspective","artsy"],98,"C minor","introspective alternative tenor","2010s indie pop (pop), introspective alternative tenor, Chinese-language vocals, indie production, artsy mood, fits a Taiwanese indie playlist, 98 BPM, C minor",["pop","indie pop","2010s","introspective","artsy"]),
  entry("zh-fish-leong","Fish Leong","zh","Китайские","Pop","mandopop ballad","2000s",["heartfelt","tearful"],78,"E major","tender emotional soprano","2000s mandopop (pop), tender emotional soprano, Chinese-language vocals, piano ballad, strings, heartfelt and tearful mood, fits a Chinese breakup playlist, 78 BPM, E major",["pop","mandopop","2000s","heartfelt","tearful"]),
  entry("zh-wilber-pan","Wilber Pan","zh","Китайские","Pop","mandopop / dance","2000s",["funky","energetic"],125,"F major","funky dance pop tenor","2000s mandopop (pop), funky dance pop tenor, Chinese-language vocals, R&B beats, energetic production, fits a Chinese dance playlist, 125 BPM, F major",["pop","mandopop","2000s","funky","energetic"]),
  entry("zh-sun-yan-zi","Sun Yan-Zi","zh","Китайские","Pop","Singapore mandopop","2000s",["sweet","uplifting"],105,"D major","sweet Singaporean soprano","2000s Singapore mandopop (pop), sweet soprano, Chinese-language vocals, pop rock production, uplifting mood, fits a family-friendly playlist, 105 BPM, D major",["pop","mandopop","2000s","sweet","uplifting"]),
  entry("zh-wang-leehom","Wang Leehom","zh","Китайские","Pop","chinked-out / fusion","2000s",["creative","patriotic"],120,"A major","creative fusion tenor","2000s chinked-out (pop), creative fusion tenor, Chinese-language vocals, erhu meets hip-hop, pipa samples, patriotic and creative mood, fits a cultural fusion playlist, 120 BPM, A major",["pop","fusion","2000s","creative","patriotic"]),
  entry("zh-elva-hsiao","Elva Hsiao","zh","Китайские","Pop","electropop / dance","2000s",["energetic","cute"],130,"G major","bright energetic soprano","2000s electropop (pop), bright energetic soprano, Chinese-language vocals, synth dance beats, cute and energetic mood, fits a Taiwanese dance playlist, 130 BPM, G major",["pop","electropop","2000s","energetic","cute"]),
  entry("zh-luhan","Luhan","zh","Китайские","Pop","C-pop / EXO alumni","2010s",["youthful","polished"],128,"F minor","polished idol tenor","2010s C-pop (pop), polished idol tenor, Chinese-language vocals, K-pop-influenced production, youthful mood, fits a modern C-pop playlist, 128 BPM, F minor",["pop","C-pop","2010s","youthful","polished"]),

  // ── AFRICAN (af: 0 → 20) ─────────────────────────────────────────────────
  entry("af-burna-boy","Burna Boy","af","Африканские","Afrobeats","afrofusion","2010s",["confident","infectious"],100,"D minor","raspy Nigerian baritone","2010s afrofusion (afrobeats), raspy Nigerian baritone, English/Pidgin vocals, live percussion, dancehall influences, brass accents, confident and infectious mood, fits an Afrobeats playlist, 100 BPM, D minor",["afrobeats","afrofusion","2010s","confident","infectious"],true),
  entry("af-wizkid","Wizkid","af","Африканские","Afrobeats","afropop","2010s",["smooth","groovy"],106,"G major","smooth Nigerian tenor","2010s afropop (afrobeats), smooth Nigerian tenor, English/Yoruba vocals, Afrobeats groove, shekere, dancehall riddims, smooth and groovy mood, fits a tropical playlist, 106 BPM, G major",["afrobeats","afropop","2010s","smooth","groovy"],true),
  entry("af-davido","Davido","af","Африканские","Afrobeats","afropop","2010s",["vibrant","celebratory"],108,"A major","vibrant melodic Nigerian tenor","2010s afropop (afrobeats), vibrant melodic tenor, English/Yoruba vocals, Afrobeats drums, celebratory mood, fits a party playlist, 108 BPM, A major",["afrobeats","afropop","2010s","vibrant","celebratory"]),
  entry("af-fela-kuti","Fela Kuti","af","Африканские","Afrobeats","afrobeat (classic)","1970s",["political","hypnotic"],105,"F minor","preaching baritone bandleader","1970s classic afrobeat (afrobeats), preaching baritone bandleader, Yoruba/Pidgin vocals, 30-piece live band, Yoruba percussion, brass section, political and hypnotic mood, fits an afrobeat originals playlist, 105 BPM, F minor",["afrobeats","classic afrobeat","1970s","political","hypnotic"],true),
  entry("af-miriam-makeba","Miriam Makeba","af","Африканские","World","South African folk / jazz","1960s",["dignified","sorrowful"],110,"D major","powerful South African alto","1960s South African folk (world), powerful South African alto, Zulu/Xhosa vocals, mbaqanga rhythms, jazz harmonics, dignified and sorrowful mood, fits a world music playlist, 110 BPM, D major",["world","South African folk","1960s","dignified","sorrowful"],true),
  entry("af-youssou-ndour","Youssou N'Dour","af","Африканские","World","mbalax","1980s",["joyful","energetic"],130,"G major","soaring Senegambian tenor","1980s mbalax (world), soaring Senegambian tenor, Wolof vocals, sabar percussion, talking drum, mbalax rhythms, joyful and energetic mood, fits a Senegalese dance playlist, 130 BPM, G major",["world","mbalax","1980s","joyful","energetic"],true),
  entry("af-tiwa-savage","Tiwa Savage","af","Африканские","Afrobeats","afropop","2010s",["fierce","sensual"],104,"C major","fierce Nigerian soprano","2010s afropop (afrobeats), fierce Nigerian soprano, English/Yoruba vocals, Afrobeats production, dancehall flavor, fierce and sensual mood, fits a Queens of Afrobeats playlist, 104 BPM, C major",["afrobeats","afropop","2010s","fierce","sensual"]),
  entry("af-angelique-kidjo","Angélique Kidjo","af","Африканские","World","Afro-world fusion","1990s",["powerful","celebratory"],118,"E major","exuberant Beninese soprano","1990s Afro-world (world), exuberant Beninese soprano, Yoruba/French vocals, brass, West African percussion, danceable groove, powerful and celebratory mood, fits a world fusion playlist, 118 BPM, E major",["world","Afro-world","1990s","powerful","celebratory"]),
  entry("af-king-sunny-ade","King Sunny Ade","af","Африканские","World","jùjú music","1980s",["flowing","spiritual"],96,"D major","smooth Yoruba tenor","1980s jùjú music (world), smooth Yoruba tenor, Yoruba vocals, talking drum, pedal steel guitar, dense percussion grid, flowing and spiritual mood, fits a Nigerian heritage playlist, 96 BPM, D major",["world","jùjú","1980s","flowing","spiritual"]),
  entry("af-dbanj","D'banj","af","Африканские","Afrobeats","afropop / dancehall","2000s",["fun","party"],112,"G minor","energetic harmonica-playing Nigerian","2000s afropop (afrobeats), energetic showman tenor, English/Pidgin vocals, harmonica hooks, dancehall beats, fun and party mood, fits an old-school Afrobeats playlist, 112 BPM, G minor",["afrobeats","afropop","2000s","fun","party"]),
  entry("af-asa","Asa","af","Африканские","Soul","neo-soul / Afro-folk","2000s",["soulful","contemplative"],80,"E minor","warm soulful Nigerian alto","2000s Afro-folk (soul), warm soulful Nigerian alto, French/English vocals, acoustic guitar, light percussion, soulful and contemplative mood, fits a quiet Sunday playlist, 80 BPM, E minor",["soul","Afro-folk","2000s","soulful","contemplative"]),
  entry("af-olamide","Olamide","af","Африканские","Hip-hop","afro-hip-hop","2010s",["street","vigorous"],140,"C minor","raw street Yoruba rapper","2010s Afro-hip-hop (hip-hop), raw street Yoruba rapper, Yoruba/Pidgin vocals, trap beats with African percussion, street and vigorous mood, fits a Lagos street playlist, 140 BPM, C minor",["hip-hop","afro-hip-hop","2010s","street","vigorous"]),
  entry("af-sauti-sol","Sauti Sol","af","Африканские","Afropop","Kenyan afropop","2010s",["uplifting","harmonious"],102,"F major","four-part male harmony group","2010s Kenyan afropop (afropop), rich male harmonies, Swahili/English vocals, acoustic guitar, African percussion, uplifting mood, fits an East African playlist, 102 BPM, F major",["afropop","Kenyan","2010s","uplifting","harmonious"]),
  entry("af-2face-idibia","2face Idibia","af","Африканские","Afrobeats","afropop","2000s",["smooth","optimistic"],98,"D major","smooth Nigerian tenor pioneer","2000s afropop (afrobeats), smooth Nigerian tenor, English/Pidgin vocals, R&B-influenced production, optimistic mood, fits a classic Afrobeats playlist, 98 BPM, D major",["afrobeats","afropop","2000s","smooth","optimistic"],true),
  entry("af-simi","Simi","af","Африканские","Afropop","afro-soul","2010s",["tender","acoustic"],88,"G major","tender acoustic Nigerian soprano","2010s afro-soul (afropop), tender acoustic soprano, English/Yoruba vocals, guitar-led sound, intimate mood, fits a chill Afropop playlist, 88 BPM, G major",["afropop","afro-soul","2010s","tender","acoustic"]),
  entry("af-rema","Rema","af","Африканские","Afrobeats","afrorave","2010s",["youthful","hypnotic"],107,"A minor","hypnotic Gen-Z Afrorave tenor","2010s afrorave (afrobeats), hypnotic Gen-Z tenor, English/Yoruba vocals, dark melodic trap-meets-Afrobeats, youthful mood, fits a new-wave Afrobeats playlist, 107 BPM, A minor",["afrobeats","afrorave","2010s","youthful","hypnotic"]),
  entry("af-tems","Tems","af","Африканские","Afropop","afro-soul","2010s",["ethereal","powerful"],90,"C major","ethereal powerful Nigerian alto","2010s afro-soul (afropop), ethereal powerful alto, English vocals, atmospheric production, retro influences, ethereal mood, fits a soulful Afropop playlist, 90 BPM, C major",["afropop","afro-soul","2010s","ethereal","powerful"]),
  entry("af-kizz-daniel","Kizz Daniel","af","Африканские","Afrobeats","afropop","2010s",["sensual","smooth"],100,"E major","sensual smooth Nigerian tenor","2010s afropop (afrobeats), sensual smooth tenor, English/Yoruba vocals, Afrobeats groove, sensual mood, fits a vibe playlist, 100 BPM, E major",["afrobeats","afropop","2010s","sensual","smooth"]),
  entry("af-lucky-dube","Lucky Dube","af","Африканские","Reggae","South African reggae","1980s",["inspiring","spiritual"],88,"D major","deep South African reggae baritone","1980s South African reggae (reggae), deep baritone, Zulu/English vocals, roots reggae rhythm, spiritual and inspiring mood, fits a reggae classics playlist, 88 BPM, D major",["reggae","South African","1980s","inspiring","spiritual"],true),
  entry("af-yvonne-chaka-chaka","Yvonne Chaka Chaka","af","Африканские","Afropop","bubblegum / township pop","1980s",["sunny","danceable"],126,"G major","bright South African soprano","1980s bubblegum pop (afropop), bright South African soprano, Zulu/English vocals, township beats, sunny and danceable mood, fits a South African hits playlist, 126 BPM, G major",["afropop","bubblegum","1980s","sunny","danceable"]),

  // ── ITALIAN (it: 0 → 15) ──────────────────────────────────────────────────
  entry("it-andrea-bocelli","Andrea Bocelli","it","Итальянские","Classical","operatic pop / classical crossover","1990s",["majestic","romantic"],72,"D major","blind tenor with operatic timbre","1990s operatic pop (classical), blind tenor with operatic timbre, Italian-language vocals, full orchestral accompaniment, soaring legato phrases, majestic and romantic mood, fits a classical crossover playlist, 72 BPM, D major",["classical","operatic pop","1990s","majestic","romantic"],true),
  entry("it-lucio-battisti","Lucio Battisti","it","Итальянские","Pop","Italian pop / progressive","1970s",["innovative","melancholic"],110,"A minor","unique expressive Italian tenor","1970s Italian pop (pop), unique expressive Italian tenor, Italian-language vocals, acoustic guitar, innovative production, melancholic mood, fits an Italian classics playlist, 110 BPM, A minor",["pop","Italian pop","1970s","innovative","melancholic"],true),
  entry("it-zucchero","Zucchero","it","Итальянские","Rock","blues rock / Italian soul","1980s",["gritty","soulful"],112,"E minor","gritty Italian blues-rock baritone","1980s blues rock (rock), gritty Italian blues baritone, Italian-language vocals, blues guitar, Hammond organ, soulful mood, fits an Italian rock playlist, 112 BPM, E minor",["rock","blues rock","1980s","gritty","soulful"]),
  entry("it-vasco-rossi","Vasco Rossi","it","Итальянские","Rock","Italian rock","1980s",["rebellious","raw"],128,"G minor","rebellious hoarse rock baritone","1980s Italian rock (rock), rebellious hoarse baritone, Italian-language vocals, hard rock guitars, arena rock production, rebellious mood, fits an Italian rock heroes playlist, 128 BPM, G minor",["rock","Italian rock","1980s","rebellious","raw"],true),
  entry("it-laura-pausini","Laura Pausini","it","Итальянские","Pop","Italian pop","1990s",["heartfelt","soaring"],96,"C major","soaring heartfelt Italian soprano","1990s Italian pop (pop), soaring soprano, Italian/Spanish vocals, piano ballads, lush production, heartfelt mood, fits an Italian romantic playlist, 96 BPM, C major",["pop","Italian pop","1990s","heartfelt","soaring"]),
  entry("it-eros-ramazzotti","Eros Ramazzotti","it","Итальянские","Pop","Italian pop rock","1990s",["passionate","romantic"],118,"D major","passionate Italian tenor","1990s Italian pop rock (pop), passionate tenor, Italian-language vocals, guitars and orchestration, romantic mood, fits an Italian love song playlist, 118 BPM, D major",["pop","Italian pop rock","1990s","passionate","romantic"]),
  entry("it-mina","Mina","it","Итальянские","Pop","Italian pop / jazz","1960s",["dramatic","sensual"],100,"F major","legendary dramatic Italian soprano","1960s Italian pop (pop), legendary dramatic soprano, Italian-language vocals, big band, theatrical production, dramatic and sensual mood, fits a vintage Italian playlist, 100 BPM, F major",["pop","Italian pop","1960s","dramatic","sensual"],true),
  entry("it-adriano-celentano","Adriano Celentano","it","Итальянские","Pop","Italian pop / rockabilly","1960s",["charismatic","quirky"],140,"A major","charismatic Italian rock baritone","1960s Italian rockabilly (pop), charismatic baritone, Italian-language vocals, rock guitar, quirky delivery, charismatic mood, fits an Italian vintage rock playlist, 140 BPM, A major",["pop","Italian rockabilly","1960s","charismatic","quirky"],true),
  entry("it-lucio-dalla","Lucio Dalla","it","Итальянские","Pop","Italian singer-songwriter","1970s",["poetic","bittersweet"],94,"E minor","warm poetic baritone","1970s Italian singer-songwriter (pop), warm poetic baritone, Italian-language vocals, piano, gentle production, bittersweet mood, fits a Sunday morning playlist, 94 BPM, E minor",["pop","cantautore","1970s","poetic","bittersweet"]),
  entry("it-giorgia","Giorgia","it","Итальянские","Pop","Italian pop / soul","1990s",["powerful","emotional"],88,"B minor","powerhouse Italian soprano","1990s Italian pop soul (pop), powerhouse soprano, Italian-language vocals, R&B-influenced production, emotional mood, fits a diva playlist, 88 BPM, B minor",["pop","Italian pop","1990s","powerful","emotional"]),
  entry("it-franco-battiato","Franco Battiato","it","Итальянские","Pop","art pop / avant-garde","1980s",["mystical","experimental"],108,"D minor","cool mystical Italian baritone","1980s art pop (pop), cool mystical baritone, Italian-language vocals, minimalist synths, Eastern scales, experimental production, fits an art-pop playlist, 108 BPM, D minor",["pop","art pop","1980s","mystical","experimental"]),
  entry("it-tiziano-ferro","Tiziano Ferro","it","Итальянские","Pop","Italian pop / R&B","2000s",["passionate","vulnerable"],98,"G minor","passionate R&B-inflected tenor","2000s Italian pop R&B (pop), passionate tenor, Italian/Spanish vocals, pop production with R&B feel, vulnerable mood, fits a heartbreak playlist, 98 BPM, G minor",["pop","Italian pop","2000s","passionate","vulnerable"]),
  entry("it-elisa","Elisa","it","Итальянские","Pop","indie pop / Italian pop","2000s",["crystalline","dreamy"],92,"C major","crystalline indie soprano","2000s Italian indie pop (pop), crystalline indie soprano, Italian/English vocals, acoustic guitar, atmospheric production, dreamy mood, fits an introspective playlist, 92 BPM, C major",["pop","indie pop","2000s","crystalline","dreamy"]),
  entry("it-mahmood","Mahmood","it","Итальянские","Pop","Italian pop / R&B / Middle East fusion","2010s",["soulful","modern"],102,"A minor","soulful Mediterranean-pop tenor","2010s Italian pop fusion (pop), soulful modern tenor, Italian-language vocals, R&B beats with Middle Eastern scales, innovative mood, fits a contemporary Italian playlist, 102 BPM, A minor",["pop","Italian pop","2010s","soulful","modern"]),
  entry("it-pino-daniele","Pino Daniele","it","Итальянские","Rock","Neapolitan blues / Mediterranean","1980s",["warm","nostalgic"],96,"E major","warm Neapolitan guitar-singer baritone","1980s Neapolitan blues (rock), warm Neapolitan baritone, Neapolitan dialect vocals, fingerstyle guitar, Mediterranean grooves, warm and nostalgic mood, fits a Naples heritage playlist, 96 BPM, E major",["rock","Neapolitan blues","1980s","warm","nostalgic"],true),

  // ── POLISH (pl: 0 → 12) ───────────────────────────────────────────────────
  entry("pl-czeslaw-niemen","Czesław Niemen","pl","Польские","Rock","psychedelic rock / art rock","1960s",["avant-garde","visionary"],110,"D minor","theatrical visionary baritone","1960s psychedelic rock (rock), theatrical visionary baritone, Polish-language vocals, vintage organ, fuzz guitar, experimental production, avant-garde mood, fits a Polish rock legends playlist, 110 BPM, D minor",["rock","psychedelic rock","1960s","avant-garde","visionary"],true),
  entry("pl-kayah","Kayah","pl","Польские","Pop","Polish pop / jazz","1990s",["sultry","jazz-inflected"],105,"F minor","sultry jazz-inflected mezzo","1990s Polish pop jazz (pop), sultry jazz mezzo, Polish-language vocals, piano, brass, intimate production, fits a Polish jazz-pop playlist, 105 BPM, F minor",["pop","Polish pop","1990s","sultry","jazz-inflected"]),
  entry("pl-ania-dabrowska","Ania Dąbrowska","pl","Польские","Pop","Polish singer-songwriter","2000s",["heartfelt","acoustic"],88,"G major","heartfelt Polish soprano singer-songwriter","2000s Polish pop (pop), heartfelt soprano, Polish-language vocals, acoustic guitar, piano, sincere mood, fits a Polish love playlist, 88 BPM, G major",["pop","singer-songwriter","2000s","heartfelt","acoustic"]),
  entry("pl-maryla-rodowicz","Maryla Rodowicz","pl","Польские","Pop","Polish folk-pop","1970s",["vivacious","nostalgic"],120,"C major","vivacious folk-pop soprano","1970s Polish folk-pop (pop), vivacious soprano, Polish-language vocals, folk instruments, cheerful production, nostalgic mood, fits a Polish classics playlist, 120 BPM, C major",["pop","Polish folk-pop","1970s","vivacious","nostalgic"],true),
  entry("pl-feel","Feel","pl","Польские","Pop","Polish pop rock","2000s",["melodic","youthful"],125,"A major","melodic Polish pop-rock tenor","2000s Polish pop rock (pop), melodic tenor, Polish-language vocals, electric guitar, polished production, youthful mood, fits a Polish radio playlist, 125 BPM, A major",["pop","Polish pop rock","2000s","melodic","youthful"]),
  entry("pl-peja","Peja","pl","Польские","Hip-hop","Polish hip-hop","2000s",["street","intense"],95,"D minor","intense Polish street rapper","2000s Polish hip-hop (hip-hop), intense street baritone, Polish-language vocals, boom-bap production, street mood, fits a Polish rap playlist, 95 BPM, D minor",["hip-hop","Polish hip-hop","2000s","street","intense"]),
  entry("pl-goran-bregovic","Republika","pl","Польские","Rock","Polish new wave / post-punk","1980s",["cold","poetic"],118,"E minor","cold poetic new-wave baritone","1980s Polish new wave (rock), cold poetic baritone, Polish-language vocals, dark synths, angular guitar, post-punk production, fits a Polish rock classics playlist, 118 BPM, E minor",["rock","new wave","1980s","cold","poetic"]),
  entry("pl-ewa-demarczyk","Ewa Demarczyk","pl","Польские","Classical","Polish cabaret / art song","1960s",["dramatic","intense"],85,"C minor","dramatic intense dramatic mezzo","1960s Polish cabaret (classical), dramatic intense mezzo, Polish-language vocals, chamber ensemble, poetic texts, dramatic mood, fits a Polish art song playlist, 85 BPM, C minor",["classical","cabaret","1960s","dramatic","intense"],true),
  entry("pl-sanah","Sanah","pl","Польские","Pop","Polish indie pop","2010s",["dreamy","romantic"],92,"D major","dreamy romantic soprano","2010s Polish indie pop (pop), dreamy romantic soprano, Polish-language vocals, piano, string quartet, romantic mood, fits a Polish indie playlist, 92 BPM, D major",["pop","indie pop","2010s","dreamy","romantic"]),
  entry("pl-happysad","Happysad","pl","Польские","Rock","Polish acoustic rock","2000s",["melancholic","sincere"],104,"G minor","sincere melancholic baritone","2000s Polish acoustic rock (rock), sincere melancholic baritone, Polish-language vocals, acoustic guitar, emotional delivery, fits a Polish introspective playlist, 104 BPM, G minor",["rock","acoustic rock","2000s","melancholic","sincere"]),
  entry("pl-taco-hemingway","Taco Hemingway","pl","Польские","Hip-hop","Polish alternative hip-hop","2010s",["ironic","literary"],92,"F minor","ironic literary rapper","2010s Polish alt hip-hop (hip-hop), ironic literary rapper, Polish-language vocals, jazz samples, indie production, ironic and literary mood, fits a Polish intellectual playlist, 92 BPM, F minor",["hip-hop","Polish hip-hop","2010s","ironic","literary"]),
  entry("pl-doda","Doda","pl","Польские","Pop","Polish pop rock","2000s",["provocative","energetic"],132,"A minor","provocative pop-rock soprano","2000s Polish pop rock (pop), provocative energetic soprano, Polish-language vocals, rock guitars, pop production, fits a guilty pleasure playlist, 132 BPM, A minor",["pop","pop rock","2000s","provocative","energetic"]),

  // ── EXPAND KOREAN (ko: 12 → 22) ───────────────────────────────────────────
  entry("ko-bts","BTS","ko","K-Pop","Pop","K-pop / hip-hop","2010s",["energetic","emotional"],150,"B minor","seven-member vocal and rap group","2010s K-pop (pop), seven-member vocal and rap group, Korean-language vocals, complex choreography-driven production, emotional balladry and hip-hop, energetic mood, fits a K-pop megahit playlist, 150 BPM, B minor",["pop","K-pop","2010s","energetic","emotional"],true),
  entry("ko-blackpink","BLACKPINK","ko","K-Pop","Pop","K-pop / girl group","2010s",["fierce","glamorous"],133,"G minor","four-member fierce girl group","2010s K-pop (pop), fierce girl group, Korean/English vocals, YG hip-hop influenced production, trap hi-hats, glamorous and fierce mood, fits a girl power playlist, 133 BPM, G minor",["pop","K-pop","2010s","fierce","glamorous"],true),
  entry("ko-iu","IU","ko","K-Pop","Pop","K-pop / indie pop","2010s",["sweet","introspective"],112,"D major","sweet indie-tinged Korean soprano","2010s K-pop indie (pop), sweet soprano, Korean-language vocals, acoustic piano, light drums, introspective and sweet mood, fits a Korean café playlist, 112 BPM, D major",["pop","K-pop","2010s","sweet","introspective"]),
  entry("ko-shinee","SHINee","ko","K-Pop","Pop","K-pop / funk","2000s",["stylish","sophisticated"],128,"F minor","five-member sophisticated vocal group","2000s K-pop funk (pop), sophisticated vocal group, Korean-language vocals, neo-soul funk production, stylish mood, fits a K-pop classics playlist, 128 BPM, F minor",["pop","K-pop","2000s","stylish","sophisticated"]),
  entry("ko-exo","EXO","ko","K-Pop","Pop","K-pop / electropop","2010s",["powerful","polished"],140,"A minor","nine-member powerhouse group","2010s K-pop electropop (pop), powerful polished group, Korean/Mandarin vocals, heavy synth drops, epic production, fits a K-pop stadium playlist, 140 BPM, A minor",["pop","K-pop","2010s","powerful","polished"]),
  entry("ko-nct127","NCT 127","ko","K-Pop","Pop","K-pop / neo-soul","2010s",["experimental","edgy"],136,"C minor","multi-national experimental K-pop group","2010s experimental K-pop (pop), multi-national group, Korean/English vocals, genre-blending production, edgy mood, fits an alternative K-pop playlist, 136 BPM, C minor",["pop","K-pop","2010s","experimental","edgy"]),
  entry("ko-aespa","aespa","ko","K-Pop","Pop","K-pop / metaverse concept","2020s",["futuristic","intense"],138,"E minor","four-member virtual concept girl group","2020s K-pop (pop), futuristic girl group, Korean/English vocals, digital glitchy production, intense mood, fits a futuristic K-pop playlist, 138 BPM, E minor",["pop","K-pop","2020s","futuristic","intense"]),
  entry("ko-bigbang","BIGBANG","ko","K-Pop","Pop","K-pop / hip-hop","2000s",["swag","groundbreaking"],130,"G major","iconic five-member K-pop pioneers","2000s K-pop hip-hop (pop), iconic swaggering group, Korean vocals, YG hip-hop production, groundbreaking mood, fits a K-pop legends playlist, 130 BPM, G major",["pop","K-pop","2000s","swag","groundbreaking"],true),
  entry("ko-seventeen","SEVENTEEN","ko","K-Pop","Pop","K-pop / self-producing","2010s",["upbeat","self-made"],148,"D major","13-member self-producing group","2010s K-pop (pop), 13-member self-producing group, Korean vocals, performance unit/vocal/hip-hop sub-units, upbeat mood, fits a K-pop show playlist, 148 BPM, D major",["pop","K-pop","2010s","upbeat","self-made"]),
  entry("ko-got7","GOT7","ko","K-Pop","Pop","K-pop / martial arts","2010s",["charismatic","upbeat"],135,"A major","seven-member performance-focused group","2010s K-pop (pop), charismatic seven-member group, Korean/English vocals, martial arts influence, upbeat mood, fits a K-pop dance playlist, 135 BPM, A major",["pop","K-pop","2010s","charismatic","upbeat"]),

  // ── EXPAND JAPANESE (ja: 12 → 22) ─────────────────────────────────────────
  entry("ja-hikaru-utada","Hikaru Utada","ja","Японские","Pop","J-pop / R&B","1990s",["emotional","groundbreaking"],108,"A minor","smooth R&B-influenced J-pop soprano","1990s J-pop R&B (pop), smooth R&B soprano, Japanese-language vocals, digital production, orchestral flourishes, emotional and groundbreaking mood, fits a J-pop legends playlist, 108 BPM, A minor",["pop","J-pop","1990s","emotional","groundbreaking"],true),
  entry("ja-kenshi-yonezu","Kenshi Yonezu","ja","Японские","Pop","J-pop / art pop","2010s",["creative","eclectic"],125,"C major","quirky art-pop tenor","2010s J-pop art pop (pop), quirky creative tenor, Japanese-language vocals, eclectic instrumentation, catchy hooks, creative mood, fits a contemporary J-pop playlist, 125 BPM, C major",["pop","J-pop","2010s","creative","eclectic"]),
  entry("ja-babymetal","BABYMETAL","ja","Японские","Metal","kawaii metal","2010s",["aggressive","cute"],180,"E minor","three-member kawaii metal group","2010s kawaii metal (metal), kawaii girl group over thrash metal, Japanese vocals, shredding guitar, blast beats, aggressive and cute mood, fits a metal novelty playlist, 180 BPM, E minor",["metal","kawaii metal","2010s","aggressive","cute"]),
  entry("ja-aimyon","Aimyon","ja","Японские","Pop","J-pop / folk pop","2010s",["nostalgic","honest"],95,"G major","relatable acoustic soprano","2010s J-pop folk (pop), relatable acoustic soprano, Japanese-language vocals, acoustic guitar, honest delivery, nostalgic mood, fits a Japanese café playlist, 95 BPM, G major",["pop","J-pop","2010s","nostalgic","honest"]),
  entry("ja-one-ok-rock","ONE OK ROCK","ja","Японские","Rock","J-rock / alternative","2000s",["anthemic","bilingual"],140,"D major","bilingual rock tenor","2000s J-rock (rock), bilingual Japanese/English tenor, electric guitar, stadium production, anthemic mood, fits a J-rock playlist, 140 BPM, D major",["rock","J-rock","2000s","anthemic","bilingual"]),
  entry("ja-buck-tick","BUCK-TICK","ja","Японские","Rock","visual kei / gothic rock","1980s",["dark","theatrical"],118,"C minor","dramatic gothic baritone","1980s visual kei (rock), dramatic gothic baritone, Japanese vocals, dark guitar riffs, theatrical production, dark mood, fits a Japanese gothic playlist, 118 BPM, C minor",["rock","visual kei","1980s","dark","theatrical"]),
  entry("ja-king-gnu","King Gnu","ja","Японские","Pop","J-pop / art rock","2010s",["complex","eclectic"],132,"F minor","dual vocal art-rock group","2010s J-pop art rock (pop), dual vocals (high/low contrast), Japanese vocals, jazz-influenced rhythms, complex production, fits an alternative J-pop playlist, 132 BPM, F minor",["pop","J-pop","2010s","complex","eclectic"]),
  entry("ja-fujii-kaze","Fujii Kaze","ja","Японские","Pop","J-pop / soul","2010s",["soulful","laid-back"],100,"E-flat major","soulful laid-back baritone","2010s J-pop soul (pop), soulful laid-back baritone, Japanese-language vocals, piano, gospel influences, soulful mood, fits a feel-good J-pop playlist, 100 BPM, E-flat major",["pop","J-pop","2010s","soulful","laid-back"]),
  entry("ja-ado","Ado","ja","Японские","Pop","J-pop / anime","2020s",["powerful","versatile"],130,"G minor","powerful versatile soprano","2020s J-pop (pop), powerful versatile soprano, Japanese vocals, electronic production, emotional range, fits an anime soundtrack playlist, 130 BPM, G minor",["pop","J-pop","2020s","powerful","versatile"]),
  entry("ja-eve","Eve","ja","Японские","Pop","J-pop / vocaloid aesthetic","2010s",["atmospheric","indie"],118,"D minor","atmospheric indie-net tenor","2010s J-pop indie net (pop), atmospheric indie tenor, Japanese vocals, dark synth textures, vocaloid-era aesthetic, fits a Japanese underground playlist, 118 BPM, D minor",["pop","J-pop","2010s","atmospheric","indie"]),

  // ── EXPAND SPANISH (es: 12 → 25) ──────────────────────────────────────────
  entry("es-bad-bunny","Bad Bunny","es","Испанские","Hip-hop","reggaeton / trap Latino","2010s",["assertive","versatile"],95,"F minor","low husky reggaeton baritone","2010s reggaeton trap (hip-hop), low husky reggaeton baritone, Spanish-language vocals, dembow rhythm, 808s, Latin urban beat, assertive and versatile mood, fits a Latin trap playlist, 95 BPM, F minor",["hip-hop","reggaeton","2010s","assertive","versatile"],true),
  entry("es-j-balvin","J Balvin","es","Испанские","Hip-hop","reggaeton / urban Latino","2010s",["smooth","danceable"],98,"G minor","smooth Colombian reggaeton tenor","2010s reggaeton (hip-hop), smooth Colombian tenor, Spanish-language vocals, dembow, electronic textures, smooth and danceable mood, fits a Latin dance playlist, 98 BPM, G minor",["hip-hop","reggaeton","2010s","smooth","danceable"]),
  entry("es-daddy-yankee","Daddy Yankee","es","Испанские","Hip-hop","reggaeton (pioneer)","2000s",["energetic","driving"],100,"D minor","explosive Puerto Rican reggaeton pioneer","2000s reggaeton (hip-hop), explosive pioneer baritone, Spanish-language vocals, classic dembow, energetic mood, fits a throwback Latin playlist, 100 BPM, D minor",["hip-hop","reggaeton","2000s","energetic","driving"],true),
  entry("es-enrique-iglesias","Enrique Iglesias","es","Испанские","Pop","Latin pop","1990s",["romantic","passionate"],118,"A major","Spanish romantic pop tenor","1990s Latin pop (pop), romantic tenor, Spanish/English vocals, guitar, melodic production, passionate mood, fits a Latin love song playlist, 118 BPM, A major",["pop","Latin pop","1990s","romantic","passionate"]),
  entry("es-maluma","Maluma","es","Испанские","Hip-hop","reggaeton / urban","2010s",["suave","party"],96,"C minor","suave Colombian baritone","2010s reggaeton (hip-hop), suave Colombian baritone, Spanish-language vocals, urban beats, party mood, fits a Latin hits playlist, 96 BPM, C minor",["hip-hop","reggaeton","2010s","suave","party"]),
  entry("es-alejandro-sanz","Alejandro Sanz","es","Испанские","Pop","Spanish pop / flamenco pop","1990s",["passionate","tender"],94,"E major","passionate flamenco-pop tenor","1990s Spanish pop (pop), passionate tenor, Spanish vocals, flamenco guitar, orchestration, passionate and tender mood, fits a Spanish romantic playlist, 94 BPM, E major",["pop","flamenco pop","1990s","passionate","tender"]),
  entry("es-ozuna","Ozuna","es","Испанские","Hip-hop","reggaeton / Latin trap","2010s",["melodic","romantic"],94,"F minor","melodic reggaeton baritone","2010s reggaeton trap (hip-hop), melodic baritone, Spanish vocals, dembow, romantic mood, fits a Latin nights playlist, 94 BPM, F minor",["hip-hop","reggaeton","2010s","melodic","romantic"]),
  entry("es-celia-cruz","Celia Cruz","es","Испанские","Salsa","Cuban salsa / tropical","1960s",["joyful","vivacious"],196,"C major","the Queen of Salsa — powerful alto shout","1960s Cuban salsa (salsa), powerful alto shout, Spanish vocals, live brass, Cuban percussion, conga, timbales, joyful and vivacious mood, fits a salsa dance playlist, 196 BPM, C major",["salsa","Cuban","1960s","joyful","vivacious"],true),
  entry("es-juanes","Juanes","es","Испанские","Rock","Latin rock","2000s",["passionate","political"],120,"A minor","passionate Colombian rock tenor","2000s Latin rock (rock), passionate rock tenor, Spanish vocals, electric guitar, political lyrics, passionate mood, fits a Latin rock playlist, 120 BPM, A minor",["rock","Latin rock","2000s","passionate","political"]),
  entry("es-marc-anthony","Marc Anthony","es","Испанские","Salsa","salsa / tropical","1990s",["passionate","powerful"],112,"D minor","New York salsa powerhouse tenor","1990s salsa (salsa), powerful New York tenor, Spanish vocals, live horns, timbales, passionate mood, fits a tropical salsa playlist, 112 BPM, D minor",["salsa","tropical","1990s","passionate","powerful"]),
  entry("es-pablo-alboran","Pablo Alborán","es","Испанские","Pop","Spanish pop","2010s",["tender","artistic"],90,"E minor","tender Málaga tenor singer-songwriter","2010s Spanish pop (pop), tender tenor, Spanish vocals, guitar and piano, artistic mood, fits a Spanish romantic playlist, 90 BPM, E minor",["pop","Spanish pop","2010s","tender","artistic"]),
  entry("es-residente","Residente","es","Испанские","Hip-hop","Latin hip-hop / art rap","2000s",["intellectual","rebellious"],90,"G minor","cerebral Puerto Rican rapper","2000s Latin hip-hop (hip-hop), cerebral Puerto Rican rapper, Spanish vocals, experimental production, intellectual and rebellious mood, fits a Latin alternative playlist, 90 BPM, G minor",["hip-hop","Latin hip-hop","2000s","intellectual","rebellious"]),
  entry("es-bunbury","Enrique Bunbury","es","Испанские","Rock","Spanish rock / post-punk","1990s",["charismatic","dark"],120,"E minor","charismatic Spanish dark-rock baritone","1990s Spanish rock (rock), charismatic dark baritone, Spanish vocals, post-punk energy, theatrical delivery, dark mood, fits a Spanish alt-rock playlist, 120 BPM, E minor",["rock","Spanish rock","1990s","charismatic","dark"]),

  // ── EXPAND PORTUGUESE (pt: 12 → 22) ───────────────────────────────────────
  entry("pt-anitta","Anitta","pt","Португальские","Pop","Brazilian funk / baile funk","2010s",["sensual","party"],128,"F major","fierce sensual carioca soprano","2010s baile funk (pop), fierce sensual soprano, Portuguese vocals, heavy bass, Rio funk beat, party mood, fits a Brazilian funk playlist, 128 BPM, F major",["pop","baile funk","2010s","sensual","party"],true),
  entry("pt-mc-hariel","MC Hariel","pt","Португальские","Hip-hop","Brazilian funk / trap","2010s",["street","intense"],140,"C minor","intense Brazilian trap rapper","2010s Brazilian trap (hip-hop), intense Brazilian rapper, Portuguese vocals, 808s, funk carioca elements, street mood, fits a Brazilian hip-hop playlist, 140 BPM, C minor",["hip-hop","Brazilian funk","2010s","street","intense"]),
  entry("pt-caetano-veloso","Caetano Veloso","pt","Португальские","Pop","tropicália / MPB","1960s",["poetic","innovative"],90,"E major","lyrical poetic baritone","1960s tropicália (pop), lyrical poetic baritone, Portuguese vocals, acoustic guitar, innovative composition, poetic mood, fits a Brazilian classics playlist, 90 BPM, E major",["pop","tropicália","1960s","poetic","innovative"],true),
  entry("pt-gilberto-gil","Gilberto Gil","pt","Португальские","Pop","tropicália / reggae","1970s",["joyful","spiritual"],96,"G major","warm philosophical baritone","1970s tropicália (pop), warm philosophical baritone, Portuguese vocals, guitar, reggae influence, joyful and spiritual mood, fits a Brazilian summer playlist, 96 BPM, G major",["pop","tropicália","1970s","joyful","spiritual"],true),
  entry("pt-ludmilla","Ludmilla","pt","Португальские","Pop","funk carioca / pagode baiano","2010s",["powerful","danceable"],132,"A minor","powerful Brazilian diva soprano","2010s funk carioca (pop), powerful soprano, Portuguese vocals, intense bass, Brazilian beat, danceable mood, fits a favela funk playlist, 132 BPM, A minor",["pop","funk carioca","2010s","powerful","danceable"]),
  entry("pt-ivete-sangalo","Ivete Sangalo","pt","Португальские","Pop","axé / MPB","1990s",["exuberant","festive"],148,"D major","exuberant Bahian carnival soprano","1990s axé (pop), exuberant Bahian soprano, Portuguese vocals, percussive axé rhythm, brass, festive mood, fits a carnival playlist, 148 BPM, D major",["pop","axé","1990s","exuberant","festive"]),
  entry("pt-elis-regina","Elis Regina","pt","Португальские","Pop","MPB / jazz","1960s",["intense","interpretive"],102,"F minor","legendary interpretive MPB alto","1960s MPB (pop), legendary interpretive alto, Portuguese vocals, jazz piano, live band, intense and expressive mood, fits a Brazilian jazz playlist, 102 BPM, F minor",["pop","MPB","1960s","intense","interpretive"],true),
  entry("pt-ze-ramalho","Zé Ramalho","pt","Португальские","Rock","Brazilian rock / northeastern","1970s",["poetic","mystical"],104,"E minor","mystical northeastern rock baritone","1970s Brazilian rock (rock), mystical baritone, Portuguese vocals, electric guitar, northeastern folk elements, poetic mood, fits a Brazilian alternative playlist, 104 BPM, E minor",["rock","Brazilian rock","1970s","poetic","mystical"]),
  entry("pt-legiao-urbana","Legião Urbana","pt","Португальские","Rock","Brazilian post-punk","1980s",["existential","anthemic"],130,"G minor","existential post-punk baritone","1980s Brazilian post-punk (rock), existential baritone, Portuguese vocals, post-punk guitars, anthemic mood, fits a Brazilian rock legends playlist, 130 BPM, G minor",["rock","Brazilian post-punk","1980s","existential","anthemic"],true),
  entry("pt-sandy","Sandy","pt","Португальские","Pop","Brazilian pop","2000s",["sweet","sincere"],105,"C major","sweet sincere Brazilian soprano","2000s Brazilian pop (pop), sweet sincere soprano, Portuguese vocals, pop production, warm mood, fits a Brazilian family playlist, 105 BPM, C major",["pop","Brazilian pop","2000s","sweet","sincere"]),

  // ── EXPAND FRENCH (fr: 13 → 23) ───────────────────────────────────────────
  entry("fr-daft-punk-fr","Air","fr","Французские","Electronic","French electronic / space rock","1990s",["cosmic","laid-back"],98,"D major","ethereal vocoder tenor","1990s French electronic (electronic), ethereal vocoder tenor, French vocals, Moog synthesizers, cosmic laid-back mood, fits an ambient electronic playlist, 98 BPM, D major",["electronic","French electronic","1990s","cosmic","laid-back"]),
  entry("fr-edith-piaf","Édith Piaf","fr","Французские","Pop","French chanson","1940s",["tragic","passionate"],88,"A minor","legendary tragic soprano chanteuse","1940s French chanson (pop), legendary tragic soprano, French vocals, accordion, strings, deeply emotional, passionate mood, fits a classic French playlist, 88 BPM, A minor",["pop","chanson","1940s","tragic","passionate"],true),
  entry("fr-charles-aznavour","Charles Aznavour","fr","Французские","Pop","French chanson","1950s",["bittersweet","intimate"],100,"G major","intimate warm baritone chansonnier","1950s French chanson (pop), intimate warm baritone, French vocals, gentle orchestration, bittersweet mood, fits a classic French café playlist, 100 BPM, G major",["pop","chanson","1950s","bittersweet","intimate"],true),
  entry("fr-aya-nakamura","Aya Nakamura","fr","Французские","Pop","afropop / dancehall French","2010s",["catchy","danceable"],108,"G minor","catchy French-afropop soprano","2010s afropop French (pop), catchy soprano, French vocals, dancehall beat, Afropop production, fits a French urban playlist, 108 BPM, G minor",["pop","afropop","2010s","catchy","danceable"]),
  entry("fr-mc-solaar","MC Solaar","fr","Французские","Hip-hop","French hip-hop","1990s",["witty","jazz"],94,"E minor","witty jazz-inflected French rapper","1990s French hip-hop (hip-hop), witty jazz rapper, French vocals, jazz samples, wordplay, witty mood, fits a French rap classics playlist, 94 BPM, E minor",["hip-hop","French hip-hop","1990s","witty","jazz"]),
  entry("fr-indochine","Indochine","fr","Французские","Rock","French new wave / synth-pop","1980s",["melancholic","romantic"],130,"C minor","dramatic new-wave baritone","1980s French new wave (rock), dramatic baritone, French vocals, synth-driven guitars, romantic and melancholic mood, fits a French 80s playlist, 130 BPM, C minor",["rock","new wave","1980s","melancholic","romantic"]),
  entry("fr-nekfeu","Nekfeu","fr","Французские","Hip-hop","French hip-hop / cloud rap","2010s",["introspective","lyrical"],92,"F minor","introspective lyrical French rapper","2010s French hip-hop (hip-hop), introspective lyrical rapper, French vocals, atmospheric beats, introspective mood, fits a French rap playlist, 92 BPM, F minor",["hip-hop","French hip-hop","2010s","introspective","lyrical"]),
  entry("fr-mylene-farmer","Mylène Farmer","fr","Французские","Pop","French synth-pop","1980s",["provocative","theatrical"],118,"D minor","theatrical provocative mezzo","1980s French synth-pop (pop), theatrical provocative mezzo, French vocals, dark synths, cinematic production, provocative mood, fits a French diva playlist, 118 BPM, D minor",["pop","synth-pop","1980s","provocative","theatrical"],true),
  entry("fr-orelsan","Orelsan","fr","Французские","Hip-hop","French rap / slam","2000s",["street","ironic"],88,"G minor","street-ironic French rapper","2000s French rap (hip-hop), street ironic baritone, French vocals, minimalist beats, ironic delivery, fits a French underground playlist, 88 BPM, G minor",["hip-hop","French rap","2000s","street","ironic"]),
  entry("fr-louane","Louane","fr","Французские","Pop","French pop","2010s",["tender","youthful"],95,"E major","tender youthful soprano","2010s French pop (pop), tender soprano, French vocals, piano, light production, youthful and touching mood, fits a French indie playlist, 95 BPM, E major",["pop","French pop","2010s","tender","youthful"]),

  // ── EXPAND GERMAN (de: 12 → 22) ───────────────────────────────────────────
  entry("de-rammstein","Rammstein","de","Немецкие","Metal","Neue Deutsche Härte","1990s",["heavy","industrial"],138,"E minor","deep authoritative German baritone","1990s Neue Deutsche Härte (metal), deep authoritative baritone, German-language vocals, distorted power riffs, industrial percussion, heavy mood, fits a metal playlist, 138 BPM, E minor",["metal","Neue Deutsche Härte","1990s","heavy","industrial"],true),
  entry("de-kraftwerk","Kraftwerk","de","Немецкие","Electronic","electronic / synth-pop","1970s",["robotic","futuristic"],126,"C minor","robotic vocoder vocals","1970s electronic (electronic), robotic vocoder vocal, German vocals, analog synthesizers, sequencer-driven, futuristic and minimal mood, fits an electronic pioneers playlist, 126 BPM, C minor",["electronic","synth-pop","1970s","robotic","futuristic"],true),
  entry("de-nena","Nena","de","Немецкие","Pop","Neue Deutsche Welle / synth-pop","1980s",["bubbly","iconic"],132,"G major","bubbly iconic German pop soprano","1980s Neue Deutsche Welle (pop), bubbly soprano, German vocals, synth-pop, catchy hooks, iconic mood, fits a 80s German pop playlist, 132 BPM, G major",["pop","Neue Deutsche Welle","1980s","bubbly","iconic"],true),
  entry("de-xavier-naidoo","Xavier Naidoo","de","Немецкие","Soul","German soul / R&B","1990s",["soulful","spiritual"],92,"D minor","soulful German gospel-soul baritone","1990s German soul (soul), soulful gospel baritone, German vocals, R&B production, spiritual and warm mood, fits a German soul playlist, 92 BPM, D minor",["soul","German soul","1990s","soulful","spiritual"]),
  entry("de-peter-maffay","Peter Maffay","de","Немецкие","Rock","German rock","1970s",["strong","classic"],118,"A major","strong classic German rock baritone","1970s German rock (rock), strong rock baritone, German vocals, rock guitar, classic mood, fits a German rock playlist, 118 BPM, A major",["rock","German rock","1970s","strong","classic"]),
  entry("de-mark-forster","Mark Forster","de","Немецкие","Pop","German indie pop","2010s",["catchy","feel-good"],120,"C major","catchy indie pop tenor","2010s German indie pop (pop), catchy tenor, German vocals, indie production, feel-good mood, fits a German radio playlist, 120 BPM, C major",["pop","indie pop","2010s","catchy","feel-good"]),
  entry("de-coldmirror","Cro","de","Немецкие","Hip-hop","German rap / cloud rap","2010s",["laid-back","quirky"],95,"F major","laid-back mask-wearing German rapper","2010s German cloud rap (hip-hop), laid-back rapper, German vocals, indie-rap production, quirky mood, fits a German hip-hop playlist, 95 BPM, F major",["hip-hop","German rap","2010s","laid-back","quirky"]),
  entry("de-namika","Namika","de","Немецкие","Pop","German pop / French-Arabic fusion","2010s",["warm","urban"],108,"E minor","warm multicultural German soprano","2010s German pop (pop), warm multicultural soprano, German/French vocals, acoustic pop, urban mood, fits a German modern pop playlist, 108 BPM, E minor",["pop","German pop","2010s","warm","urban"]),
  entry("de-been-stallone","Capital Bra","de","Немецкие","Hip-hop","German trap / drill","2010s",["street","catchy"],140,"C minor","prolific German trap rapper","2010s German trap (hip-hop), prolific trap rapper, German vocals, trap beats, street catchy mood, fits a German street playlist, 140 BPM, C minor",["hip-hop","German trap","2010s","street","catchy"]),
  entry("de-sarah-connor","Sarah Connor","de","Немецкие","Pop","German R&B pop","2000s",["soulful","emotional"],98,"G minor","soulful emotional German soprano","2000s German R&B pop (pop), soulful soprano, German/English vocals, R&B production, emotional mood, fits a German pop hits playlist, 98 BPM, G minor",["pop","German pop","2000s","soulful","emotional"]),

  // ── EXPAND TURKISH (tr: 10 → 18) ──────────────────────────────────────────
  entry("tr-duman","Duman","tr","Турецкие","Rock","Turkish rock / alternative","2000s",["melancholic","edgy"],120,"A minor","melancholic Turkish rock baritone","2000s Turkish rock (rock), melancholic baritone, Turkish vocals, alternative guitar, edgy mood, fits a Turkish alt-rock playlist, 120 BPM, A minor",["rock","Turkish rock","2000s","melancholic","edgy"]),
  entry("tr-mor-ve-otesi","Mor ve Ötesi","tr","Турецкие","Rock","Turkish rock","2000s",["energetic","youthful"],132,"E minor","energetic Turkish rock tenor","2000s Turkish rock (rock), energetic tenor, Turkish vocals, guitar-driven, youthful mood, fits a Turkish rock playlist, 132 BPM, E minor",["rock","Turkish rock","2000s","energetic","youthful"]),
  entry("tr-sagopa-kajmer","Sagopa Kajmer","tr","Турецкие","Hip-hop","Turkish hip-hop / lyrical","2000s",["introspective","poetic"],90,"D minor","introspective Turkish lyrical rapper","2000s Turkish hip-hop (hip-hop), introspective lyrical rapper, Turkish vocals, soul samples, poetic mood, fits a Turkish rap playlist, 90 BPM, D minor",["hip-hop","Turkish hip-hop","2000s","introspective","poetic"]),
  entry("tr-gulsen","Gülşen","tr","Турецкие","Pop","Turkish pop","2000s",["energetic","glamorous"],120,"F major","energetic glamorous Turkish soprano","2000s Turkish pop (pop), energetic soprano, Turkish vocals, pop production, glamorous mood, fits a Turkish hits playlist, 120 BPM, F major",["pop","Turkish pop","2000s","energetic","glamorous"]),
  entry("tr-ceza","Ceza","tr","Турецкие","Hip-hop","Turkish hip-hop / speed rap","2000s",["rapid-fire","intense"],148,"C minor","fastest Turkish rapper baritone","2000s Turkish hip-hop (hip-hop), rapid-fire baritone, Turkish vocals, intense beats, intense mood, fits a Turkish battle rap playlist, 148 BPM, C minor",["hip-hop","Turkish hip-hop","2000s","rapid-fire","intense"]),
  entry("tr-ajda-pekkan","Ajda Pekkan","tr","Турецкие","Pop","Turkish pop / eurodisco","1970s",["glamorous","iconic"],126,"G major","glamorous Turkish disco diva soprano","1970s Turkish eurodisco (pop), glamorous soprano, Turkish vocals, disco production, iconic mood, fits a Turkish classics playlist, 126 BPM, G major",["pop","Turkish pop","1970s","glamorous","iconic"],true),
  entry("tr-haluk-levent","Haluk Levent","tr","Турецкие","Rock","Turkish rock / folk rock","1990s",["sincere","raw"],114,"E major","sincere folk-rock baritone","1990s Turkish folk rock (rock), sincere baritone, Turkish vocals, folk and electric guitar, raw mood, fits a Turkish folk-rock playlist, 114 BPM, E major",["rock","Turkish folk rock","1990s","sincere","raw"]),
  entry("tr-izel","İzel","tr","Турецкие","Pop","Turkish pop","1990s",["sweet","nostalgic"],112,"D major","sweet nostalgic Turkish soprano","1990s Turkish pop (pop), sweet soprano, Turkish vocals, pop production, nostalgic mood, fits a 90s Turkish playlist, 112 BPM, D major",["pop","Turkish pop","1990s","sweet","nostalgic"]),

  // ── EXPAND UKRAINIAN (uk: 14 → 22) ────────────────────────────────────────
  entry("uk-okean-elzy","Океан Ельзи","uk","Украинские","Rock","Ukrainian rock","1990s",["anthemic","passionate"],130,"B minor","passionate Ukrainian rock tenor","1990s Ukrainian rock (rock), passionate tenor, Ukrainian vocals, electric guitar, anthemic production, fits a Ukrainian rock playlist, 130 BPM, B minor",["rock","Ukrainian rock","1990s","anthemic","passionate"],true),
  entry("uk-dakh-daughters","Dakh Daughters","uk","Украинские","Experimental","Ukrainian avant-garde / cabaret","2010s",["provocative","theatrical"],90,"D minor","multi-voice theatrical collective","2010s Ukrainian avant-garde (experimental), theatrical multi-voice, Ukrainian vocals, cabaret styling, dark and provocative mood, fits an experimental European playlist, 90 BPM, D minor",["experimental","avant-garde","2010s","provocative","theatrical"]),
  entry("uk-go-a","Go_A","uk","Украинские","Electronic","Ukrainian folk-electronic","2010s",["hypnotic","ethnic"],128,"E minor","haunting folk-electronic soprano","2010s Ukrainian folk-electronic (electronic), haunting ethnic soprano, Ukrainian vocals, electronic beats with folk motifs, hypnotic mood, fits a Ukrainian electronic playlist, 128 BPM, E minor",["electronic","folk-electronic","2010s","hypnotic","ethnic"]),
  entry("uk-antytila","Антитіла","uk","Украинские","Rock","Ukrainian indie rock","2010s",["anthemic","uplifting"],132,"G major","uplifting Ukrainian indie rock tenor","2010s Ukrainian indie rock (rock), uplifting tenor, Ukrainian vocals, catchy guitar riffs, anthemic mood, fits a modern Ukrainian rock playlist, 132 BPM, G major",["rock","Ukrainian indie rock","2010s","anthemic","uplifting"]),
  entry("uk-alyona-alyona","alyona alyona","uk","Украинские","Hip-hop","Ukrainian hip-hop","2010s",["empowering","fresh"],100,"C minor","empowering Ukrainian female rapper","2010s Ukrainian hip-hop (hip-hop), empowering female rapper, Ukrainian vocals, modern trap beats, fresh and empowering mood, fits a Ukrainian hip-hop playlist, 100 BPM, C minor",["hip-hop","Ukrainian hip-hop","2010s","empowering","fresh"]),
  entry("uk-jamala","Джамала","uk","Украинские","Pop","Ukrainian pop / soul","2010s",["powerful","emotional"],90,"D minor","powerful Ukrainian soprano with Crimean Tatar roots","2010s Ukrainian pop soul (pop), powerful soprano, Ukrainian/Crimean Tatar vocals, emotional and political delivery, fits an Eastern European playlist, 90 BPM, D minor",["pop","Ukrainian pop","2010s","powerful","emotional"],true),
  entry("uk-bez-obmezhen","Без Обмежень","uk","Украинские","Pop","Ukrainian pop / dance","2000s",["danceable","urban"],128,"F major","danceable urban Ukrainian pop","2000s Ukrainian dance pop (pop), urban pop, Ukrainian vocals, electronic beats, danceable mood, fits a Ukrainian club playlist, 128 BPM, F major",["pop","Ukrainian pop","2000s","danceable","urban"]),
  entry("uk-kalush","Kalush Orchestra","uk","Украинские","Hip-hop","Ukrainian hip-hop / folk","2020s",["innovative","ethnic"],140,"G minor","hip-hop group blending Ukrainian folk flute","2020s Ukrainian folk hip-hop (hip-hop), innovative ethnic rap, Ukrainian vocals, sopilka flute, hip-hop beats, ethnic and innovative mood, fits a Eurovision culture playlist, 140 BPM, G minor",["hip-hop","Ukrainian folk","2020s","innovative","ethnic"],true),

  // ── EXPAND INDIAN (in: 12 → 22) ───────────────────────────────────────────
  entry("in-ar-rahman","A.R. Rahman","in","Индийские","Soundtrack","Indian film score / fusion","1990s",["spiritual","cinematic"],104,"Raag Bhairavi","transcendent Sufi-film composer","1990s Indian film score (soundtrack), transcendent composer vocals / chorus, Hindi vocals, orchestral Indian fusion, qawwali influence, spiritual and cinematic mood, fits a Bollywood epic playlist, 104 BPM, Raag Bhairavi",["soundtrack","Indian film","1990s","spiritual","cinematic"],true),
  entry("in-lata-mangeshkar","Lata Mangeshkar","in","Индийские","Classical","Bollywood playback singing","1950s",["divine","melancholic"],80,"Raag Yaman","nightingale of India — pure crystalline soprano","1950s Bollywood playback (classical), divine crystalline soprano, Hindi vocals, classical ragas, orchestral arrangements, melancholic and divine mood, fits a Hindi classics playlist, 80 BPM, Raag Yaman",["classical","Bollywood","1950s","divine","melancholic"],true),
  entry("in-kishore-kumar","Kishore Kumar","in","Индийские","Pop","Bollywood playback / comedy","1960s",["versatile","joyful"],120,"Raag Khamaj","the most versatile Bollywood playback tenor","1960s Bollywood playback (pop), versatile expressive tenor, Hindi vocals, filmi orchestration, comedic and joyful mood, fits a classic Hindi film playlist, 120 BPM, Raag Khamaj",["pop","Bollywood","1960s","versatile","joyful"],true),
  entry("in-arijit-singh","Arijit Singh","in","Индийские","Pop","contemporary Bollywood","2010s",["emotional","romantic"],88,"D minor","soul-baring Bollywood tenor","2010s contemporary Bollywood (pop), soul-baring tenor, Hindi vocals, acoustic guitar, lush string arrangements, emotional and romantic mood, fits a Bollywood romance playlist, 88 BPM, D minor",["pop","Bollywood","2010s","emotional","romantic"],true),
  entry("in-asha-bhosle","Asha Bhosle","in","Индийские","Pop","Bollywood playback / ghazal","1960s",["flirtatious","playful"],116,"Raag Pahadi","the queen of Bollywood moods — playful mezzo","1960s Bollywood playback (pop), playful flirtatious mezzo, Hindi vocals, folk-film mix, diverse stylistic range, fits a Bollywood variety playlist, 116 BPM, Raag Pahadi",["pop","Bollywood","1960s","flirtatious","playful"],true),
  entry("in-zakir-hussain","Zakir Hussain","in","Индийские","Classical","Hindustani classical / tabla","1970s",["meditative","virtuosic"],90,"Teentaal","tabla virtuoso — percussive maestro","1970s Hindustani classical (classical), tabla-led instrumental, no vocals, intricate Hindustani percussion, meditative and virtuosic mood, fits a world classical playlist, 90 BPM, Teentaal",["classical","Hindustani","1970s","meditative","virtuosic"]),
  entry("in-sunidhi-chauhan","Sunidhi Chauhan","in","Индийские","Pop","contemporary Bollywood","2000s",["powerful","upbeat"],120,"F major","powerful upbeat Bollywood soprano","2000s contemporary Bollywood (pop), powerful soprano, Hindi vocals, electronic Bollywood production, upbeat mood, fits a Bollywood dance playlist, 120 BPM, F major",["pop","Bollywood","2000s","powerful","upbeat"]),
  entry("in-diljit-dosanjh","Diljit Dosanjh","in","Индийские","Pop","Punjabi pop / bhangra","2010s",["festive","joyful"],130,"G major","joyful Punjabi pop baritone","2010s Punjabi pop (pop), joyful baritone, Punjabi vocals, dhol drums, bhangra beats, festive mood, fits a Punjabi wedding playlist, 130 BPM, G major",["pop","Punjabi pop","2010s","festive","joyful"]),
  entry("in-ustad-nusrat","Nusrat Fateh Ali Khan","in","Индийские","Classical","qawwali / Sufi music","1980s",["transcendent","ecstatic"],100,"Raag Bhairav","the greatest qawwali voice — soaring tenor","1980s qawwali (classical), the greatest qawwali tenor, Urdu/Punjabi vocals, harmonium, tabla, handclaps, transcendent and ecstatic mood, fits a Sufi devotional playlist, 100 BPM, Raag Bhairav",["classical","qawwali","1980s","transcendent","ecstatic"],true),
  entry("in-ap-dhillon","AP Dhillon","in","Индийские","Pop","Punjabi pop / R&B","2020s",["cool","romantic"],94,"D minor","cool Punjabi R&B baritone","2020s Punjabi R&B (pop), cool romantic baritone, Punjabi/English vocals, western R&B production with Punjabi flair, fits a global Punjabi playlist, 94 BPM, D minor",["pop","Punjabi pop","2020s","cool","romantic"]),
];

// filter out duplicates
const toAdd = newEntries.filter(e => !existingNames.has(e.name.toLowerCase()));
const combined = [...existing, ...toAdd];

await writeFile(dataPath, JSON.stringify(combined, null, 2), "utf8");
console.log(`Added ${toAdd.length} entries. Total: ${combined.length}`);
if (toAdd.length < newEntries.length) {
  const skipped = newEntries.filter(e => existingNames.has(e.name.toLowerCase())).map(e => e.name);
  console.log("Skipped (already exist):", skipped.join(", "));
}
