import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "data", "artists.json");

const existing = JSON.parse(await readFile(dataPath, "utf8"));
const existingNames = new Set(existing.map(a => a.name.toLowerCase()));

const E = (id, name, language, languageLabel, genre, subgenre, era, mood, bpm, key, vocals, prompt, tags, free = false, isNew = true) =>
  ({ id, name, language, languageLabel, genre, subgenre, era, mood, bpm, key, vocals, prompt, tags, free, isNew });

const newEntries = [

  // ── ENGLISH expand (en: 58 → 90) ──────────────────────────────────────────
  E("en-ariana-grande","Ariana Grande","en","Зарубежные","Pop","pop / R&B","2010s",["sultry","airy"],110,"A minor","whistle-register pop soprano","2010s pop R&B (pop), whistle-register pop soprano, English-language vocals, trap-influenced beats, glossy production, sultry and airy mood, fits a pop diva playlist, 110 BPM, A minor",["pop","R&B","2010s","sultry","airy"]),
  E("en-bruno-mars","Bruno Mars","en","Зарубежные","Pop","retro pop / funk","2010s",["smooth","fun"],115,"D minor","smooth retro-soul tenor","2010s retro pop (pop), smooth retro-soul tenor, English-language vocals, funk bass, brass stabs, slick production, smooth and fun mood, fits a feel-good playlist, 115 BPM, D minor",["pop","funk","2010s","smooth","fun"]),
  E("en-justin-bieber","Justin Bieber","en","Зарубежные","Pop","pop / R&B","2010s",["catchy","romantic"],100,"E-flat major","silky pop tenor","2010s pop (pop), silky pop tenor, English-language vocals, R&B-tinged production, catchy hooks, romantic mood, fits a modern pop playlist, 100 BPM, E-flat major",["pop","R&B","2010s","catchy","romantic"]),
  E("en-shawn-mendes","Shawn Mendes","en","Зарубежные","Pop","acoustic pop","2010s",["earnest","warm"],112,"G major","earnest acoustic-pop tenor","2010s acoustic pop (pop), earnest tenor, English-language vocals, acoustic guitar, polished production, warm mood, fits a singer-songwriter pop playlist, 112 BPM, G major",["pop","acoustic pop","2010s","earnest","warm"]),
  E("en-sam-smith","Sam Smith","en","Зарубежные","Pop","soul-pop","2010s",["heartbreak","soulful"],84,"D minor","gospel-trained falsetto","2010s soul-pop (pop), gospel-trained falsetto, English-language vocals, piano-led ballads, gospel choir, heartbreak and soulful mood, fits a tearjerker playlist, 84 BPM, D minor",["pop","soul-pop","2010s","heartbreak","soulful"]),
  E("en-michael-jackson","Michael Jackson","en","Зарубежные","Pop","pop / funk / R&B","1980s",["iconic","energetic"],117,"F-sharp minor","high-register pop tenor with signature hiccups","1980s pop funk (pop), high-register pop tenor, English-language vocals, funk bass, gated reverb drums, lush production, iconic and energetic mood, fits a King of Pop playlist, 117 BPM, F-sharp minor",["pop","funk","R&B","1980s","iconic","energetic"],true),
  E("en-prince","Prince","en","Зарубежные","Funk","funk rock / R&B","1980s",["sensual","virtuosic"],112,"B-flat minor","gender-bending falsetto-baritone genius","1980s funk rock (funk), virtuosic falsetto-baritone, English-language vocals, funk guitar, synths, drum machine, sensual and virtuosic mood, fits a funk rock playlist, 112 BPM, B-flat minor",["funk","funk rock","R&B","1980s","sensual","virtuosic"],true),
  E("en-stevie-wonder","Stevie Wonder","en","Зарубежные","Soul","soul / funk","1970s",["joyful","masterful"],105,"E-flat major","soulful gospel-trained tenor with vibrato","1970s soul funk (soul), soulful tenor, English-language vocals, clavinet, harmonica, layered keyboards, joyful and masterful mood, fits a Motown soul playlist, 105 BPM, E-flat major",["soul","funk","1970s","joyful","masterful"],true),
  E("en-john-lennon","John Lennon","en","Зарубежные","Rock","classic rock / singer-songwriter","1970s",["pacifist","introspective"],100,"C major","nasal Liverpudlian tenor","1970s singer-songwriter (rock), nasal Liverpudlian tenor, English-language vocals, piano, acoustic guitar, simple arrangements, pacifist and introspective mood, fits a classic Lennon playlist, 100 BPM, C major",["rock","singer-songwriter","1970s","pacifist","introspective"],true),
  E("en-paul-mccartney","Paul McCartney","en","Зарубежные","Pop","classic pop / rock","1970s",["melodic","optimistic"],128,"G major","versatile melodic tenor","1970s classic pop (pop), versatile melodic tenor, English-language vocals, piano, bass, lush harmonies, optimistic mood, fits a McCartney solo playlist, 128 BPM, G major",["pop","classic pop","1970s","melodic","optimistic"]),
  E("en-queen","Queen","en","Зарубежные","Rock","glam rock / opera rock","1970s",["theatrical","epic"],144,"E-flat major","operatic four-octave tenor","1970s opera rock (rock), operatic four-octave tenor, English-language vocals, layered choral vocals, virtuosic guitar, theatrical and epic mood, fits a stadium rock playlist, 144 BPM, E-flat major",["rock","glam rock","opera rock","1970s","theatrical","epic"],true),
  E("en-acdc","AC/DC","en","Зарубежные","Rock","hard rock / blues rock","1970s",["raw","party"],132,"A major","screaming high-tenor rock vocals","1970s hard rock (rock), screaming high-tenor, English-language vocals, blues-rock riffs, pounding drums, raw and party mood, fits a hard rock playlist, 132 BPM, A major",["rock","hard rock","1970s","raw","party"],true),
  E("en-fleetwood-mac","Fleetwood Mac","en","Зарубежные","Rock","soft rock / pop rock","1970s",["dreamy","interpersonal"],118,"F major","trio of distinctive vocalists","1970s soft rock (rock), trio of distinctive vocalists, English-language vocals, jangly guitar, harmonies, polished production, dreamy and interpersonal mood, fits a Rumours playlist, 118 BPM, F major",["rock","soft rock","1970s","dreamy","interpersonal"]),
  E("en-rolling-stones","The Rolling Stones","en","Зарубежные","Rock","blues rock / classic rock","1960s",["raw","swaggering"],120,"E major","raspy bluesy baritone","1960s blues rock (rock), raspy bluesy baritone, English-language vocals, dirty guitar riffs, swaggering production, raw and swaggering mood, fits a classic rock playlist, 120 BPM, E major",["rock","blues rock","1960s","raw","swaggering"],true),
  E("en-bee-gees","Bee Gees","en","Зарубежные","Disco","disco / pop","1970s",["funky","danceable"],125,"A minor","three-brother falsetto disco harmonies","1970s disco (disco), brotherly falsetto harmonies, English-language vocals, four-on-the-floor disco beat, strings, funky bass, danceable mood, fits a disco classics playlist, 125 BPM, A minor",["disco","pop","1970s","funky","danceable"]),
  E("en-abba","ABBA","en","Зарубежные","Pop","Europop / disco","1970s",["sparkling","melodic"],118,"D major","male/female pop harmonies","1970s Europop (pop), male/female pop harmonies, English-language vocals, lush production, glittering hooks, melodic mood, fits a feel-good 70s playlist, 118 BPM, D major",["pop","Europop","1970s","sparkling","melodic"],true),
  E("en-spice-girls","Spice Girls","en","Зарубежные","Pop","Britpop / dance-pop","1990s",["empowering","fun"],120,"C major","five-member girl-group vocals","1990s Britpop (pop), five-member girl-group vocals, English-language vocals, pop-dance production, fun and empowering mood, fits a 90s pop playlist, 120 BPM, C major",["pop","Britpop","1990s","empowering","fun"]),
  E("en-backstreet-boys","Backstreet Boys","en","Зарубежные","Pop","boy band / pop","1990s",["romantic","polished"],110,"A minor","five-member harmony group","1990s boy band pop (pop), five-member harmony group, English-language vocals, R&B-influenced ballads, polished production, romantic mood, fits a 90s pop playlist, 110 BPM, A minor",["pop","boy band","1990s","romantic","polished"]),
  E("en-britney-spears","Britney Spears","en","Зарубежные","Pop","teen pop / dance-pop","1990s",["catchy","provocative"],118,"E minor","breathy pop princess soprano","1990s teen pop (pop), breathy pop princess soprano, English-language vocals, slick dance-pop production, catchy hooks, provocative mood, fits a 2000s pop playlist, 118 BPM, E minor",["pop","teen pop","1990s","catchy","provocative"]),
  E("en-christina-aguilera","Christina Aguilera","en","Зарубежные","Pop","pop / R&B","2000s",["powerful","sultry"],115,"C minor","powerhouse melisma-heavy soprano","2000s pop R&B (pop), powerhouse melisma-heavy soprano, English-language vocals, R&B production, powerful and sultry mood, fits a vocal diva playlist, 115 BPM, C minor",["pop","R&B","2000s","powerful","sultry"]),
  E("en-mariah-carey","Mariah Carey","en","Зарубежные","Pop","pop / R&B","1990s",["whistle-register","romantic"],100,"E major","five-octave whistle-register diva","1990s pop R&B (pop), whistle-register diva soprano, English-language vocals, gospel-tinged ballads, lush production, romantic mood, fits a Christmas pop playlist, 100 BPM, E major",["pop","R&B","1990s","whistle-register","romantic"],true),
  E("en-celine-dion","Celine Dion","en","Зарубежные","Pop","power ballad","1990s",["dramatic","emotional"],76,"D major","powerhouse Quebec soprano","1990s power ballad (pop), powerhouse Quebec soprano, English-language vocals, orchestral arrangements, dramatic peaks, emotional mood, fits a ballad playlist, 76 BPM, D major",["pop","power ballad","1990s","dramatic","emotional"]),
  E("en-elvis-presley","Elvis Presley","en","Зарубежные","Rock","rock and roll / rockabilly","1950s",["charismatic","iconic"],150,"E major","quivering baritone-tenor","1950s rock and roll (rock), quivering baritone-tenor, English-language vocals, slap-back echo, upright bass, swinging drums, charismatic and iconic mood, fits a rockabilly playlist, 150 BPM, E major",["rock","rock and roll","1950s","charismatic","iconic"],true),
  E("en-johnny-cash","Johnny Cash","en","Зарубежные","Country","outlaw country","1960s",["stoic","poignant"],110,"G major","deep stoic bass-baritone","1960s outlaw country (country), deep stoic bass-baritone, English-language vocals, boom-chicka rhythm guitar, train-beat drums, stoic and poignant mood, fits a country classics playlist, 110 BPM, G major",["country","outlaw country","1960s","stoic","poignant"],true),
  E("en-dolly-parton","Dolly Parton","en","Зарубежные","Country","classic country","1970s",["heartfelt","witty"],112,"C major","silvery Smoky Mountain soprano","1970s classic country (country), silvery soprano, English-language vocals, pedal steel, fiddle, classic Nashville production, heartfelt mood, fits a country queen playlist, 112 BPM, C major",["country","classic country","1970s","heartfelt","witty"],true),
  E("en-willie-nelson","Willie Nelson","en","Зарубежные","Country","outlaw country","1970s",["weathered","wise"],100,"D major","behind-the-beat weathered Texas tenor","1970s outlaw country (country), behind-the-beat weathered tenor, English-language vocals, nylon-string guitar, harmonica, brushed snare, wise mood, fits an outlaw country playlist, 100 BPM, D major",["country","outlaw country","1970s","weathered","wise"]),
  E("en-bob-marley","Bob Marley","en","Зарубежные","Reggae","roots reggae","1970s",["spiritual","liberating"],85,"A minor","Jamaican reggae prophet tenor","1970s roots reggae (reggae), Jamaican reggae prophet tenor, English/patois vocals, one-drop riddim, organ skanks, spiritual and liberating mood, fits a reggae classics playlist, 85 BPM, A minor",["reggae","roots reggae","1970s","spiritual","liberating"],true),
  E("en-jimi-hendrix","Jimi Hendrix","en","Зарубежные","Rock","psychedelic rock / blues rock","1960s",["psychedelic","virtuosic"],120,"E major","casual rock vocals over screaming guitar","1960s psychedelic rock (rock), casual baritone vocals, English-language vocals, wah-wah guitar, fuzz tone, exploratory production, psychedelic and virtuosic mood, fits a 60s rock playlist, 120 BPM, E major",["rock","psychedelic rock","1960s","psychedelic","virtuosic"],true),
  E("en-doors","The Doors","en","Зарубежные","Rock","psychedelic rock","1960s",["dark","poetic"],110,"D minor","Jim Morrison hypnotic baritone","1960s psychedelic rock (rock), hypnotic baritone, English-language vocals, electric organ, no bass guitar, jazzy drums, dark and poetic mood, fits a 60s psych playlist, 110 BPM, D minor",["rock","psychedelic rock","1960s","dark","poetic"]),
  E("en-tina-arena","Tracy Chapman","en","Зарубежные","Folk","folk / singer-songwriter","1980s",["intimate","social"],100,"D major","velvety contralto","1980s folk singer-songwriter (folk), velvety contralto, English-language vocals, fingerpicked acoustic guitar, intimate production, social mood, fits a folk playlist, 100 BPM, D major",["folk","singer-songwriter","1980s","intimate","social"]),
  E("en-foo-fighters","Foo Fighters","en","Зарубежные","Rock","alternative rock / post-grunge","1990s",["anthemic","driving"],140,"A major","gravelly screaming tenor","1990s alternative rock (rock), gravelly screaming tenor, English-language vocals, distorted guitar, driving rock drums, anthemic mood, fits a modern rock playlist, 140 BPM, A major",["rock","alternative rock","1990s","anthemic","driving"]),
  E("en-red-hot-chili-peppers","Red Hot Chili Peppers","en","Зарубежные","Rock","funk rock / alternative","1990s",["funky","melodic"],122,"E minor","melodic Anthony Kiedis tenor with rap delivery","1990s funk rock (rock), melodic tenor with rap delivery, English-language vocals, slap bass, funk guitar, funky and melodic mood, fits a funk rock playlist, 122 BPM, E minor",["rock","funk rock","1990s","funky","melodic"]),
  E("en-pearl-jam","Pearl Jam","en","Зарубежные","Rock","grunge / alternative","1990s",["weathered","earnest"],118,"D major","gravelly Eddie Vedder baritone","1990s grunge (rock), gravelly baritone, English-language vocals, distorted guitar, earnest mood, fits a 90s alt-rock playlist, 118 BPM, D major",["rock","grunge","1990s","weathered","earnest"]),

  // ── RUSSIAN expand (ru: 39 → 65) ──────────────────────────────────────────
  E("ru-mashina-vremeni","Машина Времени","ru","Русские","Rock","советский рок","1970s",["philosophical","melodic"],110,"A minor","философский баритон Макаревича","1970s Soviet rock (rock), philosophical baritone, Russian vocals, jangly guitar, simple drumkit, melodic mood, fits a Soviet rock classics playlist, 110 BPM, A minor",["rock","советский рок","1970s","philosophical","melodic"],true),
  E("ru-aquarium","Аквариум","ru","Русские","Rock","русский рок / арт-рок","1980s",["mystical","poetic"],100,"D major","шаманский баритон Гребенщикова","1980s Russian art-rock (rock), shamanic baritone, Russian vocals, acoustic guitar, eastern influences, mystical mood, fits a Russian rock legends playlist, 100 BPM, D major",["rock","арт-рок","1980s","mystical","poetic"],true),
  E("ru-agata-kristi","Агата Кристи","ru","Русские","Rock","готик-рок / альтернатива","1990s",["dark","theatrical"],128,"D minor","theatrical Samoilov baritone","1990s Russian gothic rock (rock), theatrical baritone, Russian vocals, dark synth-rock production, theatrical mood, fits a Russian dark wave playlist, 128 BPM, D minor",["rock","готик-рок","1990s","dark","theatrical"]),
  E("ru-mumi-troll","Мумий Тролль","ru","Русские","Rock","брит-поп / альтернатива","1990s",["dreamy","ironic"],118,"E major","theatrical Лагутенко tenor","1990s Russian brit-pop (rock), theatrical tenor, Russian vocals, jangly guitar, dreamy production, ironic mood, fits a 90s Russian rock playlist, 118 BPM, E major",["rock","брит-поп","1990s","dreamy","ironic"]),
  E("ru-kipelov","Кипелов","ru","Русские","Metal","русский хэви-метал","2000s",["epic","heroic"],135,"E minor","оперный метал-тенор","2000s Russian heavy metal (metal), operatic metal tenor, Russian vocals, twin-guitar attack, double-bass drums, epic heroic mood, fits a Russian metal playlist, 135 BPM, E minor",["metal","русский метал","2000s","epic","heroic"]),
  E("ru-aria","Ария","ru","Русские","Metal","русский хэви-метал","1980s",["epic","battle"],145,"D minor","классический метал-тенор Кипелова/Беркута","1980s Russian heavy metal (metal), classic metal tenor, Russian vocals, NWOBHM-influenced riffs, double-bass drums, battle mood, fits a Russian metal classics playlist, 145 BPM, D minor",["metal","русский метал","1980s","epic","battle"]),
  E("ru-noize-mc","Noize MC","ru","Русские","Hip-hop","альт-рэп / рэп-рок","2000s",["intellectual","rebellious"],95,"C minor","словесный рэп-тенор Алексеева","2000s Russian alt-rap (hip-hop), word-spitting rap tenor, Russian vocals, rock guitar samples, social commentary, rebellious mood, fits a Russian conscious rap playlist, 95 BPM, C minor",["hip-hop","альт-рэп","2000s","intellectual","rebellious"]),
  E("ru-pharaoh","Pharaoh","ru","Русские","Hip-hop","клауд-рэп / тёмный рэп","2010s",["atmospheric","dark"],140,"F minor","меланхоличный клауд-рэп тенор","2010s Russian cloud rap (hip-hop), atmospheric dark tenor, Russian vocals, hazy lo-fi beats, vocal effects, dark mood, fits a Russian underground playlist, 140 BPM, F minor",["hip-hop","клауд-рэп","2010s","atmospheric","dark"]),
  E("ru-husky","Хаски","ru","Русские","Hip-hop","русский андеграунд","2010s",["raw","poetic"],90,"D minor","сырой подвальный рэп-баритон","2010s Russian underground rap (hip-hop), raw basement baritone, Russian vocals, minimalist beats, poetic delivery, raw mood, fits a Russian street poetry playlist, 90 BPM, D minor",["hip-hop","андеграунд","2010s","raw","poetic"]),
  E("ru-buerak","Буерак","ru","Русские","Rock","инди-рок / пост-панк","2010s",["nostalgic","cold"],135,"E minor","отстранённый инди баритон","2010s Russian indie post-punk (rock), detached indie baritone, Russian vocals, jangly guitar, cold reverb, nostalgic mood, fits a Russian indie playlist, 135 BPM, E minor",["rock","инди-рок","2010s","nostalgic","cold"]),
  E("ru-molchat-doma","Молчат Дома","ru","Русские","Rock","пост-панк / дарк-вэйв","2010s",["depressive","cold"],128,"D minor","ледяной депрессивный баритон","2010s Belarusian post-punk (rock), icy depressive baritone, Russian vocals, drum machine, cold synths, depressive mood, fits a doomer playlist, 128 BPM, D minor",["rock","пост-панк","2010s","depressive","cold"],true),
  E("ru-grazhdanskaya-oborona","Гражданская Оборона","ru","Русские","Rock","сибирский панк / лоу-фай рок","1980s",["raw","anarchist"],150,"E minor","надрывный панк-тенор Летова","1980s Siberian punk (rock), tortured punk tenor, Russian vocals, distorted guitar wall, lo-fi tape production, anarchist mood, fits a Russian punk playlist, 150 BPM, E minor",["rock","сибирский панк","1980s","raw","anarchist"]),
  E("ru-leps","Григорий Лепс","ru","Русские","Pop","эстрада / шансон","2000s",["dramatic","hoarse"],95,"E minor","надрывный хриплый баритон","2000s Russian chanson (pop), dramatic hoarse baritone, Russian vocals, orchestral pop production, dramatic mood, fits a Russian estrada playlist, 95 BPM, E minor",["pop","шансон","2000s","dramatic","hoarse"]),
  E("ru-vysotsky","Владимир Высоцкий","ru","Русские","Folk","авторская песня / бард","1970s",["raw","prophetic"],100,"A minor","надрывный хриплый бардовский баритон","1970s Russian bard song (folk), tortured raspy baritone, Russian vocals, single acoustic guitar, raw and prophetic mood, fits a Russian bard playlist, 100 BPM, A minor",["folk","авторская песня","1970s","raw","prophetic"],true),
  E("ru-okudzhava","Булат Окуджава","ru","Русские","Folk","авторская песня / бард","1960s",["intimate","poetic"],90,"D minor","тихий бардовский тенор","1960s Russian bard song (folk), quiet bard tenor, Russian vocals, gentle acoustic guitar, intimate poetic mood, fits a Russian bard classics playlist, 90 BPM, D minor",["folk","авторская песня","1960s","intimate","poetic"],true),
  E("ru-rotaru","София Ротару","ru","Русские","Pop","советская эстрада","1970s",["warm","sincere"],110,"F major","тёплое лирическое сопрано","1970s Soviet pop (pop), warm lyrical soprano, Russian/Ukrainian vocals, orchestral pop arrangements, warm sincere mood, fits a Soviet pop playlist, 110 BPM, F major",["pop","советская эстрада","1970s","warm","sincere"]),
  E("ru-leontiev","Валерий Леонтьев","ru","Русские","Pop","советская эстрада","1980s",["theatrical","glittery"],128,"G major","театральный поп-тенор","1980s Soviet pop (pop), theatrical pop tenor, Russian vocals, synth-heavy production, glittery theatrical mood, fits a Soviet stage playlist, 128 BPM, G major",["pop","советская эстрада","1980s","theatrical","glittery"]),
  E("ru-tatu","т.А.Т.у.","ru","Русские","Pop","евро-поп / тинейдж-поп","2000s",["edgy","provocative"],128,"A minor","дуэт юных сопрано","2000s Russian teen pop (pop), young female duo sopranos, Russian vocals, euro-pop production, edgy provocative mood, fits a 2000s Russian playlist, 128 BPM, A minor",["pop","евро-поп","2000s","edgy","provocative"]),
  E("ru-vaenga","Елена Ваенга","ru","Русские","Pop","шансон / эстрада","2000s",["dramatic","folk"],90,"E minor","драматичное сопрано с фольклорной подачей","2000s Russian chanson (pop), dramatic folk-inflected soprano, Russian vocals, orchestral production, dramatic mood, fits a Russian chanson playlist, 90 BPM, E minor",["pop","шансон","2000s","dramatic","folk"]),
  E("ru-leningrad-shnur","Сергей Шнуров","ru","Русские","Rock","рок-шансон / провокация","2000s",["wild","irreverent"],150,"G major","провокационный хриплый баритон","2000s Russian rock-chanson (rock), provocative hoarse baritone, Russian vocals, ska-punk band, wild irreverent mood, fits a Russian party playlist, 150 BPM, G major",["rock","рок-шансон","2000s","wild","irreverent"]),
  E("ru-egor-creed","Егор Крид","ru","Русские","Pop","поп / R&B","2010s",["romantic","glossy"],110,"A minor","глянцевый поп-тенор","2010s Russian pop R&B (pop), glossy pop tenor, Russian vocals, modern R&B production, romantic mood, fits a Russian radio pop playlist, 110 BPM, A minor",["pop","R&B","2010s","romantic","glossy"]),
  E("ru-dora","Дора","ru","Русские","Pop","инди-поп / бедрум-поп","2010s",["ironic","quirky"],115,"D major","задорное иронично-наивное сопрано","2010s Russian bedroom pop (pop), playful naive soprano, Russian vocals, lo-fi production, quirky ironic mood, fits a Russian indie pop playlist, 115 BPM, D major",["pop","инди-поп","2010s","ironic","quirky"]),
  E("ru-kasta","Каста","ru","Русские","Hip-hop","русский хип-хоп","2000s",["lyrical","old-school"],90,"F minor","классический рэп-квартет","2000s Russian classic hip-hop (hip-hop), four-emcee lyrical group, Russian vocals, boom-bap beats, lyrical mood, fits a Russian rap classics playlist, 90 BPM, F minor",["hip-hop","русский хип-хоп","2000s","lyrical","old-school"]),
  E("ru-rasa","РАСА","ru","Русские","Pop","трэп / поп","2010s",["catchy","melodic"],95,"G minor","мелодичный трэп-дуэт","2010s Russian trap pop (pop), melodic trap duo, Russian vocals, trap beats, catchy hooks, melodic mood, fits a Russian pop trap playlist, 95 BPM, G minor",["pop","трэп","2010s","catchy","melodic"]),
  E("ru-mot","Мот","ru","Русские","Hip-hop","поп-рэп","2010s",["melodic","romantic"],100,"D minor","мелодичный поп-рэп тенор","2010s Russian pop rap (hip-hop), melodic pop-rap tenor, Russian vocals, pop production, romantic mood, fits a Russian pop-rap playlist, 100 BPM, D minor",["hip-hop","поп-рэп","2010s","melodic","romantic"]),
  E("ru-tima-belorusskih","Тима Белорусских","ru","Русские","Hip-hop","меланхоличный поп-рэп","2010s",["melancholic","tender"],95,"C minor","нежный меланхоличный тенор","2010s Belarusian pop rap (hip-hop), tender melancholic tenor, Russian vocals, lo-fi pop production, melancholic mood, fits a Russian sad rap playlist, 95 BPM, C minor",["hip-hop","поп-рэп","2010s","melancholic","tender"]),

  // ── KOREAN expand (ko: 16 → 28) ───────────────────────────────────────────
  E("ko-twice","TWICE","ko","K-Pop","Pop","K-pop / bubblegum","2010s",["bubbly","cute"],128,"C major","nine-member bubbly girl group","2010s K-pop bubblegum (pop), bubbly nine-member girl group, Korean/Japanese vocals, cheerful synth-pop production, cute mood, fits a K-pop bright playlist, 128 BPM, C major",["pop","K-pop","2010s","bubbly","cute"]),
  E("ko-red-velvet","Red Velvet","ko","K-Pop","Pop","K-pop / experimental","2010s",["versatile","quirky"],120,"A minor","five-member dual-concept girl group","2010s K-pop experimental (pop), versatile five-member group, Korean vocals, genre-shifting production, quirky mood, fits a K-pop variety playlist, 120 BPM, A minor",["pop","K-pop","2010s","versatile","quirky"]),
  E("ko-stray-kids","Stray Kids","ko","K-Pop","Pop","K-pop / hip-hop","2010s",["aggressive","self-produced"],145,"F minor","eight-member self-producing hip-hop boy group","2010s K-pop hip-hop (pop), aggressive self-produced group, Korean vocals, hard-hitting beats, aggressive mood, fits a K-pop hype playlist, 145 BPM, F minor",["pop","K-pop","2010s","aggressive","self-produced"]),
  E("ko-itzy","ITZY","ko","K-Pop","Pop","K-pop / girl crush","2010s",["confident","fierce"],130,"D minor","five-member fierce girl group","2010s K-pop girl crush (pop), confident fierce group, Korean vocals, bold production, fierce mood, fits a K-pop confidence playlist, 130 BPM, D minor",["pop","K-pop","2010s","confident","fierce"]),
  E("ko-ive","IVE","ko","K-Pop","Pop","K-pop / Y2K","2020s",["chic","retro-futuristic"],128,"E major","six-member chic girl group","2020s K-pop Y2K (pop), chic six-member group, Korean vocals, Y2K-influenced production, chic mood, fits a modern K-pop playlist, 128 BPM, E major",["pop","K-pop","2020s","chic","retro-futuristic"]),
  E("ko-newjeans","NewJeans","ko","K-Pop","Pop","K-pop / breakbeat","2020s",["fresh","Y2K"],135,"G major","five-member easy-breezy girl group","2020s K-pop breakbeat (pop), fresh five-member group, Korean/English vocals, UK garage / breakbeat production, easy-breezy mood, fits a fresh K-pop playlist, 135 BPM, G major",["pop","K-pop","2020s","fresh","Y2K"],true),
  E("ko-le-sserafim","LE SSERAFIM","ko","K-Pop","Pop","K-pop / hyperpop","2020s",["fierce","fearless"],140,"C minor","five-member fearless girl group","2020s K-pop hyperpop (pop), fierce fearless group, Korean/English vocals, hyperpop-influenced production, fierce mood, fits an empowerment playlist, 140 BPM, C minor",["pop","K-pop","2020s","fierce","fearless"]),
  E("ko-txt","TXT","ko","K-Pop","Pop","K-pop / pop rock","2010s",["youthful","emotional"],132,"B-flat major","five-member youthful boy group","2010s K-pop pop rock (pop), youthful five-member group, Korean vocals, pop rock production, emotional mood, fits a youthful K-pop playlist, 132 BPM, B-flat major",["pop","K-pop","2010s","youthful","emotional"]),
  E("ko-mamamoo","MAMAMOO","ko","K-Pop","Pop","K-pop / jazz / R&B","2010s",["soulful","vocal-heavy"],110,"G minor","four-member powerhouse vocal group","2010s K-pop jazz (pop), soulful four-member group, Korean vocals, jazz-R&B production, vocal-heavy mood, fits a K-pop vocal playlist, 110 BPM, G minor",["pop","K-pop","2010s","soulful","vocal-heavy"]),
  E("ko-psy","PSY","ko","K-Pop","Pop","K-pop / dance / novelty","2010s",["fun","viral"],132,"B minor","comedic dance-pop baritone","2010s K-pop dance (pop), comedic dance-pop baritone, Korean vocals, EDM production, viral fun mood, fits a viral K-pop playlist, 132 BPM, B minor",["pop","K-pop","2010s","fun","viral"],true),
  E("ko-girls-generation","Girls' Generation","ko","K-Pop","Pop","K-pop / bubblegum","2000s",["iconic","sweet"],128,"D major","nine-member iconic girl group","2000s K-pop bubblegum (pop), iconic nine-member group, Korean vocals, polished bubblegum production, sweet mood, fits a K-pop pioneers playlist, 128 BPM, D major",["pop","K-pop","2000s","iconic","sweet"]),
  E("ko-2ne1","2NE1","ko","K-Pop","Pop","K-pop / hip-hop / electronic","2000s",["fierce","groundbreaking"],128,"F minor","four-member fierce girl group","2000s K-pop hip-hop (pop), fierce four-member group, Korean vocals, YG electronic-hip-hop production, groundbreaking mood, fits a K-pop legends playlist, 128 BPM, F minor",["pop","K-pop","2000s","fierce","groundbreaking"]),

  // ── JAPANESE expand (ja: 17 → 28) ─────────────────────────────────────────
  E("ja-yoasobi","YOASOBI","ja","Японские","Pop","J-pop / digital","2010s",["narrative","upbeat"],135,"B-flat major","crystalline female vocalist over digital production","2010s J-pop digital (pop), crystalline soprano, Japanese vocals, digital piano-driven production, narrative-driven, upbeat mood, fits a modern anime playlist, 135 BPM, B-flat major",["pop","J-pop","2010s","narrative","upbeat"]),
  E("ja-mr-children","Mr. Children","ja","Японские","Pop","J-pop / rock","1990s",["sincere","anthemic"],105,"C major","sincere J-rock tenor","1990s J-pop rock (pop), sincere tenor, Japanese vocals, guitar-driven J-rock, anthemic mood, fits a J-pop classics playlist, 105 BPM, C major",["pop","J-pop","1990s","sincere","anthemic"]),
  E("ja-spitz","Spitz","ja","Японские","Rock","J-rock / alternative","1990s",["dreamy","melodic"],120,"D major","dreamy J-rock tenor","1990s J-rock (rock), dreamy melodic tenor, Japanese vocals, jangly guitar, light production, dreamy mood, fits a Japanese alt playlist, 120 BPM, D major",["rock","J-rock","1990s","dreamy","melodic"]),
  E("ja-radwimps","RADWIMPS","ja","Японские","Rock","J-rock / alternative","2000s",["emotional","cinematic"],128,"A minor","emotive Yojiro Noda tenor","2000s J-rock (rock), emotive tenor, Japanese vocals, alternative rock, cinematic mood, fits a Shinkai film playlist, 128 BPM, A minor",["rock","J-rock","2000s","emotional","cinematic"],true),
  E("ja-perfume","Perfume","ja","Японские","Pop","J-pop / electropop","2000s",["futuristic","cute"],128,"F major","three-member auto-tuned trio","2000s J-electropop (pop), futuristic trio, Japanese vocals, glitchy electropop, cute mood, fits a J-electro playlist, 128 BPM, F major",["pop","J-pop","2000s","futuristic","cute"]),
  E("ja-akb48","AKB48","ja","Японские","Pop","J-pop / idol","2000s",["bubbly","theatrical"],145,"C major","large-format idol group","2000s J-idol (pop), large idol group, Japanese vocals, energetic pop production, bubbly mood, fits a J-idol playlist, 145 BPM, C major",["pop","J-pop","2000s","bubbly","theatrical"]),
  E("ja-namie-amuro","Namie Amuro","ja","Японские","Pop","J-pop / R&B","1990s",["smooth","trendy"],110,"A minor","smooth J-pop R&B soprano","1990s J-pop R&B (pop), smooth soprano, Japanese vocals, R&B-influenced production, trendy mood, fits a J-pop divas playlist, 110 BPM, A minor",["pop","J-pop","1990s","smooth","trendy"]),
  E("ja-ayumi-hamasaki","Ayumi Hamasaki","ja","Японские","Pop","J-pop / dance-pop","1990s",["iconic","empowering"],132,"D minor","Empress of J-pop, melodic soprano","1990s J-pop (pop), iconic soprano, Japanese vocals, dance-pop production, empowering mood, fits a J-pop empress playlist, 132 BPM, D minor",["pop","J-pop","1990s","iconic","empowering"],true),
  E("ja-l-arc-en-ciel","L'Arc-en-Ciel","ja","Японские","Rock","J-rock / visual kei","1990s",["dramatic","melodic"],135,"E minor","melodic visual-kei tenor","1990s J-rock visual kei (rock), melodic dramatic tenor, Japanese vocals, melodic guitar-driven J-rock, dramatic mood, fits a visual kei playlist, 135 BPM, E minor",["rock","J-rock","1990s","dramatic","melodic"]),
  E("ja-x-japan","X Japan","ja","Японские","Metal","speed metal / power ballad","1980s",["dramatic","virtuosic"],180,"B minor","operatic Toshi tenor","1980s speed metal (metal), operatic tenor, Japanese vocals, lightning-fast double-bass, classical-influenced solos, dramatic mood, fits a J-metal playlist, 180 BPM, B minor",["metal","speed metal","1980s","dramatic","virtuosic"]),
  E("ja-anri","Tatsuro Yamashita","ja","Японские","Pop","city pop","1980s",["nostalgic","groovy"],110,"G major","silky city pop tenor","1980s Japanese city pop (pop), silky tenor, Japanese vocals, slap bass, jazzy chords, sax solos, nostalgic groovy mood, fits a city pop playlist, 110 BPM, G major",["pop","city pop","1980s","nostalgic","groovy"],true),

  // ── SPANISH expand (es: 21 → 32) ──────────────────────────────────────────
  E("es-shakira-2","Manu Chao","es","Испанские","World","Latin alternative / world music","1990s",["bohemian","political"],120,"A major","laid-back bilingual baritone","1990s Latin alternative (world), laid-back bilingual baritone, Spanish/French/English vocals, reggae-ska-rumba mix, political bohemian mood, fits a world music playlist, 120 BPM, A major",["world","Latin alternative","1990s","bohemian","political"],true),
  E("es-luis-miguel","Luis Miguel","es","Испанские","Pop","Latin pop / bolero","1990s",["romantic","velvety"],85,"G major","velvety bolero tenor","1990s Latin bolero (pop), velvety tenor, Spanish vocals, orchestral bolero arrangements, romantic mood, fits a Latin romance playlist, 85 BPM, G major",["pop","bolero","1990s","romantic","velvety"]),
  E("es-rauw-alejandro","Rauw Alejandro","es","Испанские","Hip-hop","reggaeton / Latin R&B","2010s",["sensual","danceable"],95,"D minor","sensual Puerto Rican R&B tenor","2010s reggaeton R&B (hip-hop), sensual tenor, Spanish vocals, dembow with R&B touches, sensual mood, fits a Latin night playlist, 95 BPM, D minor",["hip-hop","reggaeton","2010s","sensual","danceable"]),
  E("es-karol-g","Karol G","es","Испанские","Hip-hop","reggaeton / Latin pop","2010s",["fierce","danceable"],95,"C minor","fierce Colombian reggaeton soprano","2010s reggaeton (hip-hop), fierce soprano, Spanish vocals, dembow, fierce mood, fits a Latin women playlist, 95 BPM, C minor",["hip-hop","reggaeton","2010s","fierce","danceable"]),
  E("es-myke-towers","Myke Towers","es","Испанские","Hip-hop","trap Latino / reggaeton","2010s",["smooth","melodic"],90,"F minor","smooth Latin trap baritone","2010s trap Latino (hip-hop), smooth baritone, Spanish vocals, atmospheric trap-reggaeton, melodic mood, fits a Latin trap playlist, 90 BPM, F minor",["hip-hop","trap Latino","2010s","smooth","melodic"]),
  E("es-jesse-joy","Jesse & Joy","es","Испанские","Pop","Mexican pop / acoustic","2000s",["heartfelt","sibling-harmony"],100,"D major","Mexican brother-sister duo","2000s Mexican pop (pop), heartfelt sibling duo, Spanish vocals, acoustic guitar, heartfelt mood, fits a Mexican romantic playlist, 100 BPM, D major",["pop","Mexican pop","2000s","heartfelt","sibling-harmony"]),
  E("es-natalia-lafourcade","Natalia Lafourcade","es","Испанские","Pop","Mexican folk / bolero","2000s",["tender","traditional"],88,"G major","tender Mexican folk soprano","2000s Mexican folk (pop), tender soprano, Spanish vocals, acoustic guitar, traditional Mexican instruments, tender mood, fits a Mexican heritage playlist, 88 BPM, G major",["pop","Mexican folk","2000s","tender","traditional"],true),
  E("es-vicente-fernandez","Vicente Fernández","es","Испанские","Pop","ranchera / mariachi","1970s",["proud","heroic"],100,"D major","powerful Mexican mariachi baritone","1970s ranchera (pop), powerful mariachi baritone, Spanish vocals, mariachi ensemble, trumpets, proud heroic mood, fits a Mexican ranchera playlist, 100 BPM, D major",["pop","ranchera","1970s","proud","heroic"],true),
  E("es-cd9","Joaquín Sabina","es","Испанские","Rock","Spanish rock / cantautor","1980s",["raconteur","witty"],110,"E minor","raspy Spanish raconteur baritone","1980s Spanish cantautor (rock), raspy raconteur baritone, Spanish vocals, acoustic-driven rock, witty mood, fits a Spanish songwriter playlist, 110 BPM, E minor",["rock","cantautor","1980s","raconteur","witty"]),
  E("es-paco","Paco de Lucía","es","Испанские","Folk","flamenco","1970s",["virtuosic","fiery"],140,"E Phrygian","flamenco guitar maestro, instrumental","1970s flamenco (folk), flamenco guitar maestro instrumental, no vocals, Spanish flamenco guitar, palmas (handclaps), virtuosic fiery mood, fits a flamenco playlist, 140 BPM, E Phrygian",["folk","flamenco","1970s","virtuosic","fiery"],true),
  E("es-rosario","Rosario Flores","es","Испанские","Pop","flamenco pop / rumba","1990s",["sensual","earthy"],110,"E Phrygian","earthy flamenco-pop alto","1990s flamenco pop (pop), earthy flamenco alto, Spanish vocals, flamenco guitar, rumba beat, sensual mood, fits a flamenco-pop playlist, 110 BPM, E Phrygian",["pop","flamenco pop","1990s","sensual","earthy"]),

  // ── PORTUGUESE expand (pt: 18 → 30) ───────────────────────────────────────
  E("pt-tom-jobim-2","Marisa Monte","pt","Португальские","Pop","MPB / samba pop","1990s",["soulful","sophisticated"],100,"E major","sophisticated MPB soprano","1990s MPB (pop), sophisticated soprano, Portuguese vocals, acoustic guitar, percussive samba, soulful mood, fits a Brazilian sophisticated playlist, 100 BPM, E major",["pop","MPB","1990s","soulful","sophisticated"]),
  E("pt-djavan","Djavan","pt","Португальские","Pop","MPB / Brazilian jazz","1980s",["melodic","jazz-inflected"],105,"D major","melodic Brazilian jazz tenor","1980s MPB jazz (pop), melodic jazz-inflected tenor, Portuguese vocals, jazz chords, samba percussion, melodic mood, fits a Brazilian jazz playlist, 105 BPM, D major",["pop","MPB","1980s","melodic","jazz-inflected"]),
  E("pt-jorge-ben","Jorge Ben Jor","pt","Португальские","Pop","samba rock / MPB","1960s",["funky","cheerful"],112,"D major","cheerful samba-rock baritone","1960s samba rock (pop), cheerful baritone, Portuguese vocals, samba rhythms with rock guitar, funky cheerful mood, fits a Brazilian funky playlist, 112 BPM, D major",["pop","samba rock","1960s","funky","cheerful"]),
  E("pt-vanessa-da-mata","Vanessa da Mata","pt","Португальские","Pop","MPB / bossa nova","2000s",["serene","sensual"],95,"C major","serene Brazilian alto","2000s MPB (pop), serene alto, Portuguese vocals, bossa-influenced production, sensual mood, fits a Brazilian chill playlist, 95 BPM, C major",["pop","MPB","2000s","serene","sensual"]),
  E("pt-cazuza","Cazuza","pt","Португальские","Rock","Brazilian rock","1980s",["poetic","raw"],128,"E minor","raw poetic Brazilian rock tenor","1980s Brazilian rock (rock), raw poetic tenor, Portuguese vocals, post-punk-influenced rock, raw mood, fits a Brazilian rock classics playlist, 128 BPM, E minor",["rock","Brazilian rock","1980s","poetic","raw"]),
  E("pt-marisa","Mariza","pt","Португальские","Folk","Portuguese fado","2000s",["yearning","dramatic"],90,"D minor","yearning fado contralto","2000s Portuguese fado (folk), yearning dramatic contralto, Portuguese vocals, Portuguese guitar, classical guitar, dramatic mood, fits a fado playlist, 90 BPM, D minor",["folk","fado","2000s","yearning","dramatic"],true),
  E("pt-amalia","Amália Rodrigues","pt","Португальские","Folk","Portuguese fado / classic","1950s",["saudade","legendary"],85,"E minor","queen of fado, dramatic mezzo","1950s Portuguese fado (folk), legendary dramatic mezzo, Portuguese vocals, Portuguese guitar, saudade mood, fits a fado classics playlist, 85 BPM, E minor",["folk","fado","1950s","saudade","legendary"],true),
  E("pt-skank","Skank","pt","Португальские","Rock","Brazilian rock / ska","1990s",["sunny","catchy"],135,"G major","sunny Brazilian ska-rock tenor","1990s Brazilian rock ska (rock), sunny tenor, Portuguese vocals, ska guitar, brass section, catchy mood, fits a Brazilian sunny rock playlist, 135 BPM, G major",["rock","Brazilian rock","1990s","sunny","catchy"]),
  E("pt-pabllo-vittar","Pabllo Vittar","pt","Португальские","Pop","Brazilian funk / drag pop","2010s",["empowering","danceable"],128,"A minor","powerful drag-pop tenor","2010s Brazilian drag pop (pop), powerful drag-pop tenor, Portuguese vocals, funk carioca, energetic production, empowering mood, fits a queer Brazilian playlist, 128 BPM, A minor",["pop","Brazilian pop","2010s","empowering","danceable"]),
  E("pt-pollo","Mc Kevinho","pt","Португальские","Pop","Brazilian funk","2010s",["catchy","party"],130,"C minor","catchy Brazilian funk tenor","2010s Brazilian funk (pop), catchy funk tenor, Portuguese vocals, funk carioca beats, party mood, fits a Brazilian baile playlist, 130 BPM, C minor",["pop","Brazilian funk","2010s","catchy","party"]),
  E("pt-emicida","Emicida","pt","Португальские","Hip-hop","Brazilian hip-hop / conscious rap","2000s",["conscious","poetic"],90,"D minor","conscious Brazilian rapper","2000s Brazilian conscious hip-hop (hip-hop), conscious poetic rapper, Portuguese vocals, soulful samples, conscious mood, fits a Brazilian rap playlist, 90 BPM, D minor",["hip-hop","Brazilian hip-hop","2000s","conscious","poetic"]),
  E("pt-criolo","Criolo","pt","Португальские","Hip-hop","Brazilian rap / MPB fusion","2010s",["literary","sophisticated"],95,"G minor","literary São Paulo rap baritone","2010s Brazilian rap (hip-hop), literary baritone, Portuguese vocals, jazz-MPB fusion beats, sophisticated mood, fits a Brazilian alternative hip-hop playlist, 95 BPM, G minor",["hip-hop","Brazilian rap","2010s","literary","sophisticated"]),

  // ── FRENCH expand (fr: 18 → 28) ───────────────────────────────────────────
  E("fr-stromae-2","Christine and the Queens","fr","Французские","Pop","French art-pop / electronic","2010s",["androgynous","cerebral"],120,"D major","androgynous art-pop tenor/soprano","2010s French art-pop (pop), androgynous voice, French/English vocals, minimalist electronic production, cerebral mood, fits a French alt playlist, 120 BPM, D major",["pop","art-pop","2010s","androgynous","cerebral"]),
  E("fr-pomme","Pomme","fr","Французские","Pop","French indie folk","2010s",["ethereal","intimate"],88,"E minor","ethereal French folk soprano","2010s French indie folk (pop), ethereal soprano, French vocals, fingerpicked guitar, intimate mood, fits a French intimate playlist, 88 BPM, E minor",["pop","indie folk","2010s","ethereal","intimate"]),
  E("fr-jul","Jul","fr","Французские","Hip-hop","French rap / Marseille","2010s",["catchy","prolific"],95,"F minor","Marseille auto-tuned rapper","2010s French rap Marseille (hip-hop), auto-tuned baritone, French vocals, melodic trap, catchy mood, fits a French street playlist, 95 BPM, F minor",["hip-hop","French rap","2010s","catchy","prolific"]),
  E("fr-pnl","PNL","fr","Французские","Hip-hop","cloud rap / French rap","2010s",["dreamy","atmospheric"],90,"D minor","auto-tuned brother duo","2010s French cloud rap (hip-hop), auto-tuned brother duo, French vocals, dreamy atmospheric production, dreamy mood, fits a French cloud rap playlist, 90 BPM, D minor",["hip-hop","cloud rap","2010s","dreamy","atmospheric"]),
  E("fr-iam","IAM","fr","Французские","Hip-hop","French hip-hop / Marseille","1990s",["lyrical","Marseille"],95,"E minor","Marseille rap legends","1990s French hip-hop (hip-hop), lyrical Marseille rap group, French vocals, boom-bap with Mediterranean samples, Marseille mood, fits a French rap legends playlist, 95 BPM, E minor",["hip-hop","French hip-hop","1990s","lyrical","Marseille"],true),
  E("fr-jacques-brel","Jacques Brel","fr","Французские","Pop","French chanson / Belgian","1960s",["dramatic","theatrical"],100,"D minor","dramatic Belgian chansonnier baritone","1960s French chanson (pop), dramatic theatrical baritone, French vocals, accordion, dramatic orchestration, theatrical mood, fits a chanson classics playlist, 100 BPM, D minor",["pop","chanson","1960s","dramatic","theatrical"],true),
  E("fr-zaz","Zaz","fr","Французские","Pop","French folk / jazz manouche","2010s",["bohemian","earthy"],115,"E major","earthy bohemian alto","2010s French folk (pop), earthy bohemian alto, French vocals, gypsy jazz guitar, bohemian mood, fits a French street playlist, 115 BPM, E major",["pop","French folk","2010s","bohemian","earthy"]),
  E("fr-vianney","Vianney","fr","Французские","Pop","French chanson moderne","2010s",["tender","intimate"],95,"G major","tender French folk tenor","2010s French chanson moderne (pop), tender tenor, French vocals, acoustic guitar, intimate mood, fits a French romance playlist, 95 BPM, G major",["pop","chanson moderne","2010s","tender","intimate"]),
  E("fr-clara-luciani","Clara Luciani","fr","Французские","Pop","French chanson / indie","2010s",["smoky","retro"],108,"A minor","smoky retro French alto","2010s French indie chanson (pop), smoky alto, French vocals, retro-influenced production, retro mood, fits a French modern indie playlist, 108 BPM, A minor",["pop","French indie","2010s","smoky","retro"]),
  E("fr-renan-luce","Renaud","fr","Французские","Pop","French chanson / folk","1980s",["streetwise","poetic"],110,"D major","raspy streetwise French baritone","1980s French folk chanson (pop), raspy streetwise baritone, French vocals, folk-rock production, streetwise poetic mood, fits a French folk playlist, 110 BPM, D major",["pop","French folk","1980s","streetwise","poetic"]),

  // ── GERMAN expand (de: 18 → 28) ───────────────────────────────────────────
  E("de-helene-fischer","Helene Fischer","de","Немецкие","Pop","schlager / German pop","2000s",["polished","danceable"],120,"D major","polished schlager soprano","2000s German schlager (pop), polished soprano, German vocals, schlager pop production, danceable mood, fits a German schlager playlist, 120 BPM, D major",["pop","schlager","2000s","polished","danceable"],true),
  E("de-modern-talking","Modern Talking","de","Немецкие","Pop","Euro disco / German pop","1980s",["catchy","kitschy"],128,"E minor","Dieter Bohlen falsetto duo","1980s Euro disco (pop), falsetto duo, English vocals (German group), euro disco production, kitschy mood, fits an 80s Euro disco playlist, 128 BPM, E minor",["pop","Euro disco","1980s","catchy","kitschy"],true),
  E("de-die-arzte","Die Ärzte","de","Немецкие","Rock","German punk rock / fun punk","1980s",["fun","irreverent"],150,"A major","fun German punk rock trio","1980s German fun punk (rock), playful trio, German vocals, punk rock with humor, irreverent mood, fits a German fun rock playlist, 150 BPM, A major",["rock","German punk","1980s","fun","irreverent"]),
  E("de-die-toten-hosen","Die Toten Hosen","de","Немецкие","Rock","German punk rock","1980s",["anthemic","working-class"],135,"D major","anthemic German punk baritone","1980s German punk (rock), anthemic baritone, German vocals, punk rock with melodic hooks, working-class mood, fits a German punk playlist, 135 BPM, D major",["rock","German punk","1980s","anthemic","working-class"]),
  E("de-bushido","Bushido","de","Немецкие","Hip-hop","German gangsta rap","2000s",["aggressive","street"],95,"F minor","aggressive German gangsta rap baritone","2000s German gangsta rap (hip-hop), aggressive baritone, German vocals, hard street beats, aggressive mood, fits a German street rap playlist, 95 BPM, F minor",["hip-hop","German rap","2000s","aggressive","street"]),
  E("de-sido","Sido","de","Немецкие","Hip-hop","German hip-hop","2000s",["catchy","street"],100,"G minor","catchy German rapper baritone","2000s German hip-hop (hip-hop), catchy baritone, German vocals, mainstream German rap production, street mood, fits a German hip-hop playlist, 100 BPM, G minor",["hip-hop","German rap","2000s","catchy","street"]),
  E("de-falco","Falco","de","Немецкие","Pop","new wave / electronic / German rap","1980s",["theatrical","ironic"],115,"D minor","Austrian theatrical baritone / proto-rapper","1980s Austrian new wave (pop), theatrical baritone, German/English vocals, synth-rock with rap, ironic mood, fits an 80s German playlist, 115 BPM, D minor",["pop","new wave","1980s","theatrical","ironic"],true),
  E("de-juli","Juli","de","Немецкие","Rock","German pop rock","2000s",["wistful","melodic"],118,"A minor","wistful German pop-rock soprano","2000s German pop rock (rock), wistful soprano, German vocals, melodic guitar-driven rock, melodic mood, fits a German pop-rock playlist, 118 BPM, A minor",["rock","German pop rock","2000s","wistful","melodic"]),
  E("de-revolverheld","Revolverheld","de","Немецкие","Rock","German pop rock","2000s",["catchy","anthemic"],128,"E minor","catchy German pop-rock tenor","2000s German pop rock (rock), catchy tenor, German vocals, anthemic guitar production, anthemic mood, fits a German radio rock playlist, 128 BPM, E minor",["rock","German pop rock","2000s","catchy","anthemic"]),
  E("de-shirin-david","Shirin David","de","Немецкие","Hip-hop","German hip-hop / pop rap","2010s",["fierce","glamorous"],100,"G minor","fierce German female rapper","2010s German pop rap (hip-hop), fierce female rapper, German vocals, modern pop-rap production, glamorous mood, fits a German female rap playlist, 100 BPM, G minor",["hip-hop","German rap","2010s","fierce","glamorous"]),

  // ── ITALIAN expand (it: 15 → 25) ──────────────────────────────────────────
  E("it-maneskin","Måneskin","it","Итальянские","Rock","Italian glam rock / pop rock","2010s",["theatrical","raw"],130,"E minor","theatrical Damiano baritone","2010s Italian glam rock (rock), theatrical baritone, Italian/English vocals, raw glam rock with funk bass, theatrical mood, fits a modern rock playlist, 130 BPM, E minor",["rock","glam rock","2010s","theatrical","raw"],true),
  E("it-jovanotti","Jovanotti","it","Итальянские","Pop","Italian pop rap / world","1990s",["uplifting","eclectic"],118,"G major","sunny Italian pop-rap tenor","1990s Italian pop rap (pop), sunny tenor, Italian vocals, world music influences, uplifting mood, fits an Italian feel-good playlist, 118 BPM, G major",["pop","Italian pop rap","1990s","uplifting","eclectic"]),
  E("it-fabri-fibra","Fabri Fibra","it","Итальянские","Hip-hop","Italian hip-hop","2000s",["witty","incisive"],95,"D minor","witty Italian rapper baritone","2000s Italian hip-hop (hip-hop), witty baritone, Italian vocals, hard-hitting beats, incisive mood, fits an Italian rap playlist, 95 BPM, D minor",["hip-hop","Italian hip-hop","2000s","witty","incisive"]),
  E("it-marco-mengoni","Marco Mengoni","it","Итальянские","Pop","Italian pop / soul","2010s",["soulful","emotional"],95,"C minor","soulful Italian baritone","2010s Italian pop soul (pop), soulful baritone, Italian vocals, soul-influenced pop production, emotional mood, fits an Italian Sanremo playlist, 95 BPM, C minor",["pop","Italian pop","2010s","soulful","emotional"]),
  E("it-ramazzotti-2","Andrea Bocelli x classical","it","Итальянские","Classical","Italian opera / pop","1990s",["majestic","sweeping"],75,"D major","operatic Italian tenor","1990s Italian opera pop (classical), operatic tenor, Italian vocals, full orchestra, sweeping arrangements, majestic mood, fits an opera crossover playlist, 75 BPM, D major",["classical","Italian opera","1990s","majestic","sweeping"]),
  E("it-blanco","Blanco","it","Итальянские","Pop","Italian pop / urban","2020s",["raw","emotional"],120,"E minor","raw Italian young tenor","2020s Italian urban pop (pop), raw tenor, Italian vocals, urban pop production, emotional mood, fits a modern Italian playlist, 120 BPM, E minor",["pop","Italian pop","2020s","raw","emotional"]),
  E("it-salmo","Salmo","it","Итальянские","Hip-hop","Italian hip-hop / trap","2010s",["aggressive","versatile"],90,"F minor","aggressive Italian rapper","2010s Italian trap (hip-hop), aggressive versatile rapper, Italian vocals, hard trap production, aggressive mood, fits an Italian trap playlist, 90 BPM, F minor",["hip-hop","Italian hip-hop","2010s","aggressive","versatile"]),
  E("it-sfera-ebbasta","Sfera Ebbasta","it","Итальянские","Hip-hop","Italian trap","2010s",["melodic","Milano"],135,"G minor","auto-tuned Italian trap tenor","2010s Italian trap (hip-hop), auto-tuned tenor, Italian vocals, Milano trap beats, melodic mood, fits an Italian trap playlist, 135 BPM, G minor",["hip-hop","Italian trap","2010s","melodic","Milano"]),
  E("it-cesare-cremonini","Cesare Cremonini","it","Итальянские","Pop","Italian pop rock","2000s",["melodic","romantic"],110,"D major","melodic Italian tenor","2000s Italian pop rock (pop), melodic tenor, Italian vocals, polished pop rock production, romantic mood, fits an Italian pop-rock playlist, 110 BPM, D major",["pop","Italian pop rock","2000s","melodic","romantic"]),
  E("it-negramaro","Negramaro","it","Итальянские","Rock","Italian pop rock","2000s",["passionate","Mediterranean"],115,"E minor","passionate Italian pop-rock tenor","2000s Italian pop rock (rock), passionate tenor, Italian vocals, Mediterranean rock production, passionate mood, fits an Italian rock playlist, 115 BPM, E minor",["rock","Italian pop rock","2000s","passionate","Mediterranean"]),

  // ── INDIAN expand (in: 16 → 25) ───────────────────────────────────────────
  E("in-shreya-ghoshal","Shreya Ghoshal","in","Индийские","Pop","Bollywood playback","2000s",["versatile","melodic"],100,"Raag Yaman","melodic Bollywood playback soprano","2000s Bollywood playback (pop), melodic versatile soprano, Hindi vocals, contemporary Bollywood production, melodic mood, fits a Bollywood favorites playlist, 100 BPM, Raag Yaman",["pop","Bollywood","2000s","versatile","melodic"]),
  E("in-jubin-nautiyal","Jubin Nautiyal","in","Индийские","Pop","Bollywood / romantic","2010s",["romantic","melodic"],95,"E minor","romantic Bollywood tenor","2010s Bollywood (pop), romantic tenor, Hindi vocals, modern Bollywood ballad production, romantic mood, fits a Bollywood ballad playlist, 95 BPM, E minor",["pop","Bollywood","2010s","romantic","melodic"]),
  E("in-armaan-malik","Armaan Malik","in","Индийские","Pop","Bollywood / pop","2010s",["youthful","clean"],100,"G major","youthful Bollywood tenor","2010s Bollywood (pop), youthful clean tenor, Hindi/English vocals, modern pop production, clean mood, fits a contemporary Bollywood playlist, 100 BPM, G major",["pop","Bollywood","2010s","youthful","clean"]),
  E("in-divine","DIVINE","in","Индийские","Hip-hop","Indian hip-hop / Mumbai","2010s",["street","gritty"],95,"D minor","Mumbai gully rap baritone","2010s Indian hip-hop (hip-hop), gritty street baritone, Hindi/English vocals, boom-bap with Indian samples, street mood, fits a desi hip-hop playlist, 95 BPM, D minor",["hip-hop","Indian hip-hop","2010s","street","gritty"],true),
  E("in-naezy","Naezy","in","Индийские","Hip-hop","Indian hip-hop / Mumbai gully","2010s",["street","authentic"],90,"E minor","Mumbai street authentic rapper","2010s Indian gully rap (hip-hop), authentic street rapper, Hindi/Urdu vocals, raw production, street mood, fits a desi underground playlist, 90 BPM, E minor",["hip-hop","Indian hip-hop","2010s","street","authentic"]),
  E("in-yo-yo-honey-singh","Yo Yo Honey Singh","in","Индийские","Hip-hop","Punjabi pop / hip-hop","2010s",["party","catchy"],128,"A minor","catchy Punjabi rap-singer baritone","2010s Punjabi pop hip-hop (hip-hop), catchy baritone, Punjabi/Hindi vocals, party production, party mood, fits a Punjabi party playlist, 128 BPM, A minor",["hip-hop","Punjabi pop","2010s","party","catchy"]),
  E("in-ravi-shankar","Ravi Shankar","in","Индийские","Classical","Hindustani classical / sitar","1960s",["meditative","virtuosic"],85,"Raag Bhairav","sitar maestro instrumental","1960s Hindustani classical (classical), sitar maestro instrumental, no vocals, sitar, tabla, tanpura drone, meditative virtuosic mood, fits an Indian classical playlist, 85 BPM, Raag Bhairav",["classical","Hindustani","1960s","meditative","virtuosic"],true),
  E("in-rd-burman","R.D. Burman","in","Индийские","Soundtrack","Bollywood / film score","1970s",["innovative","experimental"],110,"F major","Bollywood composer / experimental","1970s Bollywood (soundtrack), innovative composer, Hindi vocals (guest singers), Indian-jazz-rock fusion, experimental mood, fits a Bollywood golden age playlist, 110 BPM, F major",["soundtrack","Bollywood","1970s","innovative","experimental"],true),
  E("in-mohit-chauhan","Mohit Chauhan","in","Индийские","Pop","Bollywood / indie pop","2000s",["earnest","mountainous"],105,"G major","earnest Himalayan Bollywood tenor","2000s Bollywood indie (pop), earnest tenor, Hindi vocals, acoustic-driven Bollywood production, earnest mood, fits a Bollywood mellow playlist, 105 BPM, G major",["pop","Bollywood","2000s","earnest","mountainous"]),

  // ── TURKISH expand (tr: 16 → 25) ──────────────────────────────────────────
  E("tr-tarkan","Tarkan","tr","Турецкие","Pop","Turkish pop / Mediterranean","1990s",["sensual","danceable"],118,"A minor","Turkish pop heartthrob tenor","1990s Turkish pop (pop), sensual tenor, Turkish vocals, Mediterranean pop production with darbuka, danceable mood, fits a Turkish pop classics playlist, 118 BPM, A minor",["pop","Turkish pop","1990s","sensual","danceable"],true),
  E("tr-sezen-aksu","Sezen Aksu","tr","Турецкие","Pop","Turkish pop / classical","1980s",["legendary","melodic"],108,"E minor","queen of Turkish pop alto","1980s Turkish pop (pop), legendary alto, Turkish vocals, orchestral Turkish pop, melodic mood, fits a Turkish queen playlist, 108 BPM, E minor",["pop","Turkish pop","1980s","legendary","melodic"],true),
  E("tr-baris-manco","Barış Manço","tr","Турецкие","Rock","Anatolian rock","1970s",["iconic","cultural"],110,"D minor","iconic Anatolian rock baritone","1970s Anatolian rock (rock), iconic baritone, Turkish vocals, electric saz, rock production, cultural mood, fits an Anatolian rock playlist, 110 BPM, D minor",["rock","Anatolian rock","1970s","iconic","cultural"],true),
  E("tr-mfo","MFÖ","tr","Турецкие","Pop","Turkish pop rock","1980s",["witty","catchy"],128,"G major","Turkish pop-rock trio","1980s Turkish pop rock (pop), witty trio, Turkish vocals, melodic pop-rock, catchy mood, fits a Turkish nostalgic playlist, 128 BPM, G major",["pop","Turkish pop rock","1980s","witty","catchy"]),
  E("tr-tarkan-2","Hadise","tr","Турецкие","Pop","Turkish pop / Eurodance","2000s",["danceable","glamorous"],128,"D minor","Belgian-Turkish pop diva","2000s Turkish Eurodance (pop), glamorous soprano, Turkish vocals, Eurodance production, danceable mood, fits a Turkish dance playlist, 128 BPM, D minor",["pop","Turkish pop","2000s","danceable","glamorous"]),
  E("tr-zeki-muren","Zeki Müren","tr","Турецкие","Classical","Turkish classical / sanat","1960s",["theatrical","legendary"],85,"Hicaz","legendary theatrical Turkish art-music tenor","1960s Turkish art music (classical), legendary tenor, Turkish vocals, classical Turkish ensemble, theatrical mood, fits a Turkish classical playlist, 85 BPM, Hicaz",["classical","Turkish classical","1960s","theatrical","legendary"],true),
  E("tr-orhan-gencebay","Orhan Gencebay","tr","Турецкие","Pop","arabesque / Turkish","1970s",["melancholic","arabesque"],90,"Hicaz","arabesque Turkish baritone","1970s Turkish arabesque (pop), melancholic baritone, Turkish vocals, arabesque orchestration with saz, melancholic mood, fits a Turkish arabesque playlist, 90 BPM, Hicaz",["pop","arabesque","1970s","melancholic","arabesque"]),
  E("tr-ibrahim-tatlises","İbrahim Tatlıses","tr","Турецкие","Pop","arabesque / folk","1980s",["powerful","emotional"],95,"Hicaz","powerful arabesque tenor","1980s Turkish arabesque (pop), powerful tenor, Turkish vocals, arabesque-folk fusion, emotional mood, fits a Turkish folk-pop playlist, 95 BPM, Hicaz",["pop","arabesque","1980s","powerful","emotional"]),
  E("tr-mfo-2","Athena","tr","Турецкие","Rock","Turkish ska / rock","1990s",["energetic","fun"],150,"E minor","Turkish ska-rock tenor","1990s Turkish ska rock (rock), energetic tenor, Turkish vocals, ska guitar, brass section, fun mood, fits a Turkish ska playlist, 150 BPM, E minor",["rock","Turkish ska","1990s","energetic","fun"]),

  // ── UKRAINIAN expand (uk: 18 → 28) ────────────────────────────────────────
  E("uk-ruslana","Руслана","uk","Украинские","Pop","Ukrainian pop / world","2000s",["powerful","ethnic"],132,"E minor","powerful Ukrainian Eurovision soprano","2000s Ukrainian pop (pop), powerful soprano, Ukrainian/English vocals, Carpathian folk meets pop, ethnic mood, fits a Eurovision playlist, 132 BPM, E minor",["pop","Ukrainian pop","2000s","powerful","ethnic"],true),
  E("uk-vopli-vidoplyasova","ВВ","uk","Украинские","Rock","Ukrainian folk-rock","1990s",["fun","folk"],128,"A major","Ukrainian folk-rock baritone","1990s Ukrainian folk rock (rock), fun folk-inflected baritone, Ukrainian vocals, accordion, electric guitar, fun mood, fits a Ukrainian folk-rock playlist, 128 BPM, A major",["rock","Ukrainian folk rock","1990s","fun","folk"]),
  E("uk-druga-rika","Друга Ріка","uk","Украинские","Rock","Ukrainian rock","2000s",["melodic","heartfelt"],125,"D minor","melodic Ukrainian rock baritone","2000s Ukrainian rock (rock), melodic baritone, Ukrainian vocals, polished rock production, heartfelt mood, fits a Ukrainian rock playlist, 125 BPM, D minor",["rock","Ukrainian rock","2000s","melodic","heartfelt"]),
  E("uk-svetlana-loboda","Светлана Лобода","uk","Украинские","Pop","Ukrainian pop / dance","2010s",["sensual","glamorous"],120,"F minor","glamorous Ukrainian pop diva","2010s Ukrainian pop (pop), sensual glamorous mezzo, Ukrainian/Russian vocals, dance-pop production, sensual mood, fits a Ukrainian dance pop playlist, 120 BPM, F minor",["pop","Ukrainian pop","2010s","sensual","glamorous"]),
  E("uk-skofka","Skofka","uk","Украинские","Pop","Ukrainian pop / folk","2020s",["heartfelt","patriotic"],95,"D minor","heartfelt Ukrainian young tenor","2020s Ukrainian pop folk (pop), heartfelt tenor, Ukrainian vocals, folk-pop production, patriotic mood, fits a modern Ukrainian playlist, 95 BPM, D minor",["pop","Ukrainian pop","2020s","heartfelt","patriotic"]),
  E("uk-tina-karol","Тіна Кароль","uk","Украинские","Pop","Ukrainian pop","2000s",["bright","heartfelt"],110,"G major","bright Ukrainian pop soprano","2000s Ukrainian pop (pop), bright soprano, Ukrainian vocals, polished pop production, heartfelt mood, fits a Ukrainian mainstream playlist, 110 BPM, G major",["pop","Ukrainian pop","2000s","bright","heartfelt"]),
  E("uk-onuka","ONUKA","uk","Украинские","Electronic","Ukrainian electronica / folk-electronic","2010s",["atmospheric","ethnic"],110,"A minor","atmospheric Ukrainian electronic soprano","2010s Ukrainian electronic folk (electronic), atmospheric soprano, Ukrainian vocals, electronic production with Ukrainian folk instruments, atmospheric mood, fits a modern Ukrainian electronic playlist, 110 BPM, A minor",["electronic","Ukrainian electronic","2010s","atmospheric","ethnic"],true),
  E("uk-svyatoslav-vakarchuk","Святослав Вакарчук","uk","Украинские","Rock","Ukrainian rock / solo","2010s",["anthemic","poetic"],128,"E minor","anthemic Vakarchuk solo tenor","2010s Ukrainian rock (rock), anthemic tenor, Ukrainian vocals, acoustic-driven rock, poetic mood, fits a Ukrainian solo playlist, 128 BPM, E minor",["rock","Ukrainian rock","2010s","anthemic","poetic"]),
  E("uk-monatik","MONATIK","uk","Украинские","Pop","Ukrainian pop / dance","2010s",["danceable","positive"],118,"G major","Ukrainian dance-pop tenor","2010s Ukrainian dance pop (pop), positive tenor, Ukrainian/Russian vocals, dance-pop production, positive mood, fits a Ukrainian dance playlist, 118 BPM, G major",["pop","Ukrainian pop","2010s","danceable","positive"]),
  E("uk-tnmk","ТНМК","uk","Украинские","Hip-hop","Ukrainian hip-hop / fusion","2000s",["fun","fusion"],105,"D minor","Ukrainian hip-hop / funk fusion","2000s Ukrainian hip-hop fusion (hip-hop), fun fusion group, Ukrainian vocals, funk-hip-hop production, fun mood, fits a Ukrainian fusion playlist, 105 BPM, D minor",["hip-hop","Ukrainian hip-hop","2000s","fun","fusion"]),

  // ── ARABIC expand (ar: 20 → 28) ───────────────────────────────────────────
  E("ar-mohamed-mounir","Mohamed Mounir","ar","Арабские","Pop","Egyptian folk pop / Nubian","1980s",["soulful","earthy"],95,"Maqam Rast","earthy Egyptian-Nubian baritone","1980s Egyptian Nubian (pop), earthy baritone, Arabic-Nubian vocals, Nubian folk fused with rock, soulful mood, fits an Egyptian alternative playlist, 95 BPM, Maqam Rast",["pop","Egyptian Nubian","1980s","soulful","earthy"]),
  E("ar-sherine","Sherine","ar","Арабские","Pop","Egyptian pop","2000s",["earthy","powerful"],105,"Maqam Bayati","earthy powerful Egyptian alto","2000s Egyptian pop (pop), earthy powerful alto, Arabic vocals, modern Egyptian pop production, powerful mood, fits an Egyptian pop playlist, 105 BPM, Maqam Bayati",["pop","Egyptian pop","2000s","earthy","powerful"]),
  E("ar-najwa-karam","Najwa Karam","ar","Арабские","Pop","Lebanese pop / dabke","1990s",["dabke","powerful"],128,"Maqam Hijaz","Lebanese mountain-power soprano","1990s Lebanese dabke (pop), powerful soprano, Arabic vocals, dabke rhythms, mijwiz, powerful mood, fits a Lebanese folk playlist, 128 BPM, Maqam Hijaz",["pop","Lebanese pop","1990s","dabke","powerful"]),
  E("ar-saber-rebai","Saber Rebai","ar","Арабские","Pop","Tunisian pop / tarab","2000s",["smooth","romantic"],95,"Maqam Bayati","Tunisian tarab-pop tenor","2000s Tunisian pop (pop), smooth tarab-influenced tenor, Arabic vocals, North African pop production, romantic mood, fits an Arabic romantic playlist, 95 BPM, Maqam Bayati",["pop","Tunisian pop","2000s","smooth","romantic"]),
  E("ar-cheb-khaled","Cheb Khaled","ar","Арабские","Pop","raï","1980s",["soulful","Mediterranean"],110,"Maqam Hijaz","raï king Algerian baritone","1980s raï (pop), soulful Algerian baritone, Arabic vocals, raï production with synths and accordion, Mediterranean mood, fits a North African playlist, 110 BPM, Maqam Hijaz",["pop","raï","1980s","soulful","Mediterranean"],true),
  E("ar-rachid-taha","Rachid Taha","ar","Арабские","Rock","raï rock / Algerian","1990s",["rebellious","fusion"],120,"Maqam Hijaz","gravelly Algerian rock baritone","1990s raï rock (rock), gravelly baritone, Arabic/French vocals, rai-rock fusion, rebellious mood, fits a Maghrebi rock playlist, 120 BPM, Maqam Hijaz",["rock","raï rock","1990s","rebellious","fusion"]),
  E("ar-marcel-khalife","Marcel Khalife","ar","Арабские","Folk","Arabic political folk","1970s",["political","poetic"],85,"Maqam Bayati","poetic Lebanese oud-folk baritone","1970s Arabic political folk (folk), poetic baritone, Arabic vocals, oud-driven, political mood, fits an Arabic poetry playlist, 85 BPM, Maqam Bayati",["folk","Arabic folk","1970s","political","poetic"]),
  E("ar-asalah-nasri-2","Mahmoud El Esseily","ar","Арабские","Pop","Egyptian shaabi pop","2010s",["urban","Egyptian"],110,"Maqam Rast","urban Egyptian shaabi tenor","2010s Egyptian shaabi pop (pop), urban tenor, Arabic vocals, modern shaabi production, Egyptian mood, fits an Egyptian street playlist, 110 BPM, Maqam Rast",["pop","Egyptian pop","2010s","urban","Egyptian"]),

  // ── CHINESE expand (zh: 20 → 28) ──────────────────────────────────────────
  E("zh-andy-lau","Andy Lau","zh","Китайские","Pop","cantopop / classic","1990s",["iconic","earnest"],95,"E minor","iconic cantopop baritone","1990s cantopop (pop), iconic earnest baritone, Cantonese vocals, classic Canto-pop production, earnest mood, fits a HK megastar playlist, 95 BPM, E minor",["pop","cantopop","1990s","iconic","earnest"],true),
  E("zh-leslie-cheung","Leslie Cheung","zh","Китайские","Pop","cantopop / classic","1980s",["sensual","theatrical"],110,"D major","legendary cantopop baritone","1980s cantopop (pop), sensual theatrical baritone, Cantonese vocals, lush cantopop production, theatrical mood, fits a HK cinema playlist, 110 BPM, D major",["pop","cantopop","1980s","sensual","theatrical"],true),
  E("zh-anita-mui","Anita Mui","zh","Китайские","Pop","cantopop / soul","1980s",["versatile","powerful"],118,"G minor","cantopop Madonna mezzo","1980s cantopop (pop), versatile powerful mezzo, Cantonese vocals, dance-pop, ballad production, powerful mood, fits a HK queen playlist, 118 BPM, G minor",["pop","cantopop","1980s","versatile","powerful"],true),
  E("zh-li-yuchun","Li Yuchun","zh","Китайские","Pop","C-pop / rock","2000s",["androgynous","alternative"],128,"E minor","androgynous Chinese pop-rock alto","2000s C-pop rock (pop), androgynous alto, Chinese vocals, rock-pop production, alternative mood, fits a Chinese alternative pop playlist, 128 BPM, E minor",["pop","C-pop","2000s","androgynous","alternative"]),
  E("zh-tfboys","TFBOYS","zh","Китайские","Pop","C-pop / boy band","2010s",["youthful","fresh"],128,"C major","three-member Chinese boy band","2010s C-pop boy band (pop), youthful three-member group, Chinese vocals, polished pop production, fresh mood, fits a Chinese teen pop playlist, 128 BPM, C major",["pop","C-pop","2010s","youthful","fresh"]),
  E("zh-jolin-tsai","Jolin Tsai","zh","Китайские","Pop","mandopop / dance","2000s",["fierce","danceable"],128,"A minor","queen of mandopop dance soprano","2000s mandopop dance (pop), fierce dance-pop soprano, Mandarin vocals, dance-pop production, danceable mood, fits a Taiwan dance playlist, 128 BPM, A minor",["pop","mandopop","2000s","fierce","danceable"]),
  E("zh-yoga-lin-2","Crowd Lu","zh","Китайские","Pop","Taiwanese indie pop","2010s",["whimsical","quirky"],95,"D major","whimsical Taiwanese indie tenor","2010s Taiwanese indie pop (pop), whimsical tenor, Mandarin vocals, indie acoustic production, quirky mood, fits a Taiwanese indie playlist, 95 BPM, D major",["pop","indie pop","2010s","whimsical","quirky"]),
  E("zh-higher-brothers","Higher Brothers","zh","Китайские","Hip-hop","Chinese trap / Chengdu","2010s",["fresh","global"],145,"F minor","four-member Chengdu trap group","2010s Chinese trap (hip-hop), four-member Chengdu group, Mandarin/English vocals, trap beats, fresh global mood, fits a Chinese hip-hop playlist, 145 BPM, F minor",["hip-hop","Chinese trap","2010s","fresh","global"]),

  // ── AFRICAN expand (af: 20 → 28) ──────────────────────────────────────────
  E("af-salif-keita","Salif Keita","af","Африканские","World","Malian / West African","1980s",["soulful","spiritual"],100,"E minor","soaring Malian albino tenor","1980s Malian world (world), soaring tenor, Bambara/French vocals, kora, balafon, West African ensemble, soulful spiritual mood, fits a West African heritage playlist, 100 BPM, E minor",["world","Malian","1980s","soulful","spiritual"]),
  E("af-amadou-mariam","Amadou & Mariam","af","Африканские","World","Malian blues","1990s",["bluesy","tender"],105,"G major","blind Malian couple duo","1990s Malian blues (world), blind couple duo, Bambara/French vocals, electric guitar, Malian percussion, bluesy mood, fits a Malian world music playlist, 105 BPM, G major",["world","Malian blues","1990s","bluesy","tender"]),
  E("af-ali-farka-toure","Ali Farka Touré","af","Африканские","World","Malian desert blues","1980s",["meditative","blues"],95,"E minor","Malian desert-blues guitarist baritone","1980s Malian desert blues (world), meditative baritone, Sonrai/Bambara vocals, hypnotic desert blues guitar, meditative mood, fits a desert blues playlist, 95 BPM, E minor",["world","Malian blues","1980s","meditative","blues"],true),
  E("af-thomas-mapfumo","Thomas Mapfumo","af","Африканские","World","chimurenga / Zimbabwean","1980s",["political","traditional"],115,"D major","Zimbabwean chimurenga lion baritone","1980s Zimbabwean chimurenga (world), political baritone, Shona vocals, mbira-influenced guitar, traditional mood, fits a Southern African playlist, 115 BPM, D major",["world","Zimbabwean","1980s","political","traditional"]),
  E("af-johnny-clegg","Johnny Clegg","af","Африканские","World","South African mbaqanga / world","1980s",["fusion","heartfelt"],120,"G major","white Zulu South African tenor","1980s South African world (world), heartfelt tenor, English/Zulu vocals, mbaqanga fusion, heartfelt mood, fits a South African fusion playlist, 120 BPM, G major",["world","South African","1980s","fusion","heartfelt"]),
  E("af-ladysmith-black-mambazo","Ladysmith Black Mambazo","af","Африканские","World","South African isicathamiya","1980s",["spiritual","harmonic"],85,"D major","South African male choral group","1980s South African isicathamiya (world), male choral group, Zulu vocals, a cappella choral harmonies, spiritual mood, fits a South African choral playlist, 85 BPM, D major",["world","South African","1980s","spiritual","harmonic"],true),
  E("af-cesaria-evora","Cesária Évora","af","Африканские","World","Cape Verdean morna","1990s",["nostalgic","barefoot"],88,"E minor","Cape Verdean barefoot diva alto","1990s Cape Verdean morna (world), nostalgic alto, Portuguese-Creole vocals, acoustic guitar, accordion, nostalgic mood, fits a Cape Verde playlist, 88 BPM, E minor",["world","Cape Verdean","1990s","nostalgic","barefoot"],true),
  E("af-king-promise","King Promise","af","Африканские","Afrobeats","Ghanaian afrobeats","2010s",["smooth","romantic"],102,"D major","smooth Ghanaian afrobeats tenor","2010s Ghanaian afrobeats (afrobeats), smooth tenor, English/Twi vocals, afrobeats production, romantic mood, fits a Ghanaian playlist, 102 BPM, D major",["afrobeats","Ghanaian","2010s","smooth","romantic"]),

  // ── NEW: VIETNAMESE (vi: 0 → 10) ─────────────────────────────────────────
  E("vi-son-tung","Sơn Tùng M-TP","vi","Вьетнамские","Pop","V-pop","2010s",["dreamy","modern"],110,"E minor","Vietnamese pop heartthrob tenor","2010s V-pop (pop), dreamy modern tenor, Vietnamese vocals, K-pop-influenced production, dreamy mood, fits a V-pop playlist, 110 BPM, E minor",["pop","V-pop","2010s","dreamy","modern"],true),
  E("vi-my-tam","Mỹ Tâm","vi","Вьетнамские","Pop","V-pop","2000s",["powerful","emotive"],100,"D major","queen of V-pop soprano","2000s V-pop (pop), powerful emotive soprano, Vietnamese vocals, lush pop production, powerful mood, fits a V-pop classics playlist, 100 BPM, D major",["pop","V-pop","2000s","powerful","emotive"]),
  E("vi-tuan-hung","Tuấn Hưng","vi","Вьетнамские","Pop","V-pop / ballad","2000s",["romantic","passionate"],90,"A minor","passionate Vietnamese ballad tenor","2000s V-pop ballad (pop), passionate tenor, Vietnamese vocals, piano ballads, romantic mood, fits a V-pop ballad playlist, 90 BPM, A minor",["pop","V-pop","2000s","romantic","passionate"]),
  E("vi-den-vau","Đen Vâu","vi","Вьетнамские","Hip-hop","Vietnamese rap / poetry","2010s",["poetic","laid-back"],85,"C minor","poetic laid-back Vietnamese rapper","2010s Vietnamese rap (hip-hop), poetic laid-back rapper, Vietnamese vocals, atmospheric beats, poetic mood, fits a Vietnamese rap playlist, 85 BPM, C minor",["hip-hop","Vietnamese rap","2010s","poetic","laid-back"]),
  E("vi-hoang-thuy-linh","Hoàng Thùy Linh","vi","Вьетнамские","Pop","V-pop / folk fusion","2010s",["ethnic","modern"],115,"E minor","Vietnamese folk-pop fusion soprano","2010s V-pop folk fusion (pop), ethnic modern soprano, Vietnamese vocals, traditional Vietnamese instruments meets electronica, ethnic modern mood, fits a Vietnamese fusion playlist, 115 BPM, E minor",["pop","V-pop","2010s","ethnic","modern"]),
  E("vi-toc-tien","Tóc Tiên","vi","Вьетнамские","Pop","V-pop / dance","2010s",["danceable","fierce"],128,"F minor","Vietnamese dance-pop soprano","2010s V-pop dance (pop), fierce soprano, Vietnamese vocals, modern dance-pop production, danceable mood, fits a Vietnamese dance playlist, 128 BPM, F minor",["pop","V-pop","2010s","danceable","fierce"]),
  E("vi-soobin","Soobin","vi","Вьетнамские","Pop","V-pop","2010s",["smooth","romantic"],105,"G major","smooth Vietnamese V-pop tenor","2010s V-pop (pop), smooth tenor, Vietnamese vocals, modern V-pop production, romantic mood, fits a modern V-pop playlist, 105 BPM, G major",["pop","V-pop","2010s","smooth","romantic"]),
  E("vi-trinh-cong-son","Trịnh Công Sơn","vi","Вьетнамские","Folk","Vietnamese poetic folk","1960s",["poetic","meditative"],88,"D minor","poetic Vietnamese folk baritone","1960s Vietnamese folk (folk), poetic baritone, Vietnamese vocals, acoustic guitar, meditative mood, fits a Vietnamese poetic playlist, 88 BPM, D minor",["folk","Vietnamese folk","1960s","poetic","meditative"],true),
  E("vi-le-quyen","Lệ Quyên","vi","Вьетнамские","Pop","V-pop / bolero","2000s",["nostalgic","sentimental"],85,"E minor","nostalgic Vietnamese bolero soprano","2000s Vietnamese bolero (pop), sentimental soprano, Vietnamese vocals, bolero ballad production, nostalgic mood, fits a Vietnamese bolero playlist, 85 BPM, E minor",["pop","V-pop","2000s","nostalgic","sentimental"]),
  E("vi-bich-phuong","Bích Phương","vi","Вьетнамские","Pop","V-pop / folk pop","2010s",["catchy","folksy"],112,"A minor","catchy Vietnamese folk-pop soprano","2010s V-pop folk pop (pop), catchy soprano, Vietnamese vocals, folk-pop production, folksy mood, fits a Vietnamese pop playlist, 112 BPM, A minor",["pop","V-pop","2010s","catchy","folksy"]),

  // ── NEW: THAI (th: 0 → 10) ───────────────────────────────────────────────
  E("th-bird-thongchai","Bird Thongchai","th","Тайские","Pop","T-pop / luk thung","1980s",["iconic","sunny"],115,"G major","king of T-pop tenor","1980s T-pop (pop), iconic sunny tenor, Thai vocals, classic Thai pop production, sunny mood, fits a Thai classics playlist, 115 BPM, G major",["pop","T-pop","1980s","iconic","sunny"],true),
  E("th-tata-young","Tata Young","th","Тайские","Pop","T-pop / dance","2000s",["fierce","international"],128,"A minor","international Thai pop soprano","2000s T-pop (pop), fierce soprano, Thai/English vocals, dance-pop production, international mood, fits a T-pop international playlist, 128 BPM, A minor",["pop","T-pop","2000s","fierce","international"]),
  E("th-modern-dog","Modern Dog","th","Тайские","Rock","Thai alternative rock","1990s",["alternative","cult"],128,"E minor","Thai alt-rock baritone","1990s Thai alt-rock (rock), alternative baritone, Thai vocals, alternative guitar-driven production, cult mood, fits a Thai indie rock playlist, 128 BPM, E minor",["rock","Thai rock","1990s","alternative","cult"]),
  E("th-bodyslam","Bodyslam","th","Тайские","Rock","Thai rock","2000s",["anthemic","emotional"],135,"D minor","anthemic Thai rock tenor","2000s Thai rock (rock), anthemic emotional tenor, Thai vocals, arena rock production, anthemic mood, fits a Thai rock playlist, 135 BPM, D minor",["rock","Thai rock","2000s","anthemic","emotional"]),
  E("th-palmy","Palmy","th","Тайские","Pop","T-pop / indie","2000s",["sunny","upbeat"],120,"G major","sunny Thai indie pop soprano","2000s T-pop indie (pop), sunny upbeat soprano, Thai vocals, indie pop production, upbeat mood, fits a Thai upbeat playlist, 120 BPM, G major",["pop","T-pop","2000s","sunny","upbeat"]),
  E("th-loso","Loso","th","Тайские","Rock","Thai rock","1990s",["raw","heartfelt"],128,"A minor","raw Thai rock tenor","1990s Thai rock (rock), raw heartfelt tenor, Thai vocals, post-grunge production, raw mood, fits a Thai 90s rock playlist, 128 BPM, A minor",["rock","Thai rock","1990s","raw","heartfelt"]),
  E("th-bowkylion","Bowkylion","th","Тайские","Pop","T-pop / indie folk","2010s",["intimate","melancholic"],88,"D minor","intimate Thai indie soprano","2010s T-pop indie folk (pop), intimate melancholic soprano, Thai vocals, acoustic indie production, melancholic mood, fits a Thai indie folk playlist, 88 BPM, D minor",["pop","T-pop","2010s","intimate","melancholic"]),
  E("th-milli","Milli","th","Тайские","Hip-hop","T-rap","2020s",["fierce","youthful"],140,"F minor","fierce young Thai female rapper","2020s T-rap (hip-hop), fierce youthful female rapper, Thai vocals, modern trap production, fierce mood, fits a T-rap playlist, 140 BPM, F minor",["hip-hop","T-rap","2020s","fierce","youthful"]),
  E("th-three-man-down","Three Man Down","th","Тайские","Pop","T-pop / indie pop","2010s",["catchy","wistful"],105,"G major","Thai indie pop boy trio","2010s T-pop indie (pop), wistful catchy trio, Thai vocals, indie pop production, wistful mood, fits a modern Thai indie playlist, 105 BPM, G major",["pop","T-pop","2010s","catchy","wistful"]),
  E("th-violette-wautier","Violette Wautier","th","Тайские","Pop","T-pop indie / folk","2010s",["smoky","intimate"],95,"C minor","smoky Thai-Belgian indie soprano","2010s T-pop indie folk (pop), smoky intimate soprano, Thai/English vocals, indie acoustic production, intimate mood, fits a Thai indie playlist, 95 BPM, C minor",["pop","T-pop","2010s","smoky","intimate"]),

  // ── NEW: GREEK (el: 0 → 8) ───────────────────────────────────────────────
  E("el-mikis-theodorakis","Mikis Theodorakis","el","Греческие","Folk","Greek folk / political","1960s",["epic","political"],105,"D minor","Greek composer / political icon","1960s Greek folk (folk), epic composer-led works (chorus/baritone vocals), Greek vocals, bouzouki, orchestral arrangements, political epic mood, fits a Greek classics playlist, 105 BPM, D minor",["folk","Greek folk","1960s","epic","political"],true),
  E("el-haris-alexiou","Haris Alexiou","el","Греческие","Pop","Greek laiko / folk pop","1980s",["soulful","melancholic"],95,"D minor","soulful Greek alto","1980s Greek laiko (pop), soulful melancholic alto, Greek vocals, bouzouki, folk-pop arrangements, melancholic mood, fits a Greek folk-pop playlist, 95 BPM, D minor",["pop","Greek laiko","1980s","soulful","melancholic"],true),
  E("el-anna-vissi","Anna Vissi","el","Греческие","Pop","Greek pop / Eurovision","1990s",["dramatic","theatrical"],120,"E minor","Greek pop diva mezzo","1990s Greek pop (pop), dramatic theatrical mezzo, Greek vocals, Eurodance-pop production, theatrical mood, fits a Greek pop diva playlist, 120 BPM, E minor",["pop","Greek pop","1990s","dramatic","theatrical"]),
  E("el-nikos-vertis","Nikos Vertis","el","Греческие","Pop","Greek laiko-pop","2000s",["sentimental","romantic"],100,"A minor","sentimental Greek tenor","2000s Greek laiko-pop (pop), sentimental tenor, Greek vocals, modern laiko production, romantic mood, fits a Greek modern laiko playlist, 100 BPM, A minor",["pop","Greek laiko","2000s","sentimental","romantic"]),
  E("el-eleftheria-arvanitaki","Eleftheria Arvanitaki","el","Греческие","Folk","Greek folk fusion","1990s",["jazzy","Mediterranean"],100,"D minor","Greek folk-jazz alto","1990s Greek folk fusion (folk), jazzy Mediterranean alto, Greek vocals, Mediterranean jazz arrangements, jazzy mood, fits a Greek folk-fusion playlist, 100 BPM, D minor",["folk","Greek folk","1990s","jazzy","Mediterranean"]),
  E("el-helena-paparizou","Helena Paparizou","el","Греческие","Pop","Greek Eurovision pop","2000s",["catchy","glamorous"],128,"D minor","Greek-Swedish Eurovision pop soprano","2000s Greek pop (pop), catchy glamorous soprano, Greek/English vocals, Eurovision dance-pop production, glamorous mood, fits a Greek Eurovision playlist, 128 BPM, D minor",["pop","Greek pop","2000s","catchy","glamorous"]),
  E("el-stelios-kazantzidis","Stelios Kazantzidis","el","Греческие","Folk","Greek laiko / classic","1950s",["legendary","mournful"],90,"D minor","legendary Greek laiko baritone","1950s Greek laiko (folk), legendary mournful baritone, Greek vocals, bouzouki-led arrangements, mournful mood, fits a Greek classics playlist, 90 BPM, D minor",["folk","Greek laiko","1950s","legendary","mournful"],true),
  E("el-light","Light","el","Греческие","Hip-hop","Greek trap","2010s",["street","modern"],140,"G minor","Greek street trap rapper","2010s Greek trap (hip-hop), street rapper, Greek vocals, modern trap production, street mood, fits a Greek hip-hop playlist, 140 BPM, G minor",["hip-hop","Greek hip-hop","2010s","street","modern"]),
];

const toAdd = newEntries.filter(e => !existingNames.has(e.name.toLowerCase()));
const combined = [...existing, ...toAdd];

await writeFile(dataPath, JSON.stringify(combined, null, 2), "utf8");
console.log(`Added ${toAdd.length} entries. Total: ${combined.length}`);
const skipped = newEntries.filter(e => existingNames.has(e.name.toLowerCase())).map(e => e.name);
if (skipped.length) console.log("Skipped (already exist):", skipped.join(", "));
